const $=s=>document.querySelector(s);let state=null,tab='Adventure',lastLog=[];const playerId='demo';
const api=async(path,opt={})=>{const r=await fetch(path,{headers:{'content-type':'application/json'},...opt});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Request failed');return j};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function load(){state=await api('/api/state?playerId='+playerId);render()}
async function action(action,payload={}){try{const r=await api('/api/action',{method:'POST',body:JSON.stringify({playerId,action,payload})});state=r;if(r.log)lastLog=r.log;toast(r.message||'Done');render()}catch(e){toast(e.message)}}
function stats(){const p=state.player;const eq=Object.values(p.equipment).map(id=>p.inventory.find(i=>i.id===id)).filter(Boolean);return {atk:p.stats.atk+eq.reduce((n,i)=>n+(i.atk||0),0),def:p.stats.def+eq.reduce((n,i)=>n+(i.def||0),0)}}
function renderHud(){const p=state.player,s=stats();$('#hud').innerHTML=`<div class="hud">${[['Level',p.level],['Gold',p.gold],['Energy',p.energy+'/'+p.maxEnergy],['HP',p.hp+'/'+p.maxHp],['ATK',s.atk],['DEF',s.def]].map(x=>`<div class=stat><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>`}
function renderTabs(){const tabs=['Adventure','Combat','Inventory','Crafting','Market','Quests','Web3'];$('#tabs').innerHTML=tabs.map(t=>`<button data-tab="${t}" class="${tab===t?'active':''}">${t}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()})}
function adventure(){const p=state.player;return `<div class=grid><div class=card><h3>⛏ Deep Shafts</h3><p>Spend energy to extract ore used by equipment recipes.</p><div class=row><span>Ore <b>${p.resources.ore}</b></span><button class=primary data-a=mine>Mine</button></div></div><div class=card><h3>🌲 Wildlands</h3><p>Gather timber and reagents for crafting chains.</p><div class=row><span>Wood <b>${p.resources.wood}</b></span><button class=primary data-a=harvest>Harvest</button></div></div><div class=card><h3>🎣 Moonwater Coast</h3><p>Fishing creates consumable ingredients and trade goods.</p><div class=row><span>Fish <b>${p.resources.fish}</b></span><button class=primary data-a=fish>Fish</button></div></div><div class=card><h3>🏕 Bastion</h3><p>Recover health and part of your energy reserve.</p><button data-a=rest>Rest</button></div><div class=card><h3>Core loop</h3><p>Gather → Craft → Equip → Fight → Trade → Upgrade. The backend validates every reward.</p></div><div class=card><h3>Progress</h3><p>XP ${p.xp}/${p.level*100}. Energy regenerates automatically at 1 point per minute.</p></div></div>`}
function combat(){return `<div class=grid>${state.enemies.map(e=>`<div class=card><div class=row><h3>${esc(e.name)}</h3><span class=pill>Lv ${e.level}</span></div><p>HP ${e.hp} · ATK ${e.atk} · DEF ${e.def}</p><p>Reward ${e.reward.gold} gold / ${e.reward.xp} XP</p><button class=primary data-enemy="${e.id}">Fight</button></div>`).join('')}</div>${lastLog.length?`<div class=card style="margin-top:10px"><h3>Combat Log</h3><div class=log>${lastLog.map(x=>`<div>${esc(x)}</div>`).join('')}</div></div>`:''}`}
function inventory(){const p=state.player;return `<div class=list>${p.inventory.map(i=>`<div class=item><div class=row><div><b class="${i.rarity}">${esc(i.name)}</b><div class=muted>${i.type} · ${i.rarity} · ATK ${i.atk||0} · DEF ${i.def||0}</div></div><div class=actions>${i.slot?`<button data-equip="${i.id}">${p.equipment[i.slot]===i.id?'Equipped':'Equip'}</button>`:''}<button data-sell="${i.id}">Sell</button></div></div></div>`).join('')||'<div class=card>Inventory empty.</div>'}</div>`}
function crafting(){const p=state.player;return `<div class=grid>${state.recipes.map(r=>{const can=Object.entries(r.cost).every(([k,v])=>(p.resources[k]||0)>=v);return `<div class=card><h3>${esc(r.name)}</h3><p>${Object.entries(r.cost).map(([k,v])=>`${v} ${k}`).join(' · ')}</p><button ${can?'':'disabled'} data-craft="${r.id}">Craft</button></div>`}).join('')}</div>`}
function market(){return `<div class=list>${state.market.map(m=>`<div class=item><div class=row><div><b class="${m.rarity}">${esc(m.name)}</b><div class=muted>${m.rarity} · ATK ${m.atk||0} · DEF ${m.def||0} · seller ${esc(m.seller)}</div></div><div><b>${m.price}g</b> <button data-buy="${m.id}" ${m.seller===playerId?'disabled':''}>Buy</button></div></div></div>`).join('')||'<div class=card>No listings.</div>'}<div class=card><p>5% market fee is removed from circulation on completed purchases.</p></div></div>`}
function quests(){const p=state.player;return `<div class=grid>${state.quests.map(q=>{const v=p.questProgress[q.kind]||0,done=v>=q.target,claimed=p.completedQuests.includes(q.id);return `<div class="card quest ${done?'done':''}"><h3>${esc(q.name)}</h3><p>${q.kind}: ${v}/${q.target}</p><p>Reward ${q.reward.gold} gold + ${q.reward.xp} XP</p><button data-quest="${q.id}" ${!done||claimed?'disabled':''}>${claimed?'Claimed':'Claim'}</button></div>`}).join('')}</div>`}
function web3(){const p=state.player;return `<div class=grid><div class=card><h3>Wallet</h3><p>${p.wallet?`Connected: ${esc(p.wallet)}`:'Demo mode works without a blockchain wallet.'}</p><div class=actions><button id=wallet>${p.wallet?'Reconnect':'Connect EVM wallet'}</button><button id=disconnect class=ghost>Disconnect</button></div></div><div class=card><h3>Hybrid architecture</h3><p>Combat and ordinary progression stay server-authoritative. Scarce ownership and explicit settlement can be tokenized through the included contracts.</p></div><div class=card><h3>Safety</h3><p>This client never asks for a seed phrase or private key. Browser-wallet login only requests an account address.</p></div></div>`}
function render(){if(!state)return;renderHud();renderTabs();const fn={Adventure:adventure,Combat:combat,Inventory:inventory,Crafting:crafting,Market:market,Quests:quests,Web3:web3}[tab];$('#panel').innerHTML=fn();bind()}
function bind(){document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>action(b.dataset.a));document.querySelectorAll('[data-enemy]').forEach(b=>b.onclick=()=>action('combat',{enemyId:b.dataset.enemy}));document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>action('equip',{itemId:b.dataset.equip}));document.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>action('craft',{recipeId:b.dataset.craft}));document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>action('buy',{listingId:b.dataset.buy}));document.querySelectorAll('[data-quest]').forEach(b=>b.onclick=()=>action('claimQuest',{questId:b.dataset.quest}));document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>{const price=prompt('Listing price in gold','25');if(price)action('sell',{itemId:b.dataset.sell,price:Number(price)})});const w=$('#wallet');if(w)w.onclick=async()=>{try{if(!window.ethereum)throw new Error('No EVM browser wallet detected');const [addr]=await window.ethereum.request({method:'eth_requestAccounts'});await action('wallet',{address:addr})}catch(e){toast(e.message)}};const d=$('#disconnect');if(d)d.onclick=()=>action('wallet',{address:''})}
$('#reset').onclick=async()=>{if(confirm('Reset demo progress?')){await api('/api/reset',{method:'POST'});lastLog=[];load()}};load();setInterval(load,60_000);
