(()=>{const l=document.createElement('link');l.rel='stylesheet';l.href='/responsive.css?v=20260825';document.head.appendChild(l)})();
const API='/api/v1';let mode='register';
const modal=document.getElementById('modal'),displayName=document.getElementById('displayName'),result=document.getElementById('authResult');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('cfs_csrf='))?.split('=')[1]||''}
async function api(path,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};if((opt.method||'GET').toUpperCase()!=='GET')opt.headers['X-CSRF-Token']=csrf();const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail?.message||`HTTP ${r.status}`);return d}
function openModal(m){mode=m;modal.classList.remove('hidden');document.getElementById('modalTitle').textContent=m==='login'?'Iniciar sesión':'Crear cuenta';displayName.style.display=m==='login'?'none':'block';result.textContent='';setTimeout(()=>document.getElementById(m==='login'?'email':'displayName')?.focus(),50)}
function closeModal(){modal.classList.add('hidden')}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
async function renderSession(){const actions=document.querySelector('.top-actions');if(!actions)return;try{const me=await api('/me');actions.innerHTML=`<a class="ghost session-account" href="/profile.html">${esc(me.user.display_name)}</a>${me.creator?'<a class="ghost session-studio" href="/creator.html">Studio</a>':''}<button class="primary session-logout" type="button">Cerrar sesión</button>`;actions.querySelector('.session-logout').addEventListener('click',async()=>{try{await api('/auth/logout',{method:'POST'});showToast('Sesión cerrada');await renderSession()}catch(e){showToast(e.message)}});document.body.classList.add('is-authenticated');document.body.classList.remove('is-anonymous')}catch{actions.innerHTML='<button class="ghost auth-open" type="button" data-open="login">Iniciar sesión</button><button class="primary auth-open" type="button" data-open="register">Crear cuenta</button>';actions.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));document.body.classList.add('is-anonymous');document.body.classList.remove('is-authenticated')}}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.open)));
document.querySelector('.close')?.addEventListener('click',closeModal);
modal?.addEventListener('click',e=>{if(e.target===modal)closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal?.classList.contains('hidden'))closeModal()});
document.getElementById('authForm').addEventListener('submit',async e=>{e.preventDefault();const submit=e.currentTarget.querySelector('button[type="submit"]');const body={email:document.getElementById('email').value,password:document.getElementById('password').value};if(mode==='register')body.display_name=displayName.value;try{submit.disabled=true;submit.textContent=mode==='login'?'Entrando…':'Creando cuenta…';const r=await fetch(`${API}/auth/${mode}`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail?.message||'No se pudo continuar');result.textContent=`✓ Sesión segura iniciada como ${d.user.display_name}`;showToast('Cuenta conectada');await renderSession();setTimeout(closeModal,450)}catch(err){result.textContent='⚠ '+err.message}finally{submit.disabled=false;submit.textContent='Continuar'}});
document.getElementById('featuredPlay')?.addEventListener('click',()=>showToast('Crypto Factory Web está en integración de staging'));
document.getElementById('factoryPlay')?.addEventListener('click',()=>showToast('Build Web de Crypto Factory: staging'));
async function loadPublishedGames(){try{const r=await fetch('/api/v1/games');const d=await r.json();const grid=document.getElementById('gameGrid');if(!grid)return;for(const g of d.games){if(['crypto-factory','cryptoquest-rpg'].includes(g.slug))continue;const a=document.createElement('article');a.className='game-card';a.innerHTML=`<div class="game-art"><span class="status live">PUBLISHED</span><span class="art-number">WEB</span></div><div class="game-info"><span class="genre">${esc(g.genre)}</span><h3>${esc(g.title)}</h3><p>${esc(g.description||'Juego de la comunidad.')}</p><div class="card-row"><span>${esc(g.creator_name)}</span><a class="small primary" href="/game.html?slug=${encodeURIComponent(g.slug)}">Ver juego</a></div></div>`;grid.insertBefore(a,grid.lastElementChild)}}catch(e){console.warn('catalog unavailable')}}
renderSession();loadPublishedGames();