import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
let state=null,tab='Adventure',lastLog=[],session=null;

function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function authHeaders(){return session?.access_token?{'authorization':`Bearer ${session.access_token}`}:{}}
async function api(path,opt={}){const r=await fetch(path,{...opt,headers:{'content-type':'application/json',...authHeaders(),...(opt.headers||{})}});let j={};try{j=await r.json()}catch{}if(r.status===401){await supabase.auth.signOut();throw new Error('Sesión expirada')}if(!r.ok||j.error)throw new Error(j.error||'Request failed');return j}

function setLoggedInUi(logged){$('#logout').hidden=!logged;$('#reset').hidden=!logged}
function renderAuth(message='Inicia sesión para guardar tu progreso permanentemente.'){
  state=null;setLoggedInUi(false);$('#hud').innerHTML='';$('#tabs').innerHTML='';
  $('#panel').innerHTML=`<div class="auth-wrap"><div class="card auth-card"><span class="eyebrow">CUENTA DE JUGADOR</span><h2>Nexus Realms</h2><p>${esc(message)}</p><div class="auth-grid"><form id="login-form"><h3>Iniciar sesión</h3><label>Email<input id="login-email" type="email" autocomplete="email" required></label><label>Contraseña<input id="login-password" type="password" autocomplete="current-password" minlength="6" required></label><button class="primary" type="submit">Entrar</button></form><form id="signup-form"><h3>Crear cuenta</h3><label>Nombre de jugador<input id="signup-username" maxlength="24" autocomplete="nickname" required></label><label>Email<input id="signup-email" type="email" autocomplete="email" required></label><label>Contraseña<input id="signup-password" type="password" autocomplete="new-password" minlength="6" required></label><label>Clase<select id="signup-class"><option value="warrior">Guerrero</option><option value="mage">Mago</option><option value="archer">Arquero</option><option value="assassin">Asesino</option></select></label><button class="primary" type="submit">Crear personaje</button></form></div><p class="muted">Pagos, depósitos y retiros permanecen desactivados. La wallet es opcional y solo está en modo demo.</p></div></div>`;
  $('#login-form').onsubmit=async e=>{e.preventDefault();try{const {data,error}=await supabase.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error)throw error;session=data.session;toast('Sesión iniciada');await load()}catch(err){toast(err.message)}};
  $('#signup-form').onsubmit=async e=>{e.preventDefault();try{const username=$('#signup-username').value.trim(),email=$('#signup-email').value.trim(),password=$('#signup-password').value,playerClass=$('#signup-class').value;const {data,error}=await supabase.auth.signUp({email,password,options:{data:{username,class:playerClass}}});if(error)throw error;if(data.session){session=data.session;toast('Cuenta creada');await load()}else renderAuth('Cuenta creada. Revisa el correo de confirmación y después inicia sesión.')}catch(err){toast(err.message)}};
}

async function load(){if(!session)return renderAuth();try{state=await api('/api/state');setLoggedInUi(true);render()}catch(e){toast(e.message)}}
async function action(action,payload={}){try{const r=await api('/api/action',{method:'POST',body:JSON.stringify({action,payload})});state=r;if(r.log)lastLog=r.log;toast(r.message||'Listo');render()}catch(e){toast(e.message)}}
function stats(){const p=state.player;const eq=Object.values(p.equipment).map(id=>p.inventory.find(i=>i.id===id)).filter(Boolean);return {atk:p.stats.atk+eq.reduce((n,i)=>n+(i.atk||0),0),def:p.stats.def+eq.reduce((n,i)=>n+(i.def||0),0)}}
function renderHud(){const p=state.player,s=stats();$('#hud').innerHTML=`<div class="player-line"><div><b>${esc(p.name)}</b><span>${esc(({warrior:'Guerrero',mage:'Mago',archer:'Arquero',assassin:'Asesino'})[p.class]||p.class)}</span></div></div><div class="hud">${[['Nivel',p.level],['Oro',p.gold],['Energía',p.energy+'/'+p.maxEnergy],['HP',p.hp+'/'+p.maxHp],['ATK',s.atk],['DEF',s.def]].map(x=>`<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>`}
function renderTabs(){const tabs=['Adventure','Combat','Inventory','Crafting','Market','Quests','Web3'];$('#tabs').innerHTML=tabs.map(t=>`<button data-tab="${t}" class="${tab===t?'active':''}">${({Adventure:'Aventura',Combat:'Combate',Inventory:'Inventario',Crafting:'Crafteo',Market:'Mercado',Quests:'Misiones',Web3:'Web3'})[t]}</button>`).join('');document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()})}
function adventure(){const p=state.player;return `<div class="grid"><div class="card"><h3>⛏ Mina profunda</h3><p>Gasta energía para extraer mineral.</p><div class="row"><span>Mineral <b>${p.resources.ore}</b></span><button class="primary" data-a="mine">Minar</button></div></div><div class="card"><h3>🌲 Tierras salvajes</h3><p>Recolecta madera para fabricar equipo.</p><div class="row"><span>Madera <b>${p.resources.wood}</b></span><button class="primary" data-a="harvest">Recolectar</button></div></div><div class="card"><h3>🎣 Costa Moonwater</h3><p>Pesca ingredientes y recursos.</p><div class="row"><span>Pez <b>${p.resources.fish}</b></span><button class="primary" data-a="fish">Pescar</button></div></div><div class="card"><h3>🏕 Bastión</h3><p>Recupera la vida y parte de la energía.</p><button data-a="rest">Descansar</button></div><div class="card"><h3>Bucle principal</h3><p>Recolectar → Fabricar → Equipar → Combatir → Comerciar → Mejorar.</p></div><div class="card"><h3>Progreso persistente</h3><p>XP ${p.xp}/${p.level*100}. La energía regenera automáticamente a 1 punto por minuto y el progreso se guarda en Supabase.</p></div></div>`}
function combat(){return `<div class="grid">${state.enemies.map(e=>`<div class="card"><div class="row"><h3>${esc(e.name)}</h3><span class="pill">Nv ${e.level}</span></div><p>HP ${e.hp} · ATK ${e.atk} · DEF ${e.def}</p><p>Recompensa ${e.reward.gold} oro / ${e.reward.xp} XP</p><button class="primary" data-enemy="${e.id}">Combatir</button></div>`).join('')}</div>${lastLog.length?`<div class="card" style="margin-top:10px"><h3>Registro de combate</h3><div class="log">${lastLog.map(x=>`<div>${esc(x)}</div>`).join('')}</div></div>`:''}`}
function inventory(){const p=state.player;return `<div class="list">${p.inventory.map(i=>`<div class="item"><div class="row"><div><b class="${i.rarity}">${esc(i.name)}</b><div class="muted">${esc(i.type)} · ${i.rarity} · ATK ${i.atk||0} · DEF ${i.def||0}</div></div><div class="actions">${i.slot?`<button data-equip="${i.id}">${p.equipment[i.slot]===i.id?'Equipado':'Equipar'}</button>`:''}<button data-sell="${i.id}">Vender</button></div></div></div>`).join('')||'<div class="card">Inventario vacío.</div>'}</div>`}
function crafting(){const p=state.player;return `<div class="grid">${state.recipes.map(r=>{const can=Object.entries(r.cost).every(([k,v])=>(p.resources[k]||0)>=v);return `<div class="card"><h3>${esc(r.name)}</h3><p>${Object.entries(r.cost).map(([k,v])=>`${v} ${k}`).join(' · ')}</p><button ${can?'':'disabled'} data-craft="${r.id}">Fabricar</button></div>`}).join('')}</div>`}
function market(){return `<div class="list">${state.market.map(m=>`<div class="item"><div class="row"><div><b class="${m.rarity}">${esc(m.name)}</b><div class="muted">${m.rarity} · ATK ${m.atk||0} · DEF ${m.def||0} · vendedor ${esc(m.seller)}</div></div><div><b>${m.price}g</b> <button data-buy="${m.id}" ${m.seller===state.player.id?'disabled':''}>Comprar</button></div></div></div>`).join('')||'<div class="card">No hay anuncios.</div>'}<div class="card"><p>Mercado DEMO: comisión interna del 5 %. No mueve criptomonedas ni dinero real.</p></div></div>`}
function quests(){const p=state.player;return `<div class="grid">${state.quests.map(q=>{const v=p.questProgress[q.kind]||0,done=v>=q.target,claimed=p.completedQuests.includes(q.id);return `<div class="card quest ${done?'done':''}"><h3>${esc(q.name)}</h3><p>${q.kind}: ${v}/${q.target}</p><p>Recompensa ${q.reward.gold} oro + ${q.reward.xp} XP</p><button data-quest="${q.id}" ${!done||claimed?'disabled':''}>${claimed?'Reclamada':'Reclamar'}</button></div>`}).join('')}</div>`}
function web3(){const p=state.player;return `<div class="grid"><div class="card"><h3>Wallet opcional</h3><p>${p.wallet?`Conectada: ${esc(p.wallet)}`:'El juego funciona sin wallet blockchain.'}</p><div class="actions"><button id="wallet">${p.wallet?'Reconectar':'Conectar wallet EVM'}</button><button id="disconnect" class="ghost">Desconectar</button></div></div><div class="card"><h3>Arquitectura híbrida</h3><p>El progreso ordinario se valida en servidor. La capa Web3 permanece desacoplada.</p></div><div class="card"><h3>Dinero real bloqueado</h3><p>Depósitos, pagos, retiros, cash-out, tokens y tesorería real están desactivados hasta la fase final.</p></div></div>`}
function render(){if(!state)return;renderHud();renderTabs();const fn={Adventure:adventure,Combat:combat,Inventory:inventory,Crafting:crafting,Market:market,Quests:quests,Web3:web3}[tab];$('#panel').innerHTML=fn();bind()}
function bind(){document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>action(b.dataset.a));document.querySelectorAll('[data-enemy]').forEach(b=>b.onclick=()=>action('combat',{enemyId:b.dataset.enemy}));document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>action('equip',{itemId:b.dataset.equip}));document.querySelectorAll('[data-craft]').forEach(b=>b.onclick=()=>action('craft',{recipeId:b.dataset.craft}));document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>action('buy',{listingId:b.dataset.buy}));document.querySelectorAll('[data-quest]').forEach(b=>b.onclick=()=>action('claimQuest',{questId:b.dataset.quest}));document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>{const price=prompt('Precio en oro','25');if(price)action('sell',{itemId:b.dataset.sell,price:Number(price)})});const w=$('#wallet');if(w)w.onclick=async()=>{try{if(!window.ethereum)throw new Error('No se detectó wallet EVM en este navegador');const [addr]=await window.ethereum.request({method:'eth_requestAccounts'});await action('wallet',{address:addr,chainId:56})}catch(e){toast(e.message)}};const d=$('#disconnect');if(d)d.onclick=()=>action('wallet',{address:''})}

$('#reset').onclick=async()=>{if(confirm('¿Reiniciar únicamente tu progreso de prueba?')){try{state=await api('/api/reset',{method:'POST',body:'{}'});lastLog=[];toast('Progreso demo reiniciado');render()}catch(e){toast(e.message)}}};
$('#logout').onclick=async()=>{await supabase.auth.signOut();session=null;renderAuth('Sesión cerrada. Tu progreso sigue guardado.')};
supabase.auth.onAuthStateChange((_event,newSession)=>{session=newSession;if(newSession)load();else renderAuth()});
const {data:{session:initialSession}}=await supabase.auth.getSession();session=initialSession;if(session)await load();else renderAuth();
