const API='/api/v1';
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('cfs_csrf='))?.split('=')[1]||''}
let products=[],methods=[],selectedProduct=null,selectedMethod=null,currentQuote=null,currentOrder=null,paymentMode='OFFLINE',authenticated=false;
const $=id=>document.getElementById(id);
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
async function api(path,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};if((opt.method||'GET').toUpperCase()!=='GET')opt.headers['X-CSRF-Token']=csrf();const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail?.message||`HTTP ${r.status}`);return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function isRealPayments(){return paymentMode==='PRODUCTION'}
function methodLabel(m){if(m.method_id==='usdt_tron')return ['USDT','TRON','TRC-20'];if(m.method_id==='usdt_bsc')return ['USDT','BNB SMART CHAIN','BEP-20'];return [m.asset||'CRYPTO',m.network||'',m.standard||'']}
function clearCheckout(){currentQuote=null;currentOrder=null;$('checkoutOrder').textContent='Todavía no creado';$('paymentDetails').classList.add('hidden');$('payAmount').textContent='—';$('payAsset').textContent='—';$('payAddress').textContent='—';$('paymentStatus').textContent='AWAITING_PAYMENT';$('txInput').value=''}
async function init(){
 try{const pm=await api('/payments/methods');paymentMode=String(pm.mode||'OFFLINE').toUpperCase();methods=(pm.methods||[]).filter(m=>['usdt_tron','usdt_bsc'].includes(m.method_id));$('modeBadge').textContent=paymentMode;$('modeBadge').className='mode-badge '+paymentMode.toLowerCase()}catch(e){paymentMode='OFFLINE';methods=[];$('modeBadge').textContent='OFFLINE'}
 try{const p=await api('/products');products=p.products||[];renderProducts()}catch(e){$('productCards').innerHTML='<div class="error-card">No se pudo cargar el catálogo.</div>'}
 try{const me=await api('/me');authenticated=true;const creator=me.creator;$('accountPlan').textContent=creator?`${me.user.display_name} · ${creator.plan_id.toUpperCase()}`:me.user.display_name;if(creator?.billing_exempt)$('accountPlan').textContent+=' · BILLING EXEMPT';await loadPurchases()}catch(e){authenticated=false;$('accountPlan').innerHTML='<a href="/">Inicia sesión para comprar</a>';$('purchaseHistory').innerHTML='<div class="muted">Debes iniciar sesión antes de crear una orden.</div>'}
}
function renderProducts(){$('productCards').innerHTML=products.map((p,i)=>`<article class="product-card ${i===0?'featured':''}"><div class="product-glow"></div><span class="plan-tag">${i===0?'RECOMMENDED':'CREATOR TIER'}</span><h3>${esc(p.label)}</h3><p>${esc(p.description)}</p><div class="product-price"><span>$</span><strong>${esc(p.price_usd)}</strong><small>USD</small></div><ul>${p.product_id.includes('plus')?'<li>More games & storage</li><li>Advanced analytics</li><li>Private/staging builds</li>':'<li>Higher platform limits</li><li>Professional creator tools</li><li>Team-ready architecture</li>'}</ul><button class="primary full select-plan" type="button" data-product-id="${esc(p.product_id)}">SELECCIONAR</button></article>`).join('');document.querySelectorAll('.select-plan').forEach(button=>button.addEventListener('click',()=>chooseProduct(button.dataset.productId)))}
function chooseProduct(id){if(!authenticated){toast('Primero inicia sesión');setTimeout(()=>location.href='/',500);return}selectedProduct=products.find(p=>p.product_id===id);if(!selectedProduct){toast('No se pudo seleccionar el plan');return}clearCheckout();$('terminalEmpty').classList.add('hidden');$('terminalFlow').classList.remove('hidden');$('checkoutProduct').textContent=selectedProduct.label;$('checkoutFiat').textContent=`$${selectedProduct.price_usd} USD`;$('terminalMessage').textContent=isRealPayments()?'Selecciona la red y crea una orden nueva.':'MODO DE PRUEBA: no envíes criptomonedas reales.';renderMethods();document.querySelectorAll('.select-plan').forEach(button=>button.classList.toggle('active',button.dataset.productId===id));$('terminal')?.scrollIntoView({behavior:'smooth',block:'start'})}
function selectMethod(id){if(selectedMethod===id)return;selectedMethod=id;clearCheckout();document.querySelectorAll('.method-choice').forEach(x=>x.classList.toggle('active',x.dataset.id===id));$('terminalMessage').textContent='Red seleccionada. Crea una orden nueva para obtener su importe y dirección.'}
function renderMethods(){selectedMethod=methods[0]?.method_id||null;if(!selectedMethod){$('methodButtons').innerHTML='<div class="error-card">No hay redes de pago disponibles en este momento.</div>';return}$('methodButtons').innerHTML=methods.map((m,i)=>{const [asset,network,standard]=methodLabel(m);return `<button class="method-choice ${i===0?'active':''}" type="button" data-id="${esc(m.method_id)}"><span><b>${esc(asset)}</b><small>${esc(network)} · ${esc(standard)}</small></span><small>${isRealPayments()&&m.production_allowed?'PRODUCTION':'TEST ONLY'}</small></button>`}).join('');document.querySelectorAll('.method-choice').forEach(b=>b.addEventListener('click',()=>selectMethod(b.dataset.id)))}
$('createOrderBtn').addEventListener('click',async()=>{if(!selectedProduct||!selectedMethod){toast('Selecciona un plan y una red');return}try{$('createOrderBtn').disabled=true;$('createOrderBtn').textContent='CREANDO…';$('terminalMessage').textContent='Creando quote y order server-side…';currentQuote=await api('/payments/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:selectedProduct.product_id,method_id:selectedMethod})});const idem='web-'+crypto.randomUUID();currentOrder=await api('/payments/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quote_id:currentQuote.quote_id,idempotency_key:idem})});await showCheckout()}catch(e){$('terminalMessage').textContent='⚠ '+e.message;toast(e.message)}finally{$('createOrderBtn').disabled=false;$('createOrderBtn').textContent='CREAR ORDEN SEGURA'}})
async function showCheckout(){const d=await api(`/payments/orders/${currentOrder.order_id}/checkout`);currentOrder=d.order;$('checkoutOrder').textContent=currentOrder.order_id;$('payAmount').textContent=currentOrder.expected_amount;$('payAsset').textContent=`${d.payment_method.asset} · ${d.payment_method.network} / ${d.payment_method.standard}`;$('paymentStatus').textContent=currentOrder.status;if(isRealPayments()){$('networkWarning').textContent=d.payment_method.warning;$('payAddress').textContent=d.payment_method.address;$('copyAddress').disabled=false;$('terminalMessage').textContent='Dirección obtenida desde la orden para la red seleccionada.'}else{$('networkWarning').textContent=`${paymentMode} / TEST ONLY — NO ENVÍES CRIPTOMONEDAS REALES.`;$('payAddress').textContent='OCULTA EN MODO DE PRUEBA';$('copyAddress').disabled=true;$('terminalMessage').textContent='Simulación únicamente. Usa un TXID de prueba mock_…'}$('paymentDetails').classList.remove('hidden');$('paymentDetails').scrollIntoView({behavior:'smooth',block:'start'})}
$('copyAddress').addEventListener('click',async()=>{if(!isRealPayments()){toast('Dirección deshabilitada en modo de prueba');return}const value=$('payAddress').textContent;try{await navigator.clipboard.writeText(value);toast('✓ Dirección copiada')}catch{const ta=document.createElement('textarea');ta.value=value;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');toast('✓ Dirección copiada')}catch{toast('No se pudo copiar la dirección')}ta.remove()}})
$('submitTx').addEventListener('click',async()=>{if(!currentOrder)return;const tx=$('txInput').value.trim();if(!tx){toast(isRealPayments()?'Introduce TXID':'Introduce un TXID de prueba mock_…');return}if(!isRealPayments()&&!tx.startsWith('mock_')){toast('En modo de prueba usa un TXID que empiece por mock_');return}try{$('submitTx').disabled=true;$('submitTx').textContent='VERIFICANDO…';const o=await api(`/payments/orders/${currentOrder.order_id}/submit-tx`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transaction_hash:tx})});currentOrder=o;$('paymentStatus').textContent=o.status;$('terminalMessage').textContent=o.status==='FULFILLED'?(isRealPayments()?'✓ Pago verificado por backend y plan activado.':'✓ Simulación TEST completada.'):`Estado: ${o.status}`;if(o.status==='FULFILLED'){toast(isRealPayments()?'Plan activado':'Plan activado en modo de prueba');await loadPurchases()}}catch(e){$('terminalMessage').textContent='⚠ '+e.message;toast(e.message)}finally{$('submitTx').disabled=false;$('submitTx').textContent='VERIFICAR TRANSACCIÓN'}})
async function loadPurchases(){try{const d=await api('/purchases');$('purchaseHistory').innerHTML=d.purchases.length?d.purchases.map(p=>`<div class="purchase-row"><div><b>${esc(p.product_id)}</b><small>${esc(p.network)} · ${esc(p.asset)}</small></div><div><strong>${esc(p.amount)}</strong><span>${isRealPayments()?'CONFIRMED':'TEST'}</span></div></div>`).join(''):'<div class="muted">No hay compras confirmadas todavía.</div>'}catch(e){$('purchaseHistory').innerHTML='<div class="muted">No se pudo cargar el historial.</div>'}}
init();