const API='/api/v1';
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('cfs_csrf='))?.split('=')[1]||''}
let products=[], methods=[], selectedProduct=null, selectedMethod=null, currentQuote=null, currentOrder=null, paymentMode='OFFLINE';
const $=id=>document.getElementById(id);
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
async function api(path,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};if((opt.method||'GET').toUpperCase()!=='GET')opt.headers['X-CSRF-Token']=csrf();const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail?.message||`HTTP ${r.status}`);return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function isRealPayments(){return paymentMode==='PRODUCTION'}
async function init(){
 try{const pm=await api('/payments/methods');paymentMode=String(pm.mode||'OFFLINE').toUpperCase();methods=pm.methods;$('modeBadge').textContent=paymentMode;$('modeBadge').className='mode-badge '+paymentMode.toLowerCase()}catch(e){paymentMode='OFFLINE';$('modeBadge').textContent='OFFLINE'}
 try{const p=await api('/products');products=p.products;renderProducts()}catch(e){$('productCards').innerHTML='<div class="error-card">No se pudo cargar el catálogo.</div>'}
 try{const me=await api('/me');const creator=me.creator;$('accountPlan').textContent=creator?`${me.user.display_name} · ${creator.plan_id.toUpperCase()}`:me.user.display_name;if(creator?.billing_exempt)$('accountPlan').textContent+=' · BILLING EXEMPT';await loadPurchases()}catch(e){$('accountPlan').textContent='Cuenta no conectada'}
}
function renderProducts(){
 $('productCards').innerHTML=products.map((p,i)=>`<article class="product-card ${i===0?'featured':''}"><div class="product-glow"></div><span class="plan-tag">${i===0?'RECOMMENDED':'CREATOR TIER'}</span><h3>${esc(p.label)}</h3><p>${esc(p.description)}</p><div class="product-price"><span>$</span><strong>${esc(p.price_usd)}</strong><small>USD reference</small></div><ul>${p.product_id.includes('plus')?'<li>More games & storage</li><li>Advanced analytics</li><li>Private/staging builds</li>':'<li>Higher platform limits</li><li>Professional creator tools</li><li>Team-ready architecture</li>'}</ul><button class="primary full select-plan" type="button" data-product-id="${esc(p.product_id)}">SELECCIONAR</button></article>`).join('');
 document.querySelectorAll('.select-plan').forEach(button=>button.addEventListener('click',()=>chooseProduct(button.dataset.productId)));
}
function chooseProduct(id){
 selectedProduct=products.find(p=>p.product_id===id);
 if(!selectedProduct){toast('No se pudo seleccionar el plan');return}
 currentQuote=null;currentOrder=null;
 $('terminalEmpty').classList.add('hidden');
 $('terminalFlow').classList.remove('hidden');
 $('checkoutProduct').textContent=selectedProduct.label;
 $('checkoutOrder').textContent='Todavía no creado';
 $('paymentDetails').classList.add('hidden');
 $('terminalMessage').textContent=isRealPayments()?'Selecciona una red de pago.':'MODO DE PRUEBA: no envíes criptomonedas reales. Selecciona una red para simular el flujo.';
 renderMethods();
 document.querySelectorAll('.select-plan').forEach(button=>button.classList.toggle('active',button.dataset.productId===id));
 const terminal=$('terminal');
 if(terminal)terminal.scrollIntoView({behavior:'smooth',block:'start'});
}
function renderMethods(){selectedMethod=methods[0]?.method_id||null;$('methodButtons').innerHTML=methods.map((m,i)=>`<button class="method-choice ${i===0?'active':''}" type="button" data-id="${esc(m.method_id)}"><b>${esc(m.display_name)}</b><small>${isRealPayments()&&m.production_allowed?'PRODUCTION':'TEST ONLY'}</small></button>`).join('');document.querySelectorAll('.method-choice').forEach(b=>b.onclick=()=>{selectedMethod=b.dataset.id;document.querySelectorAll('.method-choice').forEach(x=>x.classList.toggle('active',x===b))})}
$('createOrderBtn').onclick=async()=>{if(!selectedProduct||!selectedMethod)return;try{$('createOrderBtn').disabled=true;$('terminalMessage').textContent=isRealPayments()?'Creando quote y order server-side…':'Creando orden simulada de prueba…';currentQuote=await api('/payments/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:selectedProduct.product_id,method_id:selectedMethod})});const idem='web-'+crypto.randomUUID();currentOrder=await api('/payments/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quote_id:currentQuote.quote_id,idempotency_key:idem})});await showCheckout();}catch(e){$('terminalMessage').textContent='⚠ '+e.message;toast(e.message)}finally{$('createOrderBtn').disabled=false}}
async function showCheckout(){const d=await api(`/payments/orders/${currentOrder.order_id}/checkout`);currentOrder=d.order;$('checkoutOrder').textContent=currentOrder.order_id;$('payAmount').textContent=currentOrder.expected_amount;$('payAsset').textContent=`${d.payment_method.asset} · ${d.payment_method.network} / ${d.payment_method.standard}`;$('paymentStatus').textContent=currentOrder.status;if(isRealPayments()){$('networkWarning').textContent=d.payment_method.warning;$('payAddress').textContent=d.payment_method.address;try{const qr=await fetch(`${API}/payments/orders/${currentOrder.order_id}/qr.svg`,{credentials:'same-origin'});if(qr.ok){const blob=await qr.blob();$('qrImage').src=URL.createObjectURL(blob);$('qrImage').style.display='block'}else{$('qrImage').style.display='none'}}catch{$('qrImage').style.display='none'};$('copyAddress').disabled=false;$('terminalMessage').textContent='Dirección obtenida desde la orden. Nunca desde valores del navegador.'}else{$('networkWarning').textContent=`${paymentMode} / TEST ONLY — NO ENVÍES CRIPTOMONEDAS REALES.`;$('payAddress').textContent='OCULTA EN MODO DE PRUEBA';$('qrImage').style.display='none';$('copyAddress').disabled=true;$('terminalMessage').textContent='Simulación únicamente. Usa un TXID de prueba con prefijo mock_; no envíes fondos reales.'}$('paymentDetails').classList.remove('hidden');$('paymentDetails').scrollIntoView({behavior:'smooth',block:'start'})}
$('copyAddress').onclick=async()=>{if(!isRealPayments()){toast('Dirección deshabilitada en modo de prueba');return}try{await navigator.clipboard.writeText($('payAddress').textContent);toast('Dirección copiada')}catch{toast('No se pudo usar el portapapeles')}}
$('submitTx').onclick=async()=>{if(!currentOrder)return;const tx=$('txInput').value.trim();if(!tx){toast(isRealPayments()?'Introduce TXID':'Introduce un TXID de prueba mock_…');return}if(!isRealPayments()&&!tx.startsWith('mock_')){toast('En modo de prueba usa un TXID que empiece por mock_');return}try{$('submitTx').disabled=true;const o=await api(`/payments/orders/${currentOrder.order_id}/submit-tx`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transaction_hash:tx})});currentOrder=o;$('paymentStatus').textContent=o.status;$('terminalMessage').textContent=o.status==='FULFILLED'?(isRealPayments()?'✓ Pago verificado por backend y entitlement activado.':'✓ Simulación TEST completada; entitlement de prueba activado.'):`Estado: ${o.status}`;if(o.status==='FULFILLED'){toast(isRealPayments()?'Plan activado':'Plan activado en modo de prueba');await loadPurchases()}}catch(e){$('terminalMessage').textContent='⚠ '+e.message;toast(e.message)}finally{$('submitTx').disabled=false}}
async function loadPurchases(){try{const d=await api('/purchases');$('purchaseHistory').innerHTML=d.purchases.length?d.purchases.map(p=>`<div class="purchase-row"><div><b>${esc(p.product_id)}</b><small>${esc(p.network)} · ${esc(p.asset)}</small></div><div><strong>${esc(p.amount)}</strong><span>${isRealPayments()?'CONFIRMED':'TEST'}</span></div></div>`).join(''):'<div class="muted">No hay compras confirmadas todavía.</div>'}catch(e){$('purchaseHistory').innerHTML='<div class="muted">No se pudo cargar el historial.</div>'}}
init();
