const API='/api/v1';let catalog=[],filter='All',me=null,mode='login',currentProduct=null,currentOrder=null,paymentMode='MOCK';
const $=id=>document.getElementById(id);const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)};
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('cfs_csrf='))?.split('=')[1]||''}
async function api(path,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};if((opt.method||'GET').toUpperCase()!=='GET')opt.headers['X-CSRF-Token']=csrf();const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail?.message||'Request failed');return d}
async function refreshMe(){try{me=(await api('/me')).user;$('accountBtn').textContent=me.display_name}catch{me=null;$('accountBtn').textContent='Sign in'}}
function categories(){return ['All',...new Set(catalog.map(x=>x.category))]}
function renderFilters(){$('filters').innerHTML=categories().map(x=>`<button class="chip ${x===filter?'active':''}" data-cat="${x}">${x}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{filter=b.dataset.cat;renderFilters();renderProducts()})}
function renderProducts(){const rows=catalog.filter(x=>filter==='All'||x.category===filter);$('productGrid').innerHTML=rows.map(p=>`<article class="product"><span class="cat">${p.category}</span><h3>${p.name}</h3><p>${p.summary}</p><div class="price">${p.free?'FREE':'$'+p.price} <small>${p.free?'instant download':'USDC'}</small></div>${p.free?`<a class="primary full" href="${API}/bitshelf/free/${p.product_id}">Download</a>`:`<button class="primary full buy" data-id="${p.product_id}">Buy with USDC</button>`}</article>`).join('');document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>buy(b.dataset.id))}
function openAuth(){mode='login';$('authTitle').textContent='Sign in';$('displayName').style.display='none';$('authSwitch').textContent='Create an account instead';$('authModal').classList.remove('hidden')}
$('accountBtn').onclick=()=>{if(me){toast('Signed in as '+me.display_name)}else openAuth()};$('authClose').onclick=()=>$('authModal').classList.add('hidden');$('checkoutClose').onclick=()=>$('checkoutModal').classList.add('hidden');
$('authSwitch').onclick=()=>{mode=mode==='login'?'register':'login';$('authTitle').textContent=mode==='login'?'Sign in':'Create account';$('displayName').style.display=mode==='login'?'none':'block';$('authSwitch').textContent=mode==='login'?'Create an account instead':'I already have an account'};
$('authForm').onsubmit=async e=>{e.preventDefault();const body={email:$('email').value,password:$('password').value};if(mode==='register')body.display_name=$('displayName').value;try{const r=await fetch(`${API}/auth/${mode}`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.detail?.message||'Authentication failed');$('authModal').classList.add('hidden');await refreshMe();toast('Account ready')}catch(e){$('authResult').textContent=e.message}};
async function buy(id){currentProduct=catalog.find(x=>x.product_id===id);if(!me){openAuth();toast('Sign in first');return}try{$('checkoutModal').classList.remove('hidden');$('checkoutName').textContent=currentProduct.name;$('checkoutStatus').textContent='Creating secure order…';$('payPanel').classList.add('hidden');$('downloadPanel').classList.add('hidden');const pm=await api('/payments/methods');paymentMode=String(pm.mode||'MOCK').toUpperCase();const method=(pm.methods||[]).find(x=>x.method_id==='usdc_base');if(!method)throw new Error('USDC on Base is not available yet');const quote=await api('/payments/quotes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:id,method_id:'usdc_base'})});currentOrder=await api('/payments/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({quote_id:quote.quote_id,idempotency_key:'bitshelf-'+crypto.randomUUID()})});const checkout=await api(`/payments/orders/${currentOrder.order_id}/checkout`);currentOrder=checkout.order;$('payAmount').textContent=currentOrder.expected_amount+' USDC';if(paymentMode==='PRODUCTION'){$('payAddress').textContent=checkout.payment_method.address;$('checkoutStatus').textContent='Send the exact amount using USDC on Base only.'}else{$('payAddress').textContent='Hidden in test mode';$('checkoutStatus').textContent=paymentMode+' mode — do not send real funds. Use a mock_ transaction hash.'}$('payPanel').classList.remove('hidden')}catch(e){$('checkoutStatus').textContent='⚠ '+e.message}}
$('copyAddress').onclick=async()=>{if(paymentMode!=='PRODUCTION'){toast('Address hidden in test mode');return}await navigator.clipboard.writeText($('payAddress').textContent);toast('Address copied')};
$('verifyBtn').onclick=async()=>{const tx=$('txHash').value.trim();if(!tx||!currentOrder)return;try{$('verifyBtn').disabled=true;$('checkoutStatus').textContent='Verifying on-chain…';currentOrder=await api(`/payments/orders/${currentOrder.order_id}/submit-tx`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transaction_hash:tx})});$('checkoutStatus').textContent='Order status: '+currentOrder.status;if(currentOrder.status==='FULFILLED'){$('payPanel').classList.add('hidden');$('downloadPanel').classList.remove('hidden');toast('Payment confirmed')}}catch(e){$('checkoutStatus').textContent='⚠ '+e.message}finally{$('verifyBtn').disabled=false}};
$('downloadBtn').onclick=async()=>{try{const d=await api(`/bitshelf/download-ticket/${currentProduct.product_id}`,{method:'POST'});location.href=d.download_url}catch(e){toast(e.message)}};
(async()=>{try{catalog=(await api('/bitshelf/catalog')).products;renderFilters();renderProducts()}catch(e){$('productGrid').innerHTML='<div class="loading">Store is temporarily unavailable.</div>'}await refreshMe()})();