const API='/api/v1';
const gamesById=new Map();
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('cfs_csrf='))?.split('=')[1]||''}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
async function api(path,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};if((opt.method||'GET').toUpperCase()!=='GET')opt.headers['X-CSRF-Token']=csrf();const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail?.message||`HTTP ${r.status}`);return d}
async function init(){try{const me=await api('/me');document.getElementById('welcome').textContent='Hola, '+me.user.display_name;if(!me.creator){document.getElementById('creatorState').textContent='Tu cuenta todavía es Player.';document.getElementById('activate').classList.remove('hidden')}else{document.getElementById('createPanel').classList.remove('hidden');await loadOverview();await loadGames()}}catch(e){document.getElementById('creatorState').innerHTML='Necesitas iniciar sesión desde el <a href="/">portal</a>.'}}
async function activateCreator(){try{await api('/creator/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({creator_slug:creatorSlug.value,bio:creatorBio.value})});location.reload()}catch(e){toast(e.message)}}
async function createGame(){try{await api('/creator/games',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:gameTitle.value,genre:gameGenre.value,description:gameDescription.value})});gameTitle.value='';gameDescription.value='';toast('Draft creado');await Promise.all([loadGames(),loadOverview()])}catch(e){toast(e.message)}}
function publicUrl(g){return `${location.origin}/play/${encodeURIComponent(g.slug)}/`}
async function copyGame(id){const g=gamesById.get(id);if(!g)return;try{await navigator.clipboard.writeText(publicUrl(g));toast('Enlace copiado ✓')}catch{toast(publicUrl(g))}}
async function shareGame(id){const g=gamesById.get(id);if(!g)return;const url=publicUrl(g);if(navigator.share){try{await navigator.share({title:g.title,text:`Juega ${g.title} en Crypto Factory Studios`,url});return}catch(e){if(e.name==='AbortError')return}}await copyGame(id)}
async function loadGames(){try{const d=await api('/creator/games');const root=document.getElementById('gamesList');root.innerHTML='';gamesById.clear();if(!d.games.length){root.innerHTML='<p class="muted">Todavía no has creado juegos.</p>';return}for(const g of d.games){gamesById.set(g.game_id,g);const published=g.status==='PUBLISHED';const row=document.createElement('div');row.className='game-row';row.innerHTML=`<div><b>${esc(g.title)}</b><br><small>${esc(g.status)} · /${esc(g.slug)} · ${esc(g.visibility)}</small><div id="builds-${esc(g.game_id)}"></div></div><div class="game-actions">${published?`<a class="primary small" href="/play/${encodeURIComponent(g.slug)}/" target="_blank" rel="noopener">PLAY GAME</a><button class="ghost small" data-action="copy" data-id="${esc(g.game_id)}">COPY LINK</button><button class="ghost small" data-action="share" data-id="${esc(g.game_id)}">SHARE</button>`:''}<button class="ghost small" data-action="edit" data-id="${esc(g.game_id)}">Editar</button>${published?`<button class="ghost small" data-action="unpublish" data-id="${esc(g.game_id)}">Despublicar</button>`:''}<label class="ghost small">1 — SELECT ZIP<input hidden type="file" accept=".zip,application/zip" data-upload="${esc(g.game_id)}"></label><button class="danger small" data-action="delete" data-id="${esc(g.game_id)}">Eliminar</button></div>`;root.appendChild(row);loadBuilds(g.game_id)}root.querySelectorAll('[data-action="edit"]').forEach(b=>b.addEventListener('click',()=>editGame(b.dataset.id)));root.querySelectorAll('[data-action="copy"]').forEach(b=>b.addEventListener('click',()=>copyGame(b.dataset.id)));root.querySelectorAll('[data-action="share"]').forEach(b=>b.addEventListener('click',()=>shareGame(b.dataset.id)));root.querySelectorAll('[data-action="unpublish"]').forEach(b=>b.addEventListener('click',()=>unpublishGame(b.dataset.id)));root.querySelectorAll('[data-action="delete"]').forEach(b=>b.addEventListener('click',()=>deleteGame(b.dataset.id)));root.querySelectorAll('[data-upload]').forEach(i=>i.addEventListener('change',()=>upload(i.dataset.upload,i)))}catch(e){toast(e.message)}}
async function editGame(id){const g=gamesById.get(id);if(!g)return;const title=prompt('Nombre del juego',g.title);if(title===null)return;const description=prompt('Descripción',g.description||'');if(description===null)return;const genre=prompt('Género',g.genre||'Other');if(genre===null)return;const visibility=(prompt('Visibilidad: PUBLIC, PRIVATE o UNLISTED',g.visibility||'PUBLIC')||'').toUpperCase();if(!['PUBLIC','PRIVATE','UNLISTED'].includes(visibility)){toast('Visibilidad inválida');return}try{await api(`/creator/games/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description,genre,visibility})});toast('Juego actualizado');await loadGames()}catch(e){toast(e.message)}}
async function upload(gameId,input){if(!input.files[0])return;const version=prompt('Versión del build','0.1.0');if(version===null){input.value='';return}const fd=new FormData();fd.append('version',version||'0.1.0');fd.append('archive',input.files[0]);toast('2 — CFS valida y prepara el build…');try{const d=await api(`/creator/games/${gameId}/builds`,{method:'POST',body:fd});if(d.scan_status==='CLEAN')toast('Build validated ✓ · Files prepared ✓ · Ready to publish ✓');else toast(`Scan: ${d.scan_status}`);await Promise.all([loadBuilds(gameId),loadOverview()])}catch(e){toast(e.message)}finally{input.value=''}}
async function loadBuilds(gameId){try{const d=await api(`/creator/games/${gameId}/builds`);const root=document.getElementById('builds-'+gameId);if(!root)return;root.innerHTML=d.builds.map(b=>`<div class="build"><span class="${b.scan_status==='CLEAN'?'ok':'warn'}">${b.scan_status==='CLEAN'?'Build validated ✓':esc(b.scan_status)}</span> · ${esc(b.version)} · ${esc(b.status)} ${b.scan_status==='CLEAN'&&b.status==='READY_FOR_REVIEW'?`<button class="primary small" data-publish="${esc(b.build_id)}">3 — PUBLISH</button>`:''}</div>`).join('');root.querySelectorAll('[data-publish]').forEach(b=>b.addEventListener('click',()=>publishBuild(b.dataset.publish)))}catch(e){}}
async function publishBuild(id){try{await api(`/creator/builds/${id}/publish`,{method:'POST'});toast('Publicado ✓ · PLAY, COPY LINK y SHARE listos');await Promise.all([loadGames(),loadOverview()])}catch(e){toast(e.message)}}
async function unpublishGame(id){if(!confirm('¿Despublicar este juego? Dejará de aparecer en el catálogo.'))return;try{await api(`/creator/games/${id}/unpublish`,{method:'POST'});toast('Juego despublicado');await Promise.all([loadGames(),loadOverview()])}catch(e){toast(e.message)}}
async function deleteGame(id){const g=gamesById.get(id);if(!confirm(`¿Eliminar definitivamente ${g?.title||'este juego'} y sus builds?`))return;try{await api(`/creator/games/${id}`,{method:'DELETE'});toast('Juego eliminado');await Promise.all([loadGames(),loadOverview()])}catch(e){toast(e.message)}}
async function loadOverview(){try{const o=await api('/creator/overview');const state=document.getElementById('creatorState');const pct=o.limits.max_storage_bytes?Math.min(100,Math.round(o.storage_bytes/o.limits.max_storage_bytes*100)):0;const upgrade=o.plan_id==='free'?'<a class="primary small" href="/billing.html">Ver Creator Pro</a>':'';state.innerHTML=`<div class="creator-overview"><div><span>PLAN</span><b>${esc(o.plan_id.toUpperCase())}</b></div><div><span>GAMES</span><b>${o.games}${o.limits.max_games==null?' / ∞':' / '+o.limits.max_games}</b></div><div><span>PUBLISHED</span><b>${o.published_games}</b></div><div><span>BUILDS CLEAN</span><b>${o.clean_builds}/${o.builds}</b></div></div><div class="usagebar"><i style="width:${pct}%"></i></div><small>${(o.storage_bytes/1048576).toFixed(1)} MB de almacenamiento usado</small> ${upgrade}`}catch(e){}}
document.getElementById('activateCreatorBtn')?.addEventListener('click',activateCreator);document.getElementById('createGameBtn')?.addEventListener('click',createGame);init();