const API='/api/v1';
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('cfs_csrf='))?.split('=')[1]||''}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
async function api(path,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};if((opt.method||'GET').toUpperCase()!=='GET')opt.headers['X-CSRF-Token']=csrf();const r=await fetch(API+path,opt);const d=await r.json();if(!r.ok)throw new Error(d.detail?.message||'Error');return d}
async function init(){try{const me=await api('/me');document.getElementById('welcome').textContent='Hola, '+me.user.display_name;if(!me.creator){document.getElementById('creatorState').textContent='Tu cuenta todavía es Player.';document.getElementById('activate').classList.remove('hidden')}else{document.getElementById('creatorState').innerHTML=`Plan <b>${me.creator.plan_id.toUpperCase()}</b> · Trust ${me.creator.trust_level} · Billing exempt ${me.creator.billing_exempt?'YES':'NO'}`;document.getElementById('createPanel').classList.remove('hidden');await loadOverview();await loadGames()}}catch(e){document.getElementById('creatorState').innerHTML='Necesitas iniciar sesión desde el <a href="/">portal</a>.'}}
async function activateCreator(){try{await api('/creator/activate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({creator_slug:creatorSlug.value,bio:creatorBio.value})});location.reload()}catch(e){toast(e.message)}}
async function createGame(){try{await api('/creator/games',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:gameTitle.value,genre:gameGenre.value,description:gameDescription.value})});toast('Draft creado');await loadGames()}catch(e){toast(e.message)}}
async function loadGames(){try{const d=await api('/creator/games');const root=document.getElementById('gamesList');root.innerHTML='';for(const g of d.games){const row=document.createElement('div');row.className='game-row';row.innerHTML=`<div><b>${g.title}</b><br><small>${g.status} · /${g.slug}</small><div id="builds-${g.game_id}"></div></div><div><label class="ghost small">Subir ZIP<input hidden type="file" accept=".zip" onchange="upload('${g.game_id}',this)"></label></div>`;root.appendChild(row);loadBuilds(g.game_id)}}catch(e){toast(e.message)}}
async function upload(gameId,input){if(!input.files[0])return;const fd=new FormData();fd.append('version','0.1.0');fd.append('archive',input.files[0]);try{const d=await api(`/creator/games/${gameId}/builds`,{method:'POST',body:fd});toast(`Scan: ${d.scan_status}`);await loadBuilds(gameId)}catch(e){toast(e.message)}}
async function loadBuilds(gameId){try{const d=await api(`/creator/games/${gameId}/builds`);const root=document.getElementById('builds-'+gameId);root.innerHTML=d.builds.map(b=>`<div class="build"><span class="${b.scan_status==='CLEAN'?'ok':'warn'}">${b.scan_status}</span> · ${b.version} · ${b.status} ${b.scan_status==='CLEAN'&&b.status==='READY_FOR_REVIEW'?`<button class="primary small" onclick="publishBuild('${b.build_id}')">Publish</button>`:''}</div>`).join('')}catch(e){}}
async function publishBuild(id){try{await api(`/creator/builds/${id}/publish`,{method:'POST'});toast('Publicado');await loadGames()}catch(e){toast(e.message)}}
init();

async function loadOverview(){try{const o=await api('/creator/overview');const state=document.getElementById('creatorState');const pct=o.limits.max_storage_bytes?Math.min(100,Math.round(o.storage_bytes/o.limits.max_storage_bytes*100)):0;state.innerHTML=`<div class="creator-overview"><div><span>PLAN</span><b>${o.plan_id.toUpperCase()}</b></div><div><span>GAMES</span><b>${o.games}${o.limits.max_games==null?' / ∞':' / '+o.limits.max_games}</b></div><div><span>PUBLISHED</span><b>${o.published_games}</b></div><div><span>BUILDS CLEAN</span><b>${o.clean_builds}/${o.builds}</b></div></div><div class="usagebar"><i style="width:${pct}%"></i></div><small>${(o.storage_bytes/1048576).toFixed(1)} MB de almacenamiento usado</small>`}catch(e){}}
