import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const EARN_EDGE=`${SUPABASE_URL}/functions/v1/earn-engine`;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let earnState=null,opened=false,loading=false,lastLoaded=0,timer=null,scheduled=false;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>localStorage.getItem('nexus-lang')||'es';
const L={
 es:{title:'Recompensas Earn',demo:'DEMO · sin dinero real',open:'Abrir recompensas',points:'Puntos de contribución',projection:'Proyección semanal',pool:'Pool semanal',credits:'Créditos Earn DEMO',board:'Tablón semanal',eligibility:'Requisitos Earn',history:'Actividad reciente',past:'Semanas anteriores',claim:'Reclamar',claimed:'Reclamado',ready:'Listo',progress:'En progreso',level:'Nivel 3+',age:'Cuenta con 24 h+',minPoints:'40+ puntos',categories:'3+ tipos de actividad',review:'Sin revisión pendiente',closes:'Cierra en',share:'Participación estimada',players:'Puntos globales',rules:'Protección de economía',noValue:'Estos créditos no tienen valor monetario, no son transferibles y no se pueden retirar.',dynamic:'La proyección cambia cuando participan más jugadores.',empty:'Todavía no hay actividad Earn.',weekClaim:'Reclamar pool cerrado',meaningful:'Los combates demasiado fáciles dejan de dar puntos base. El mercado no da puntos Earn para reducir compra/venta artificial.',dailyCaps:'Hay límites diarios por categoría y los bonos del tablón se obtienen por variedad de actividad.'},
 en:{title:'Earn Rewards',demo:'DEMO · no real money',open:'Open rewards',points:'Contribution Points',projection:'Weekly projection',pool:'Weekly pool',credits:'Earn DEMO Credits',board:'Weekly Board',eligibility:'Earn Requirements',history:'Recent activity',past:'Previous weeks',claim:'Claim',claimed:'Claimed',ready:'Ready',progress:'In progress',level:'Level 3+',age:'Account 24h+',minPoints:'40+ points',categories:'3+ activity types',review:'No pending review',closes:'Closes in',share:'Estimated share',players:'Global points',rules:'Economy protection',noValue:'These credits have no monetary value, are non-transferable, and cannot be withdrawn.',dynamic:'Projection changes as more players participate.',empty:'No Earn activity yet.',weekClaim:'Claim closed pool',meaningful:'Battles that are too easy stop awarding base points. Market trading gives no Earn points to reduce wash trading.',dailyCaps:'Each activity category has daily caps; board bonuses reward varied play.'}
};
const t=k=>L[lang()]?.[k]??L.es[k]??k;
const fmt=n=>Number(n||0).toLocaleString();
const pct=(a,b)=>Math.max(0,Math.min(100,b?Number(a)/Number(b)*100:0));
function fmtTime(ms){if(!Number.isFinite(ms)||ms<=0)return '00:00';let s=Math.ceil(ms/1000),d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);return d?`${d}d ${h}h`:h?`${h}h ${m}m`:`${m}m`;}
async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||null;}
async function call(body){const tk=await token();if(!tk)throw new Error(lang()==='es'?'Inicia sesión primero':'Sign in first');const r=await fetch(EARN_EDGE,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${tk}`,'apikey':SUPABASE_KEY},body:JSON.stringify(body),cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok||j.error)throw new Error(j.error||'Earn request failed');return j;}
async function load(force=false){if(loading)return earnState;if(!force&&earnState&&Date.now()-lastLoaded<12000)return earnState;loading=true;renderLauncher();try{earnState=await call({op:'state'});lastLoaded=Date.now();renderLauncher();if(opened)renderOverlay();return earnState;}catch(e){if(opened)toast(e.message)}finally{loading=false;renderLauncher();}}
async function act(action,payload={}){if(loading)return;loading=true;renderOverlay();try{earnState=await call({op:'action',action,payload});lastLoaded=Date.now();toast(earnState.message||'✓');renderLauncher();renderOverlay();}catch(e){toast(human(e.message))}finally{loading=false;renderOverlay();}}
function human(m=''){if(lang()==='en')return String(m);return String(m).replace('Earn task already claimed','Esta tarea ya fue reclamada').replace('Earn task incomplete','La tarea Earn aún no está completa').replace('Weekly pool is still active','El pool semanal todavía está activo').replace('No weekly score','No tienes puntuación esa semana').replace('Weekly earn reward already claimed','La recompensa semanal ya fue reclamada').replace('Level 3 required','Se requiere nivel 3').replace('Account must be at least 24 hours old before week close','La cuenta debe tener al menos 24 horas antes del cierre semanal').replace('Need at least 40 contribution points','Necesitas al menos 40 puntos de contribución').replace('Need activity in at least 3 categories','Necesitas actividad en al menos 3 categorías').replace('Score pending review','La puntuación está pendiente de revisión');}
function toast(m){let el=$('#earn-toast');if(!el){el=document.createElement('div');el.id='earn-toast';document.body.append(el);}el.textContent=human(m);el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}
function isMore(){const h=document.querySelector('#panel .section-head h2');return Boolean(h&&(/Más|More/i.test(h.textContent||'')));}
function renderLauncher(){if(!isMore())return;let el=$('#earn-launcher');if(!el){el=document.createElement('section');el.id='earn-launcher';el.className='earn-launcher';const clan=$('#clan-launcher');const menu=document.querySelector('#panel .segmented');if(clan)clan.insertAdjacentElement('afterend',el);else menu?.insertAdjacentElement('afterend',el);}if(!el)return;const w=earnState?.week;el.innerHTML=`<button class="earn-launch-button" data-open-earn ${loading?'disabled':''}><span class="earn-icon">💰</span><span><b>${t('title')}</b><small>${w?`${fmt(w.points)} ${t('points').toLowerCase()} · ${fmt(w.projectedDemoCredits)} ${t('credits')}`:t('demo')}</small></span><strong>›</strong></button>`;el.querySelector('[data-open-earn]')?.addEventListener('click',openOverlay);}
function ruleRow(label,r,extra=''){return `<div class="earn-rule ${r?.ok?'ok':'wait'}"><span>${r?.ok?'✓':'○'}</span><div><b>${label}</b>${extra?`<small>${extra}</small>`:''}</div></div>`;}
function taskHtml(x){const ready=x.ready&&!x.claimed;return `<div class="earn-task ${x.claimed?'claimed':ready?'ready':''}"><div class="earn-task-head"><div><b>${esc(lang()==='es'?x.nameEs:x.name)}</b><small>+${x.bonusPoints} ${t('points')}</small></div><span>${Math.min(x.progress,x.target)}/${x.target}</span></div><div class="earn-progress"><i style="width:${pct(x.progress,x.target)}%"></i></div><button data-earn-task="${esc(x.key)}" ${!ready||loading?'disabled':''}>${x.claimed?t('claimed'):ready?t('claim'):t('progress')}</button></div>`;}
function recentHtml(){const rows=earnState?.recent||[];return rows.length?`<div class="earn-recent">${rows.map(r=>`<div><span>${esc(r.categoryName||r.category)}</span><b>+${r.points}</b><small>${new Date(r.createdAt).toLocaleString()}</small></div>`).join('')}</div>`:`<div class="earn-muted">${t('empty')}</div>`;}
function pastHtml(){const rows=earnState?.past||[];if(!rows.length)return `<div class="earn-muted">${t('empty')}</div>`;return `<div class="earn-past">${rows.map(x=>`<div><span><b>${esc(x.weekStart)}</b><small>${fmt(x.points)} ${t('points').toLowerCase()} · ${x.categories} cat.</small></span>${x.claimed?`<strong>+${fmt(x.demoCredits)} DEMO</strong>`:`<button data-earn-week="${esc(x.weekStart)}" ${!x.claimable||loading?'disabled':''}>${t('weekClaim')}</button>`}</div>`).join('')}</div>`;}
function overlayHtml(){if(!earnState)return `<div class="earn-loading">...</div>`;const w=earnState.week,r=w.rules,closeMs=new Date(w.closesAt).getTime()-Date.now(),share=w.totalServerPoints?100*w.points/w.totalServerPoints:0;return `<section class="earn-hero"><div><span class="eyebrow">${t('demo')}</span><h2>💰 ${t('title')}</h2><p>${t('noValue')}</p></div><div class="earn-credit-box"><small>${t('credits')}</small><strong>${fmt(earnState.character.earnCreditsDemo)}</strong></div></section><section class="earn-summary"><div><small>${t('points')}</small><strong>${fmt(w.points)}</strong></div><div><small>${t('projection')}</small><strong>${fmt(w.projectedDemoCredits)}</strong></div><div><small>${t('pool')}</small><strong>${fmt(w.poolDemoCredits)}</strong></div><div><small>${t('share')}</small><strong>${share.toFixed(2)}%</strong></div></section><div class="earn-close">⏳ ${t('closes')} <b data-earn-close>${fmtTime(closeMs)}</b> · ${t('players')}: ${fmt(w.totalServerPoints)}</div><p class="earn-muted">${t('dynamic')}</p><section class="earn-block"><h3>🛡️ ${t('eligibility')}</h3><div class="earn-rules">${ruleRow(t('level'),r.level,`${r.level.current}/${r.level.required}`)}${ruleRow(t('age'),r.accountAge,`${r.accountAge.currentHours}h/${r.accountAge.requiredHours}h`)}${ruleRow(t('minPoints'),r.points,`${fmt(r.points.current)}/${fmt(r.points.required)}`)}${ruleRow(t('categories'),r.categories,`${r.categories.current}/${r.categories.required}`)}${ruleRow(t('review'),r.review,r.review.reason||'')}</div></section><section class="earn-block"><h3>📋 ${t('board')}</h3><div class="earn-task-list">${earnState.tasks.map(taskHtml).join('')}</div></section><section class="earn-block"><h3>🔐 ${t('rules')}</h3><p>${t('meaningful')}</p><p>${t('dailyCaps')}</p></section><section class="earn-block"><h3>📈 ${t('history')}</h3>${recentHtml()}</section><section class="earn-block"><h3>🗓️ ${t('past')}</h3>${pastHtml()}</section>`;}
function renderOverlay(){let ov=$('#earn-overlay');if(!opened){ov?.remove();return;}if(!ov){ov=document.createElement('div');ov.id='earn-overlay';ov.className='earn-overlay';document.body.append(ov);}ov.innerHTML=`<div class="earn-sheet"><div class="earn-sheet-bar"><b>💰 ${t('title')}</b><button data-close-earn>✕</button></div><div class="earn-sheet-body">${overlayHtml()}</div></div>`;bindOverlay();updateClose();}
function bindOverlay(){const ov=$('#earn-overlay');if(!ov)return;ov.querySelector('[data-close-earn]')?.addEventListener('click',closeOverlay);ov.addEventListener('click',e=>{if(e.target===ov)closeOverlay()});ov.querySelectorAll('[data-earn-task]').forEach(b=>b.addEventListener('click',()=>act('claimTask',{taskKey:b.dataset.earnTask})));ov.querySelectorAll('[data-earn-week]').forEach(b=>b.addEventListener('click',()=>act('claimWeek',{weekStart:b.dataset.earnWeek})));}
function openOverlay(){opened=true;document.body.classList.add('earn-open');renderOverlay();load(true);if(timer)clearInterval(timer);timer=setInterval(()=>{if(opened)load(true)},30000);}
function closeOverlay(){opened=false;document.body.classList.remove('earn-open');if(timer){clearInterval(timer);timer=null;}renderOverlay();}
function updateClose(){const el=document.querySelector('[data-earn-close]');if(el&&earnState)el.textContent=fmtTime(new Date(earnState.week.closesAt).getTime()-Date.now());}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;renderLauncher();if(isMore()&&!earnState)load(false);});}
new MutationObserver(schedule).observe(document.querySelector('#app')||document.body,{childList:true,subtree:true});
window.addEventListener('nexus:state',()=>{schedule();if(opened)load(true)});
window.addEventListener('focus',()=>{if(opened)load(true)});
setInterval(updateClose,1000);
setTimeout(schedule,900);
