import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
import {plainText,petEvolutionRequirement,eventState,RANKING_KEYS} from './phase5-core.js';

const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const EDGE=`${SUPABASE_URL}/functions/v1/phase5-engine`;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=n=>Number(n||0).toLocaleString();const lang=()=>localStorage.getItem('nexus-lang')||'es';const txt=(es,en)=>lang()==='en'?en:es;const date=v=>v?new Date(v).toLocaleString():'';
let state=null,opened=false,tab='pets',socialTab='friends',rankKey='level',chatChannel='global',loading=false,refreshTimer=null,searchResults=[],inspectProfile=null;

async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||null}
async function call(body){const tk=await token();if(!tk)throw new Error(txt('Inicia sesión primero','Sign in first'));const r=await fetch(EDGE,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${tk}`,'apikey':SUPABASE_KEY},body:JSON.stringify(body),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||'Phase 5 request failed');return j}
async function load(force=false){if(loading)return state;if(state&&!force)return state;loading=true;render();try{state=await call({op:'state'});renderPlayerTitle();renderLauncher();render();return state}catch(e){toast(e.message);throw e}finally{loading=false;render()}}
async function act(action,payload={}){if(loading)return;loading=true;render();try{state=await call({op:'action',action,payload:{...payload,requestId:payload.requestId||crypto.randomUUID()}});renderPlayerTitle();toast(state.message||'✓');renderLauncher();render()}catch(e){toast(e.message)}finally{loading=false;render()}}
function toast(m){let el=$('#phase5-toast');if(!el){el=document.createElement('div');el.id='phase5-toast';el.className='p5-toast';document.body.append(el)}el.textContent=String(m||'');el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function isMore(){return /Más|More/i.test($('#panel .section-head h2')?.textContent||'')}
function renderLauncher(){if(!isMore())return;let host=$('#phase5-launcher');if(!host){host=document.createElement('section');host.id='phase5-launcher';host.className='phase5-launcher';const anchor=$('#phase4-launcher')||$('#clan-launcher')||$('#panel .segmented');anchor?.insertAdjacentElement('afterend',host)}if(!host)return;const unread=state?.notifications?.unread||0,petCount=state?.pets?.owned?.length||0;host.innerHTML=`<button class="phase5-launch-button" data-open-phase5><span>🌐</span><span><b>${txt('Mundo Vivo','Living World')}${unread?` · 🔔 ${unread}`:''}</b><small>${txt('Mascotas · Social · Rankings · Eventos','Pets · Social · Rankings · Events')}${petCount?` · 🐾 ${petCount}`:''}</small></span><strong>›</strong></button>`;host.querySelector('[data-open-phase5]')?.addEventListener('click',openOverlay)}
function renderPlayerTitle(){const h=$('.player-main h2');if(!h)return;let badge=$('#phase5-title-badge');const selected=state?.achievements?.titles?.find(x=>x.selected);if(!selected){badge?.remove();return}if(!badge){badge=document.createElement('div');badge.id='phase5-title-badge';badge.className='p5-title-badge';h.insertAdjacentElement('afterend',badge)}badge.textContent=`✦ ${lang()==='en'?selected.name_en:selected.name_es}`}
function openOverlay(){opened=true;render();load(true).catch(()=>{});startRefresh()}
function closeOverlay(){opened=false;$('#phase5-overlay')?.remove();stopRefresh()}
function startRefresh(){stopRefresh();refreshTimer=setInterval(()=>{if(opened&&!loading)load(true).catch(()=>{})},15000)}function stopRefresh(){if(refreshTimer){clearInterval(refreshTimer);refreshTimer=null}}

const passive=d=>({gathering:txt('+2% recolección','+2% gathering'),xp:txt('+2% XP','+2% XP'),boss_damage:txt('+2% daño a boss','+2% boss damage'),crafting:txt('+2% crafting','+2% crafting'),collection:txt('+1% colección','+1% collection')})[d?.passive_key]||d?.passive_key;
function petsHtml(){const p=state?.pets;if(!p)return'<div class="p5-card">…</div>';const owned=new Map((p.owned||[]).map(x=>[x.pet_key,x]));return `<section class="p5-hero"><span class="p5-eyebrow">NEXUS REALMS · FASE 5</span><h2>🐾 ${txt('Mascotas','Pets')}</h2><p>${txt('Coleccionables con bonos pequeños. Nunca son obligatorias para competir.','Collectibles with small bonuses. They are never mandatory to compete.')}</p><div class="p5-chips"><span>${p.owned.length}/${p.definitions.length} ${txt('obtenidas','owned')}</span><span>Common → Mythic</span></div></section><div class="p5-grid">${p.definitions.map(d=>{const o=owned.get(d.pet_key);if(!o)return`<article class="p5-card p5-pet locked"><div class="p5-pet-icon">${esc(d.appearance)}</div><span class="p5-rarity ${d.rarity}">${esc(d.rarity)}</span><h3>${esc(lang()==='en'?d.name_en:d.name_es)}</h3><b>${esc(passive(d))}</b><small>🔒 ${esc(d.origin)}</small></article>`;const req=petEvolutionRequirement(d,o.evolution_stage),canEvolve=o.level>=req.level&&o.evolution_stage<3;return`<article class="p5-card p5-pet ${o.equipped?'equipped':''}"><div class="p5-pet-icon">${esc(d.appearance)}</div><span class="p5-rarity ${d.rarity}">${esc(d.rarity)}</span><h3>${esc(lang()==='en'?d.name_en:d.name_es)} ${o.equipped?'✓':''}</h3><b>${txt('Nivel','Level')} ${o.level} · Evo ${o.evolution_stage}</b><small>${fmt(o.xp)} XP · ${esc(passive(d))}</small><small>${txt('Origen','Origin')}: ${esc(o.acquired_from)}</small><div class="p5-actions"><button data-p5-equip="${o.id}" ${o.equipped||loading?'disabled':''}>${o.equipped?txt('Equipada','Equipped'):txt('Equipar','Equip')}</button><button data-p5-evolve="${o.id}" ${!canEvolve||loading?'disabled':''}>${txt('Evolucionar','Evolve')}</button></div>${o.evolution_stage<3?`<small>${txt('Evolución','Evolution')}: Lv.${req.level} · ${req.amount} ${esc(req.resource)} · Núcleo</small>`:'<small>EVOLUTION MAX</small>'}</article>`}).join('')}</div>`}

function personRow(p,actions=''){return`<div class="p5-row"><div class="p5-row-main"><b><i class="${p?.online?'p5-online':'p5-online p5-offline'}"></i>${esc(p?.name||'Jugador')}</b><small>${p?.title?`✦ ${esc(lang()==='en'?p.title.name_en:p.title.name_es)} · `:''}${txt('Nivel','Level')} ${p?.level||1}${p?.guild?` · [${esc(p.guild.tag||'')}]`:''}</small></div><div class="p5-actions">${actions}</div></div>`}
function friendsHtml(){const s=state?.social;if(!s)return'<div class="p5-card">…</div>';return `<form id="p5-player-search" class="p5-form"><input name="query" maxlength="24" placeholder="${txt('Buscar jugador','Search player')}"><button>${txt('Buscar','Search')}</button></form>${searchResults.length?`<section class="p5-block"><h3>🔎 ${txt('Resultados','Results')}</h3><div class="p5-list">${searchResults.map(p=>personRow(p,`<button data-p5-inspect="${p.id}">${txt('Ver','View')}</button><button data-p5-friend-add="${p.id}">＋</button>`)).join('')}</div></section>`:''}${inspectProfile?inspectHtml(inspectProfile):''}<section class="p5-block"><h3>📨 ${txt('Solicitudes','Requests')} · ${s.incoming.length}</h3><div class="p5-list">${s.incoming.map(r=>personRow(r.profile,`<button data-p5-friend-response="${r.id}" data-accept="1">✓</button><button data-p5-friend-response="${r.id}" data-accept="0">✕</button>`)).join('')||`<small>${txt('Sin solicitudes pendientes','No pending requests')}</small>`}</div></section><section class="p5-block"><h3>👥 ${txt('Amigos','Friends')} · ${s.friends.length}</h3><div class="p5-list">${s.friends.map(p=>personRow(p,`<button data-p5-inspect="${p.id}">${txt('Inspeccionar','Inspect')}</button><button data-p5-friend-remove="${p.id}">−</button>`)).join('')||`<small>${txt('Busca jugadores para agregarlos.','Search for players to add them.')}</small>`}</div></section>`}
function inspectHtml(p){return`<section class="p5-block p5-inspect"><h3>🔍 ${esc(p.name)}</h3><div class="p5-chips"><span>${txt('Nivel','Level')} ${p.level}</span><span>${txt('Renombre','Renown')} ${fmt(p.renown)}</span>${p.arena?`<span>Arena ${fmt(p.arena.highest_rating)}</span>`:''}<span>📚 ${fmt(p.collectionCount)}</span></div><small>${p.title?`✦ ${esc(lang()==='en'?p.title.name_en:p.title.name_es)}`:''}${p.guild?` · [${esc(p.guild.tag||'')}] ${esc(p.guild.name||'')}`:''}</small><small>${p.equippedPet?`🐾 ${esc(p.equippedPet.pet_key)} Lv.${p.equippedPet.level}`:txt('Sin mascota equipada','No pet equipped')}</small></section>`}
function chatHtml(){const msgs=state?.chat?.[chatChannel]||[];return `<div class="p5-rank-tabs"><button data-p5-channel="global" class="${chatChannel==='global'?'active':''}">🌐 Global</button><button data-p5-channel="clan" class="${chatChannel==='clan'?'active':''}" ${!state?.social?.guild?'disabled':''}>🛡️ Clan</button></div><div class="p5-chat">${msgs.map(m=>`<div class="p5-msg"><div class="p5-msg-head"><b>${esc(m.profile?.name||'Player')}${m.profile?.title?` · ✦ ${esc(lang()==='en'?m.profile.title.name_en:m.profile.title.name_es)}`:''}</b><small>${date(m.created_at)}</small></div><p>${esc(m.body)}</p>${m.character_id!==state.character.id?`<div class="p5-msg-actions"><button data-p5-mute="${m.character_id}">🔇 ${txt('Mute','Mute')}</button><button data-p5-report="${m.id}">⚑ ${txt('Reportar','Report')}</button></div>`:''}</div>`).join('')||`<small>${txt('Todavía no hay mensajes.','No messages yet.')}</small>`}</div><form id="p5-chat-form" class="p5-form"><input name="body" maxlength="280" autocomplete="off" placeholder="${txt('Mensaje sin HTML · máx. 280','Plain text · max 280')}"><button ${loading?'disabled':''}>${txt('Enviar','Send')}</button></form><small class="p5-note">${txt('Rate limit, anti-spam, mute y report activos.','Rate limit, anti-spam, mute and report are active.')}</small>`}
function socialHtml(){return `<section class="p5-hero"><span class="p5-eyebrow">SOCIAL</span><h2>👥 ${txt('Mundo Social','Social World')}</h2><p>${txt('Perfiles públicos del juego. Email, wallet y datos personales nunca se muestran.','Public game profiles. Email, wallet and personal data are never shown.')}</p></section><div class="p5-subtabs"><button data-p5-social="friends" class="${socialTab==='friends'?'active':''}">👥 ${txt('Amigos','Friends')}</button><button data-p5-social="chat" class="${socialTab==='chat'?'active':''}">💬 Chat</button></div>${socialTab==='friends'?friendsHtml():chatHtml()}`}

const rankLabel=k=>({level:txt('Nivel','Level'),power:txt('Poder','Power'),arena:'Arena',world_boss:'World Boss',clans:txt('Clanes','Clans'),professions:txt('Profesiones','Professions'),collection:txt('Colección','Collection'),season:txt('Temporada','Season')})[k]||k;
function rankingsHtml(){const r=state?.rankings?.groups?.[rankKey]||[],mine=state?.rankings?.mine?.[rankKey];return `<section class="p5-hero"><span class="p5-eyebrow">RANKINGS</span><h2>🏆 ${rankLabel(rankKey)}</h2><p>${mine?`${txt('Tu posición','Your rank')}: #${mine.rank} · ${fmt(mine.score)}`:txt('Aún sin posición registrada.','No recorded rank yet.')}</p></section><div class="p5-rank-tabs">${RANKING_KEYS.map(k=>`<button data-p5-rank="${k}" class="${rankKey===k?'active':''}">${rankLabel(k)}</button>`).join('')}</div><div class="p5-list">${r.map(x=>{const e=x.entity||{},isMe=x.entity_type==='character'&&x.entity_id===state.character.id;return`<div class="p5-row p5-rank-row ${isMe?'p5-rank-me':''}"><strong>#${x.rank}</strong><div class="p5-row-main"><b>${x.entity_type==='guild'?`[${esc(e.tag||'')}] ${esc(e.name||'Clan')}`:esc(e.name||'Player')}</b><small>${x.entity_type==='character'&&e.title?`✦ ${esc(lang()==='en'?e.title.name_en:e.title.name_es)}`:''}</small></div><strong>${fmt(x.score)}</strong></div>`}).join('')}</div>`}

function eventsHtml(){const ev=state?.events?.calendar||[],notifs=state?.notifications?.items||[];return `<section class="p5-hero"><span class="p5-eyebrow">LIVE EVENTS</span><h2>📅 ${txt('Calendario semanal','Weekly Calendar')}</h2><p>${txt('Los horarios se generan desde configuración del servidor; los eventos mensuales usan plantillas temporales, no fechas permanentes en cliente.','Schedules are generated from server configuration; monthly events use temporary templates, not permanent client dates.')}</p></section><div class="p5-list">${ev.map(e=>{const st=eventState(e),d=e.definition||{};return`<article class="p5-card p5-event ${st}"><div class="p5-event-day"><b>${new Date(e.starts_at).toLocaleDateString(undefined,{weekday:'short'})}</b><small>${new Date(e.starts_at).toLocaleDateString()}</small></div><div><b>${esc(lang()==='en'?(d.name_en||e.event_key):(d.name_es||e.event_key))}</b><small>${st==='active'?txt('ACTIVO AHORA','ACTIVE NOW'):st==='scheduled'?txt('Próximo','Upcoming'):txt('Finalizado','Ended')}${Number(d.bonus_percent)>0?` · +${Math.round(Number(d.bonus_percent)*100)}% ${esc(d.bonus_key||'')}`:''}</small></div>${st==='active'?`<button data-p5-event-claim="${e.id}" ${e.claim||loading?'disabled':''}>${e.claim?txt('Reclamado','Claimed'):txt('Reclamar','Claim')}</button>`:`<span class="p5-status ${st}">${st}</span>`}</article>`}).join('')}</div><section class="p5-block"><h3>🎭 ${txt('Plantillas mensuales/temporales','Monthly/temporary templates')}</h3><div class="p5-chips">${(state?.events?.templates||[]).map(x=>`<span>${esc(lang()==='en'?x.name_en:x.name_es)}</span>`).join('')}</div></section><section class="p5-block"><h3>🔔 ${txt('Notificaciones','Notifications')} · ${state?.notifications?.unread||0}</h3><div class="p5-notifications">${notifs.slice(0,12).map(n=>`<div class="p5-notification ${n.read_at?'read':''}" data-p5-notification="${n.id}"><b>${esc(n.title)}</b><small>${esc(n.body)} · ${date(n.created_at)}</small></div>`).join('')}</div></section>`}

function achievementsHtml(){const a=state?.achievements;return `<section class="p5-hero"><span class="p5-eyebrow">ACHIEVEMENTS + TITLES</span><h2>🏅 ${txt('Logros y Títulos','Achievements & Titles')}</h2><p>${txt('El título equipado aparece debajo de tu nombre.','Your equipped title appears below your name.')}</p></section><div class="p5-list">${(a?.titles||[]).map(t=>`<article class="p5-card p5-title ${t.unlocked?'':'locked'}"><div><b>✦ ${esc(lang()==='en'?t.name_en:t.name_es)}</b><small>${esc(lang()==='en'?t.description_en:t.description_es)}</small></div><button data-p5-title="${t.title_key}" ${!t.unlocked||t.selected||loading?'disabled':''}>${t.selected?txt('Equipado','Equipped'):t.unlocked?txt('Usar','Use'):'🔒'}</button></article>`).join('')}</div>`}
function codexHtml(){const labels={monsters:txt('Monstruos','Monsters'),bosses:'Bosses',equipment:txt('Equipo','Equipment'),sets:'Sets',pets:txt('Mascotas','Pets'),resources:txt('Recursos','Resources'),zones:txt('Zonas','Zones')};return `<section class="p5-hero"><span class="p5-eyebrow">CODEX</span><h2>📚 ${txt('Códice ampliado','Expanded Codex')}</h2></section><div class="p5-codex">${(state?.codex?.categories||[]).map(c=>{const pct=c.total?Math.round(c.unlocked/c.total*100):0;return`<section class="p5-card"><div class="p5-codex-head"><b>${labels[c.category]||c.category}</b><span>${c.unlocked}/${c.total}</span></div><div class="p5-progress"><i style="width:${pct}%"></i></div><div class="p5-codex-items">${c.items.slice(0,30).map(i=>`<span class="${i.unlocked?'':'locked'}">${esc(i.icon)} ${esc(lang()==='en'?i.name_en:i.name_es)}</span>`).join('')}</div></section>`}).join('')}</div>`}

function bodyHtml(){if(!state&&loading)return'<div class="p5-card">…</div>';return({pets:petsHtml,social:socialHtml,rankings:rankingsHtml,events:eventsHtml,achievements:achievementsHtml,codex:codexHtml}[tab]||petsHtml)()}
function render(){renderLauncher();renderPlayerTitle();if(!opened)return;let ov=$('#phase5-overlay');if(!ov){ov=document.createElement('div');ov.id='phase5-overlay';ov.className='phase5-overlay';document.body.append(ov)}const tabs=[['pets','🐾',txt('Mascotas','Pets')],['social','👥','Social'],['rankings','🏆','Rankings'],['events','📅',txt('Eventos','Events')],['achievements','🏅',txt('Títulos','Titles')],['codex','📚','Códice']];ov.innerHTML=`<div class="phase5-sheet"><div class="phase5-bar"><b>🌐 NEXUS REALMS · FASE 5</b><button data-close-phase5>✕</button></div><div class="phase5-tabs">${tabs.map(([k,i,l])=>`<button data-p5-tab="${k}" class="${tab===k?'active':''}">${i} ${l}</button>`).join('')}</div><div class="phase5-body">${bodyHtml()}</div></div>`;bind()}
async function doSearch(q){try{const j=await call({op:'search',query:plainText(q,24)});searchResults=j.results||[];render()}catch(e){toast(e.message)}}async function doInspect(id){try{const j=await call({op:'inspect',characterId:id});inspectProfile=j.profile;render()}catch(e){toast(e.message)}}
function bind(){const ov=$('#phase5-overlay');if(!ov)return;ov.querySelector('[data-close-phase5]')?.addEventListener('click',closeOverlay);ov.addEventListener('click',e=>{if(e.target===ov)closeOverlay()});ov.querySelectorAll('[data-p5-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.p5Tab;render()}));ov.querySelectorAll('[data-p5-equip]').forEach(b=>b.addEventListener('click',()=>act('petEquip',{petId:b.dataset.p5Equip})));ov.querySelectorAll('[data-p5-evolve]').forEach(b=>b.addEventListener('click',()=>{if(confirm(txt('¿Evolucionar esta mascota?','Evolve this pet?')))act('petEvolve',{petId:b.dataset.p5Evolve})}));ov.querySelectorAll('[data-p5-social]').forEach(b=>b.addEventListener('click',()=>{socialTab=b.dataset.p5Social;render()}));ov.querySelector('#p5-player-search')?.addEventListener('submit',e=>{e.preventDefault();doSearch(new FormData(e.currentTarget).get('query'))});ov.querySelectorAll('[data-p5-inspect]').forEach(b=>b.addEventListener('click',()=>doInspect(b.dataset.p5Inspect)));ov.querySelectorAll('[data-p5-friend-add]').forEach(b=>b.addEventListener('click',()=>act('friendRequest',{characterId:b.dataset.p5FriendAdd})));ov.querySelectorAll('[data-p5-friend-response]').forEach(b=>b.addEventListener('click',()=>act('friendRespond',{requestId:b.dataset.p5FriendResponse,accept:b.dataset.accept==='1'})));ov.querySelectorAll('[data-p5-friend-remove]').forEach(b=>b.addEventListener('click',()=>act('friendRemove',{characterId:b.dataset.p5FriendRemove})));ov.querySelectorAll('[data-p5-channel]').forEach(b=>b.addEventListener('click',()=>{chatChannel=b.dataset.p5Channel;render()}));ov.querySelector('#p5-chat-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),body=plainText(f.get('body'),280);if(body)act('chatSend',{channel:chatChannel,body})});ov.querySelectorAll('[data-p5-mute]').forEach(b=>b.addEventListener('click',()=>act('chatMute',{characterId:b.dataset.p5Mute,minutes:1440})));ov.querySelectorAll('[data-p5-report]').forEach(b=>b.addEventListener('click',()=>{const reason=plainText(prompt(txt('Motivo del reporte','Report reason'),'spam')||'',240);if(reason)act('chatReport',{messageId:b.dataset.p5Report,reason})}));ov.querySelectorAll('[data-p5-rank]').forEach(b=>b.addEventListener('click',()=>{rankKey=b.dataset.p5Rank;render()}));ov.querySelectorAll('[data-p5-event-claim]').forEach(b=>b.addEventListener('click',()=>act('eventClaim',{eventId:b.dataset.p5EventClaim})));ov.querySelectorAll('[data-p5-title]').forEach(b=>b.addEventListener('click',()=>act('titleSet',{titleKey:b.dataset.p5Title})));ov.querySelectorAll('[data-p5-notification]').forEach(n=>{if(!n.classList.contains('read'))n.addEventListener('click',()=>act('notificationRead',{notificationId:n.dataset.p5Notification}))})}

window.addEventListener('nexus:panel-render',renderLauncher);window.addEventListener('nexus:more-refresh',renderLauncher);window.addEventListener('nexus:phase4',()=>renderLauncher());document.addEventListener('click',e=>{if(e.target.closest?.('[data-more],[data-tab]'))setTimeout(renderLauncher,0)});supabase.auth.onAuthStateChange((_e,s)=>{if(!s){state=null;closeOverlay();$('#phase5-title-badge')?.remove()}else setTimeout(()=>load(true).catch(()=>{}),1200)});setTimeout(()=>{renderLauncher();token().then(t=>t&&load(true).catch(()=>{}))},1500);
