import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const EDGE=`${SUPABASE_URL}/functions/v1/phase2-engine`;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>localStorage.getItem('nexus-lang')||'es';
const feature=()=>localStorage.getItem('nexus-combat-feature')||'adventure';
const setFeature=v=>localStorage.setItem('nexus-combat-feature',v);
const classIcon=c=>({warrior:'⚔️',mage:'🔮',archer:'🏹',assassin:'🗡️'})[c]||'⚔️';
const roomIcon=t=>({combat:'⚔️',elite:'💀',event:'✦',treasure:'💎',rest:'🔥',trap:'🕸️',boss:'👑'})[t]||'🌀';
const DIFF={normal:{es:'Normal',en:'Normal',min:1},hard:{es:'Difícil',en:'Hard',min:2},nightmare:{es:'Pesadilla',en:'Nightmare',min:4},infernal:{es:'Infernal',en:'Infernal',min:6}};
const txt={
 es:{adventure:'Aventura',rifts:'Grietas',arena:'Arena',unstable:'GRIETAS INESTABLES',riftHelp:'Explora una ruta generada por el servidor. La semilla no la elige el jugador.',tier:'Rift Tier',difficulty:'Dificultad',start:'Abrir grieta',daily:'Intentos diarios',runs:'Completadas',best:'Mejor Tier',modifier:'Modificador',energy:'Costo',enter:'Entrar en sala',abandon:'Abandonar',active:'Grieta activa',victory:'GRIETA SUPERADA',defeat:'GRIETA FALLIDA',rewards:'Recompensas acumuladas',loading:'Cargando...',arenaTitle:'ARENA 1 VS 1',arenaHelp:'Combate asíncrono autoritativo contra otro jugador compatible.',rating:'Rating',rank:'Rango',wins:'Victorias',losses:'Derrotas',streak:'Racha',position:'Posición',find:'Buscar rival',history:'Últimos combates',noHistory:'Aún no hay combates.',win:'VICTORIA',loss:'DERROTA',reward:'Recompensa',close:'Continuar',noOpponent:'No hay un rival compatible ahora mismo.',server:'Servidor autoritativo',season:'Temporada',ends:'Finaliza',gold:'oro',essence:'esencia',locked:'Bloqueado'},
 en:{adventure:'Adventure',rifts:'Rifts',arena:'Arena',unstable:'UNSTABLE RIFTS',riftHelp:'Explore a server-generated route. The player never chooses the seed.',tier:'Rift Tier',difficulty:'Difficulty',start:'Open rift',daily:'Daily runs',runs:'Completed',best:'Best Tier',modifier:'Modifier',energy:'Cost',enter:'Enter room',abandon:'Abandon',active:'Active rift',victory:'RIFT CLEARED',defeat:'RIFT FAILED',rewards:'Accumulated rewards',loading:'Loading...',arenaTitle:'1 VS 1 ARENA',arenaHelp:'Server-authoritative asynchronous combat against a compatible player.',rating:'Rating',rank:'Rank',wins:'Wins',losses:'Losses',streak:'Streak',position:'Position',find:'Find opponent',history:'Recent matches',noHistory:'No matches yet.',win:'VICTORY',loss:'DEFEAT',reward:'Reward',close:'Continue',noOpponent:'No compatible opponent is available right now.',server:'Server authoritative',season:'Season',ends:'Ends',gold:'gold',essence:'essence',locked:'Locked'}
};
const t=k=>txt[lang()]?.[k]||txt.es[k]||k;
let riftState=null,arenaState=null,busy=false,renderQueued=false;

async function headers(){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;return token?{'content-type':'application/json','authorization':`Bearer ${token}`,apikey:SUPABASE_KEY}:{'content-type':'application/json',apikey:SUPABASE_KEY}}
async function call(op,payload={}){const h=await headers();if(!h.authorization)throw new Error(lang()==='es'?'Inicia sesión primero':'Sign in first');const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch(EDGE,{method:'POST',headers:h,body:JSON.stringify({op,payload}),cache:'no-store',signal:ctl.signal});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||'Phase 2 request failed');return j}finally{clearTimeout(timer)}}
function isCombat(){return /Combate|Combat/i.test($('#panel .section-head h2')?.textContent||'')}
function setPanelMode(){const p=$('#panel');if(!p)return;p.classList.remove('p2-mode-adventure','p2-mode-rifts','p2-mode-arena');if(isCombat())p.classList.add(`p2-mode-${feature()}`)}
function shell(){return `<div id="p2-featurebar" class="p2-featurebar"><button data-p2-feature="adventure" class="${feature()==='adventure'?'active':''}">⚔️ ${t('adventure')}</button><button data-p2-feature="rifts" class="${feature()==='rifts'?'active':''}">🌀 ${t('rifts')}</button><button data-p2-feature="arena" class="${feature()==='arena'?'active':''}">🏆 ${t('arena')}</button></div><section id="p2-host" class="p2-host"></section>`}
function ensureShell(){if(!isCombat()){const p=$('#panel');p?.classList.remove('p2-mode-adventure','p2-mode-rifts','p2-mode-arena');$('#p2-featurebar')?.remove();$('#p2-host')?.remove();return}if(!$('#p2-featurebar')){$('#panel .section-head')?.insertAdjacentHTML('afterend',shell())}setPanelMode();renderFeature()}
function qRender(){if(renderQueued)return;renderQueued=true;queueMicrotask(()=>{renderQueued=false;ensureShell()})}
function errorBox(e){const host=$('#p2-host');if(!host)return;const msg=String(e?.message||e);host.innerHTML=`<div class="p2-error">⚠️ ${esc(msg==='no_compatible_opponent'?t('noOpponent'):msg)}</div>`}
function fmtDate(v){if(!v)return'—';try{return new Date(v).toLocaleString(lang()==='es'?'es':'en',{dateStyle:'medium',timeStyle:'short'})}catch{return String(v)}}
function stat(label,value){return `<div class="p2-stat"><small>${label}</small><b>${value}</b></div>`}
function rewardLine(x={}){return `${Number(x.gold||0)} 🪙 · ${Number(x.xp||0)} XP · ${Number(x.essence||0)} ✨ · ${Number(x.ore||0)} ⛏️ · ${Number(x.wood||0)} 🪵`}
function difficultyOptions(highest){return Object.entries(DIFF).map(([id,d])=>`<option value="${id}" ${highest<d.min?'disabled':''}>${lang()==='es'?d.es:d.en}${highest<d.min?` · ${t('locked')} T${d.min}`:''}</option>`).join('')}
function tierOptions(highest){return Array.from({length:Math.max(1,highest)},(_,i)=>i+1).map(n=>`<option value="${n}" ${n===highest?'selected':''}>Tier ${n}</option>`).join('')}
function roomsHtml(run){return `<div class="p2-room-path">${(run.rooms||[]).map(r=>`<div class="p2-room ${r.done?'done':''} ${r.current?'current':''}"><span>${roomIcon(r.type)}</span><small>${esc(r.label)}</small><em>${r.done?'✓':r.current?'▶':r.index+1}</em></div>`).join('')}</div>`}
function riftHtml(){if(!riftState)return`<div class="p2-loading">${t('loading')}</div>`;const p=riftState.progress,run=riftState.active;if(run){const ended=run.status!=='active';return `<div class="p2-title"><div><span>🌀 ${t('server')}</span><h3>${t('active')} · Tier ${run.tier}</h3><p>${esc(run.modifierLabel)}</p></div><strong>${String(run.difficulty).toUpperCase()}</strong></div>${roomsHtml(run)}<div class="p2-stats">${stat('HP',`${run.currentHp}/${run.maxHp}`)}${stat('MP',`${run.currentMana}/${run.maxMana}`)}${stat(t('energy'),`${run.energyCost}⚡`)}</div><div class="p2-card"><small>${t('rewards')}</small><b>${rewardLine(run.totals)}</b></div>${run.lastResolution?.room?`<div class="p2-last"><b>${roomIcon(run.lastResolution.room.type)} ${esc(run.lastResolution.room.label)}</b><small>${esc(String(run.lastResolution.result||''))}</small></div>`:''}<div class="p2-actions">${!ended?`<button class="primary" data-p2-rift-next ${busy?'disabled':''}>${t('enter')}</button><button class="ghost" data-p2-rift-abandon ${busy?'disabled':''}>${t('abandon')}</button>`:''}</div>`}return `<div class="p2-title"><div><span>🌀 ${t('server')}</span><h3>${t('unstable')}</h3><p>${t('riftHelp')}</p></div><strong>Tier ${p.highestTier}</strong></div><div class="p2-stats">${stat(t('daily'),`${p.dailyRuns}/${p.dailyLimit}`)}${stat(t('runs'),p.runsCompleted)}${stat(t('best'),p.bestTier)}</div><div class="p2-config"><label>${t('tier')}<select id="p2-tier">${tierOptions(p.highestTier)}</select></label><label>${t('difficulty')}<select id="p2-difficulty">${difficultyOptions(p.highestTier)}</select></label></div><button class="primary p2-full" data-p2-rift-start ${busy||p.dailyRuns>=p.dailyLimit?'disabled':''}>🌀 ${t('start')}</button><div class="p2-recent">${(riftState.recent||[]).map(x=>`<div><span>Tier ${x.tier} · ${esc(String(x.difficulty))}</span><b class="${x.status}">${esc(String(x.status))}</b></div>`).join('')}</div>`}
function arenaHtml(){if(!arenaState)return`<div class="p2-loading">${t('loading')}</div>`;const p=arenaState.profile,s=arenaState.season;return `<div class="p2-title"><div><span>🏆 ${t('server')}</span><h3>${t('arenaTitle')}</h3><p>${t('arenaHelp')}</p></div><strong>${esc(p.rank)}</strong></div><div class="p2-season"><span>${t('season')}: <b>${esc(s.name)}</b></span><small>${t('ends')}: ${fmtDate(s.endsAt)}</small></div><div class="p2-stats">${stat(t('rating'),p.rating)}${stat(t('rank'),esc(p.rank))}${stat(t('position'),`#${p.position}`)}${stat(t('wins'),p.wins)}${stat(t('losses'),p.losses)}${stat(t('streak'),p.streak)}</div><button class="primary p2-full" data-p2-arena-match ${busy||p.matchesToday>=p.dailyLimit?'disabled':''}>⚔️ ${t('find')} · ${p.matchesToday}/${p.dailyLimit}</button><div class="p2-history"><h4>${t('history')}</h4>${(arenaState.recent||[]).length?(arenaState.recent||[]).map(m=>`<div class="p2-history-row ${m.won?'won':'lost'}"><div><b>${m.won?'✅':'❌'} ${esc(m.opponent)}</b><small>${fmtDate(m.createdAt)}</small></div><strong>${m.delta>=0?'+':''}${m.delta}</strong></div>`).join(''):`<div class="p2-empty">${t('noHistory')}</div>`}</div>`}
function renderFeature(){const host=$('#p2-host');if(!host||!isCombat())return;setPanelMode();if(feature()==='adventure'){host.innerHTML='';return}host.innerHTML=feature()==='rifts'?riftHtml():arenaHtml()}
async function loadRifts(){try{riftState=await call('rift_state');renderFeature()}catch(e){errorBox(e)}}
async function loadArena(){try{arenaState=await call('arena_state');renderFeature()}catch(e){errorBox(e)}}
async function chooseFeature(v){setFeature(v);setPanelMode();renderFeature();if(v==='rifts'&&!riftState)await loadRifts();if(v==='arena'&&!arenaState)await loadArena()}
function overlayBase(){let o=$('#p2-overlay');if(!o){o=document.createElement('div');o.id='p2-overlay';o.className='p1-overlay';document.body.append(o)}return o}
function closeOverlay(){ $('#p2-overlay')?.remove() }
function showRiftResolution(res){const rr=res?.resolution,run=res?.run;if(!rr?.room)return;const o=overlayBase(),won=rr.result!=='defeat';o.innerHTML=`<div class="p1-battle-sheet"><div class="p1-battle-stage tone-rift"><div class="p1-battle-top"><span>🌀 RIFT · T${run?.tier||''}</span><b>${roomIcon(rr.room.type)} ${esc(rr.room.label)}</b></div><div class="p2-resolution-icon">${roomIcon(rr.room.type)}</div><div class="p2-resolution-result ${won?'victory':'defeat'}">${won?'✓':'✕'} ${won?t('victory'):t('defeat')}</div></div><div class="p1-feed">${(rr.log||[]).slice(-8).map(x=>`<div>${esc(x.text||String(x))}</div>`).join('')}</div><div class="p1-result ${won?'victory':'defeat'}"><b>${rewardLine(rr.reward||{})}</b><button data-p2-close>${t('close')}</button></div></div>`;o.querySelector('[data-p2-close]')?.addEventListener('click',closeOverlay,{once:true})}
function showArenaResult(m){if(!m)return;const o=overlayBase(),won=Boolean(m.won);o.innerHTML=`<div class="p1-battle-sheet"><div class="p1-battle-stage tone-rift"><div class="p1-battle-top"><span>🏆 ARENA</span><b>${esc(m.rank||'')}</b></div><div class="p1-fighters"><div class="p1-fighter player"><div class="p1-avatar">${classIcon(m.player.class)}</div><b>${esc(m.player.name)}</b><small>Lv ${m.player.level} · PWR ${m.player.power}</small><div class="p1-bar hp"><i style="width:${Math.max(0,Math.min(100,m.player.hp/m.player.maxHp*100))}%"></i><span>${m.player.hp}/${m.player.maxHp}</span></div></div><div class="p1-vs">VS</div><div class="p1-fighter enemy"><div class="p1-avatar">${classIcon(m.opponent.class)}</div><b>${esc(m.opponent.name)}</b><small>Lv ${m.opponent.level} · PWR ${m.opponent.power}</small><div class="p1-bar enemyhp"><i style="width:${Math.max(0,Math.min(100,m.opponent.hp/m.opponent.maxHp*100))}%"></i><span>${m.opponent.hp}/${m.opponent.maxHp}</span></div></div></div></div><div class="p1-feed">${(m.log||[]).slice(-8).map(x=>`<div>${esc(x.text||'')}</div>`).join('')}</div><div class="p1-result ${won?'victory':'defeat'}"><b>${won?t('win'):t('loss')} · ${m.delta>=0?'+':''}${m.delta} rating</b><span>${t('reward')}: ${m.reward?.gold||0} ${t('gold')}${m.reward?.essence?` · ${m.reward.essence} ${t('essence')}`:''}</span><button data-p2-close>${t('close')}</button></div></div>`;o.querySelector('[data-p2-close]')?.addEventListener('click',closeOverlay,{once:true})}

async function startRift(){if(busy)return;busy=true;renderFeature();try{const tier=Number($('#p2-tier')?.value||1),difficulty=$('#p2-difficulty')?.value||'normal',r=await call('rift_start',{tier,difficulty});riftState={...(await call('rift_state')),active:r.run};renderFeature()}catch(e){errorBox(e)}finally{busy=false;renderFeature()}}
async function advanceRift(){if(busy)return;busy=true;renderFeature();try{const r=await call('rift_advance');showRiftResolution(r);riftState=await call('rift_state');renderFeature()}catch(e){errorBox(e)}finally{busy=false;renderFeature()}}
async function abandonRift(){if(busy)return;busy=true;renderFeature();try{await call('rift_abandon');riftState=await call('rift_state')}catch(e){errorBox(e)}finally{busy=false;renderFeature()}}
async function arenaMatch(){if(busy)return;busy=true;renderFeature();try{const r=await call('arena_match',{requestKey:crypto.randomUUID()});showArenaResult(r.match);arenaState=await call('arena_state');renderFeature()}catch(e){errorBox(e)}finally{busy=false;renderFeature()}}

document.addEventListener('click',e=>{const b=e.target?.closest?.('[data-p2-feature],[data-p2-rift-start],[data-p2-rift-next],[data-p2-rift-abandon],[data-p2-arena-match]');if(!b)return;if(b.dataset.p2Feature){e.preventDefault();chooseFeature(b.dataset.p2Feature);return}if(b.hasAttribute('data-p2-rift-start'))startRift();else if(b.hasAttribute('data-p2-rift-next'))advanceRift();else if(b.hasAttribute('data-p2-rift-abandon'))abandonRift();else if(b.hasAttribute('data-p2-arena-match'))arenaMatch()},true);
document.addEventListener('nexus:panel-render',qRender);
window.addEventListener('pageshow',qRender);
supabase.auth.onAuthStateChange((_event,session)=>{if(!session){riftState=null;arenaState=null;$('#p2-featurebar')?.remove();$('#p2-host')?.remove()}else qRender()});
setTimeout(qRender,800);
