import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const MANUAL_EDGE=`${SUPABASE_URL}/functions/v1/manual-combat`;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>localStorage.getItem('nexus-lang')||'es';
let cachedState=null,lastFetch=0,refreshTimer=null,manualCombat=null,manualBusy=false,manualLogCount=0;
const mode=()=>localStorage.getItem('nexus-combat-mode')||'auto';
const setMode=v=>localStorage.setItem('nexus-combat-mode',v);
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const pct=(a,b)=>Math.max(0,Math.min(100,b?Number(a)/Number(b)*100:0));
const L={
 es:{auto:'AUTO',manual:'MANUAL',fight:'Combatir',travel:'Viajar',youAreHere:'ESTÁS AQUÍ',level:'Nivel',recommended:'Nivel recomendado',resources:'Recursos',enemies:'Enemigos',boss:'Jefe',safe:'Zona segura',open:'Zona hostil',continue:'Continuar',flee:'Huir',basic:'Ataque básico',mana:'Maná',cooldown:'Enfriamiento',victory:'VICTORIA',defeat:'DERROTA',loading:'Preparando combate...',worldRoute:'Ruta de los Reinos',manualHelp:'Elige tus habilidades. El servidor resuelve cada turno.',autoHelp:'La IA resuelve el combate y la escena reproduce el resultado.',marked:'Presa marcada',guard:'Guardia',enrage:'Enfurecido',bossIncoming:'Ataque peligroso entrante',returnGame:'Volver al juego'},
 en:{auto:'AUTO',manual:'MANUAL',fight:'Fight',travel:'Travel',youAreHere:'YOU ARE HERE',level:'Level',recommended:'Recommended level',resources:'Resources',enemies:'Enemies',boss:'Boss',safe:'Safe zone',open:'Hostile zone',continue:'Continue',flee:'Flee',basic:'Basic attack',mana:'Mana',cooldown:'Cooldown',victory:'VICTORY',defeat:'DEFEAT',loading:'Preparing combat...',worldRoute:'Realm Route',manualHelp:'Choose your skills. The server resolves every turn.',autoHelp:'AI resolves combat and the scene replays the result.',marked:'Marked prey',guard:'Guard',enrage:'Enraged',bossIncoming:'Dangerous attack incoming',returnGame:'Return to game'}
};
const t=k=>L[lang()]?.[k]||L.es[k]||k;
const zoneMeta={
 bastion:{icon:'🏰',tone:'bastion',resources:['Refugio','Regeneración'],descEs:'Fortaleza central de los aventureros.',descEn:'Central fortress of the adventurers.'},
 emberwood:{icon:'🌲',tone:'forest',resources:['🪵 Madera','⛏️ Mineral'],descEs:'Bosque antiguo cubierto de brasas y raíces vivas.',descEn:'Ancient forest of embers and living roots.'},
 moonwater_coast:{icon:'🌊',tone:'coast',resources:['🎣 Pesca','🪵 Madera'],descEs:'Costa lunar azotada por criaturas de las profundidades.',descEn:'Moonlit coast haunted by creatures from the deep.'},
 mire:{icon:'🌫️',tone:'mire',resources:['🌿 Esencia','🎣 Pesca'],descEs:'Pantano tóxico donde la niebla nunca desaparece.',descEn:'Toxic mire where the mist never fades.'},
 frostpeak:{icon:'❄️',tone:'frost',resources:['⛏️ Mineral','✨ Esencia'],descEs:'Cumbres congeladas dominadas por bestias de hielo.',descEn:'Frozen peaks ruled by ice beasts.'},
 ashlands:{icon:'🌋',tone:'ash',resources:['⛏️ Mineral','✨ Esencia'],descEs:'Tierras volcánicas consumidas por ceniza y fuego.',descEn:'Volcanic lands consumed by ash and fire.'},
 rift:{icon:'🌀',tone:'rift',resources:['✨ Esencia','💠 Reliquias'],descEs:'La frontera rota entre Nexus y el Vacío.',descEn:'The shattered frontier between Nexus and the Void.'}
};
const enemyIcon=id=>({goblin:'👺','dire-wolf':'🐺','thorn-shaman':'🧙','ancient-treant':'🌳','reef-raider':'🗡️','drowned-sailor':'💀','tide-serpent':'🐍','kraken-spawn':'🐙',wraith:'👻','bog-stalker':'🕷️','plague-witch':'🧙‍♀️','mire-hydra':'🐲','ice-wolf':'🐺','frost-revenant':'💀','crystal-golem':'🗿','frost-wyrm':'🐉','ash-imp':'👹','lava-brute':'🪨','cinder-mage':'🔥','inferno-colossus':'🌋','rift-hound':'🐺','void-cultist':'🕯️','rift-knight':'🛡️',boss:'👑'})[id]||'⚔️';
const classIcon=c=>({warrior:'⚔️',mage:'🔮',archer:'🏹',assassin:'🗡️'})[c]||'🛡️';

async function sessionHeaders(){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;return token?{'content-type':'application/json','authorization':`Bearer ${token}`}:{'content-type':'application/json'};}
async function fetchState(force=false){if(!force&&cachedState&&Date.now()-lastFetch<8000)return cachedState;const headers=await sessionHeaders();if(!headers.authorization)return null;const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),9000);try{const r=await fetch('/api/state',{headers,cache:'no-store',signal:ctl.signal});if(!r.ok)return cachedState;cachedState=await r.json();lastFetch=Date.now();return cachedState;}catch{return cachedState}finally{clearTimeout(timer)}}
async function manualCall(op,payload={}){const headers=await sessionHeaders();if(!headers.authorization)throw new Error(lang()==='es'?'Inicia sesión primero':'Sign in first');const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(MANUAL_EDGE,{method:'POST',headers:{...headers,apikey:SUPABASE_KEY},body:JSON.stringify({op,payload}),cache:'no-store',signal:ctl.signal});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||'Manual combat failed');return j;}finally{clearTimeout(timer)}}
function scheduleRefresh(ms=100){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refreshVisual(true),ms)}
function currentHeading(){return $('#panel .section-head h2')?.textContent||''}
function isWorld(){return /Mundo|World/i.test(currentHeading())}
function isZoneCombat(){const h=currentHeading();const zone=$('#panel [data-combat="zone"]');return /Combate|Combat/i.test(h)&&(!zone||zone.classList.contains('active'))}
function zoneName(z){return lang()==='es'?(z?.nameEs||z?.name||z?.id):(z?.name||z?.nameEs||z?.id)}
function enemyName(e){return lang()==='es'?(e?.nameEs||e?.name||e?.id):(e?.name||e?.nameEs||e?.id)}

function worldHtml(state){const p=state.player,zones=[...(state.zones||[])].sort((a,b)=>Number(a.requiredLevel||0)-Number(b.requiredLevel||0)),current=zones.find(z=>z.id===p.zoneId),meta=zoneMeta[p.zoneId]||zoneMeta.bastion,enemies=(state.enemies||[]).filter(e=>e.zoneId===p.zoneId),boss=enemies.find(e=>e.boss);return `<section id="p1-world" class="p1-world tone-${meta.tone}"><div class="p1-world-hero"><div><span class="p1-kicker">${t('youAreHere')}</span><h2>${meta.icon} ${esc(zoneName(current))}</h2><p>${esc(lang()==='es'?meta.descEs:meta.descEn)}</p><div class="p1-zone-tags"><span>${current?.safe?t('safe'):t('open')}</span><span>${t('recommended')}: ${Number(current?.requiredLevel||1)}</span></div></div><div class="p1-zone-orb">${meta.icon}</div></div><div class="p1-zone-details"><div><small>${t('resources')}</small><b>${meta.resources.join(' · ')}</b></div><div><small>${t('enemies')}</small><b>${enemies.length?enemies.filter(e=>!e.boss).map(e=>enemyIcon(e.id)).join(' '):'—'}</b></div><div><small>${t('boss')}</small><b>${boss?`${enemyIcon(boss.id)} ${esc(enemyName(boss))}`:'—'}</b></div></div><div class="p1-route-head"><b>🗺️ ${t('worldRoute')}</b></div><div class="p1-route">${zones.map((z,i)=>{const m=zoneMeta[z.id]||zoneMeta.bastion,locked=Number(p.level)<Number(z.requiredLevel||0),here=p.zoneId===z.id,b=(state.enemies||[]).find(e=>e.zoneId===z.id&&e.boss);return `<article class="p1-zone-node ${here?'here':''} ${locked?'locked':''}" data-p1-zone="${esc(z.id)}"><div class="p1-node-line">${i<zones.length-1?'<i></i>':''}</div><div class="p1-node-icon">${m.icon}</div><div class="p1-node-body"><span>${here?t('youAreHere'):`${t('level')} ${Number(z.requiredLevel||1)}`}</span><b>${esc(zoneName(z))}</b><small>${m.resources.join(' · ')}${b?` · 👑 ${esc(enemyName(b))}`:''}</small></div><button data-p1-travel="${esc(z.id)}" ${here||locked?'disabled':''}>${locked?'🔒':here?'✓':t('travel')}</button></article>`}).join('')}</div></section>`}
function renderWorld(state){let host=$('#p1-world');if(!isWorld()){host?.remove();document.querySelectorAll('.p1-legacy-destinations').forEach(e=>e.classList.remove('p1-legacy-destinations'));return;}const legacy=$('#panel .destination-list')?.closest('.content-block');legacy?.classList.add('p1-legacy-destinations');if(!host){host=document.createElement('div');const head=$('#panel .section-head');head?.insertAdjacentElement('afterend',host)}host.outerHTML=worldHtml(state)}

function enemyCard(e){return `<article class="p1-enemy-card ${e.boss?'boss':''}"><div class="p1-enemy-art">${enemyIcon(e.id)}</div><div class="p1-enemy-main"><span>${e.boss?'BOSS':`${t('level')} ${e.level}`}</span><b>${esc(enemyName(e))}</b><div class="p1-mini-stats"><em>HP ${e.hp}</em><em>ATK ${e.atk}</em><em>DEF ${e.def}</em><em>${e.reward?.gold||0} 🪙</em></div></div><button class="p1-fight" data-p1-fight="${esc(e.id)}">⚔️ ${t('fight')}</button></article>`}
function combatRosterHtml(state){const p=state.player,enemies=(state.enemies||[]).filter(e=>e.zoneId===p.zoneId);return `<section id="p1-combat-roster" class="p1-combat-roster"><div class="p1-modebar"><div><b>⚔️ ${lang()==='es'?'Modo de combate':'Combat mode'}</b><small>${mode()==='manual'?t('manualHelp'):t('autoHelp')}</small></div><div class="p1-mode-toggle"><button data-p1-mode="auto" class="${mode()==='auto'?'active':''}">🤖 ${t('auto')}</button><button data-p1-mode="manual" class="${mode()==='manual'?'active':''}">⚔️ ${t('manual')}</button></div></div><div class="p1-enemy-grid">${enemies.map(enemyCard).join('')||`<div class="p1-empty">${lang()==='es'?'Viaja a una zona hostil para combatir.':'Travel to a hostile zone to fight.'}</div>`}</div></section>`}
function renderCombat(state){let host=$('#p1-combat-roster');if(!isZoneCombat()){host?.remove();document.querySelectorAll('.p1-legacy-enemies').forEach(e=>e.classList.remove('p1-legacy-enemies'));return;}const legacy=$('#panel .enemy-list');legacy?.classList.add('p1-legacy-enemies');if(!host){host=document.createElement('div');const seg=$('#panel .segmented');seg?.insertAdjacentElement('afterend',host)}host.outerHTML=combatRosterHtml(state)}

function stageHtml({player,enemy,modeLabel}){const pm=zoneMeta[cachedState?.player?.zoneId]||zoneMeta.rift;return `<div class="p1-battle-stage tone-${pm.tone}" data-stage><div class="p1-battle-top"><span>${modeLabel}</span>${enemy.boss?`<b>👑 BOSS · ${enemy.phase||'I'}</b>`:''}</div>${enemy.warning?`<div class="p1-boss-warning">⚠️ ${esc(enemy.warning)}</div>`:''}<div class="p1-fighters"><div class="p1-fighter player"><div class="p1-avatar">${classIcon(player.class)}</div><b>${esc(player.name)}</b><small>${t('level')} ${player.level}</small><div class="p1-bar hp"><i style="width:${pct(player.hp,player.maxHp)}%"></i><span>${player.hp}/${player.maxHp}</span></div><div class="p1-bar mana"><i style="width:${pct(player.mana,player.maxMana)}%"></i><span>${player.mana}/${player.maxMana} ${t('mana')}</span></div></div><div class="p1-vs">VS</div><div class="p1-fighter enemy ${enemy.boss?'boss':''}"><div class="p1-avatar">${enemyIcon(enemy.id)}</div><b>${esc(enemy.name)}</b><small>${enemy.boss?'BOSS':`${t('level')} ${enemy.level}`}</small><div class="p1-bar hp enemyhp"><i style="width:${pct(enemy.hp,enemy.maxHp)}%"></i><span>${enemy.hp}/${enemy.maxHp}</span></div></div></div></div>`}
function overlayRoot(){let ov=$('#p1-combat-overlay');if(!ov){ov=document.createElement('div');ov.id='p1-combat-overlay';ov.className='p1-overlay';document.body.append(ov)}return ov}
function closeOverlay(reload=false){$('#p1-combat-overlay')?.remove();manualCombat=null;manualLogCount=0;if(reload)location.reload();else scheduleRefresh(150)}
function floatText(side,text,cls=''){const host=$(`#p1-combat-overlay .p1-fighter.${side}`);if(!host)return;const el=document.createElement('span');el.className=`p1-float ${cls}`;el.textContent=text;host.append(el);setTimeout(()=>el.remove(),900)}
async function animateLogs(logs,start=0){for(let i=start;i<logs.length;i++){const row=logs[i],text=typeof row==='string'?row:String(row?.text||'');if(row?.type==='player')floatText('enemy',`${row.crit?'CRIT ':''}-${row.damage}`,row.crit?'crit':'');else if(row?.type==='enemy')floatText('player',`-${row.damage}`,row.bossPower?'boss-hit':'');else if(row?.type==='dodge')floatText('player','DODGE','dodge');else if(/CRIT/.test(text))floatText('enemy',text,'crit');else if(/Dodge/i.test(text))floatText('player','DODGE','dodge');const feed=$('#p1-combat-overlay .p1-feed');if(feed){const d=document.createElement('div');d.textContent=text;feed.append(d);feed.scrollTop=feed.scrollHeight}await delay(260)}}

async function startAuto(enemyId){const state=await fetchState(true),e=(state?.enemies||[]).find(x=>x.id===enemyId),p=state?.player;if(!e||!p)return;const ov=overlayRoot();ov.innerHTML=`<div class="p1-battle-sheet">${stageHtml({player:{name:p.name,class:p.class,level:p.level,hp:p.hp,maxHp:p.maxHp,mana:p.mana,maxMana:p.maxMana},enemy:{id:e.id,name:enemyName(e),level:e.level,hp:e.hp,maxHp:e.hp,boss:e.boss,phase:e.boss?'I':null},modeLabel:`🤖 ${t('auto')}`})}<div class="p1-feed"><div>${t('loading')}</div></div><button class="p1-close-battle" disabled>...</button></div>`;const legacy=$(`#panel .enemy-list [data-enemy="${CSS.escape(enemyId)}"]`);if(!legacy){closeOverlay();return}legacy.click();let lines=[];for(let i=0;i<24;i++){await delay(180);lines=[...document.querySelectorAll('#panel .log div')].map(x=>x.textContent||'');if(lines.length)break}await animateLogs(lines.map(text=>({text})),0);const btn=$('#p1-combat-overlay .p1-close-battle');if(btn){btn.disabled=false;btn.textContent=t('continue');btn.onclick=()=>closeOverlay(false)}scheduleRefresh(200)}

function manualControls(c){const skills=(c.skills||[]).map(s=>`<button data-p1-skill="${esc(s.id)}" ${!s.available||manualBusy?'disabled':''}><b>${esc(lang()==='es'?(s.nameEs||s.name):s.name)}</b><small>${s.manaCost} ${t('mana')}${s.cooldownRemaining?` · ${t('cooldown')} ${s.cooldownRemaining}`:''}</small></button>`).join('');return `<div class="p1-effects">${(c.effects||[]).map(x=>`<span>${x.key==='marked'?'🎯':x.key==='guard'?'🛡️':'🔥'} ${esc(x.label)}</span>`).join('')}</div><div class="p1-manual-actions"><button data-p1-basic ${manualBusy?'disabled':''}>⚔️ ${t('basic')}</button>${skills}</div><div class="p1-battle-actions"><button class="ghost" data-p1-flee ${manualBusy?'disabled':''}>↩ ${t('flee')}</button></div>`}
function renderManual(){const c=manualCombat;if(!c)return;const ov=overlayRoot();ov.innerHTML=`<div class="p1-battle-sheet">${stageHtml({player:c.player,enemy:c.enemy,modeLabel:`⚔️ ${t('manual')} · T${c.turn}`})}<div class="p1-feed">${(c.log||[]).slice(-7).map(x=>`<div>${esc(typeof x==='string'?x:x.text||'')}</div>`).join('')}</div>${c.status==='active'?manualControls(c):`<div class="p1-result ${c.status}"><b>${c.status==='victory'?t('victory'):c.status==='defeat'?t('defeat'):c.status.toUpperCase()}</b><button data-p1-finish>${t('returnGame')}</button></div>`}</div>`;ov.querySelector('[data-p1-basic]')?.addEventListener('click',()=>manualTurn('basic'));ov.querySelectorAll('[data-p1-skill]').forEach(b=>b.addEventListener('click',()=>manualTurn(b.dataset.p1Skill)));ov.querySelector('[data-p1-flee]')?.addEventListener('click',manualFlee);ov.querySelector('[data-p1-finish]')?.addEventListener('click',()=>closeOverlay(true));}
async function startManual(enemyId){manualBusy=true;try{const j=await manualCall('start',{enemyId});manualCombat=j.combat;manualLogCount=manualCombat?.log?.length||0;renderManual()}catch(e){alert(e.message)}finally{manualBusy=false;renderManual()}}
async function manualTurn(action){if(!manualCombat||manualBusy)return;manualBusy=true;const before=manualCombat.log?.length||0;renderManual();try{const j=await manualCall('turn',{sessionId:manualCombat.id,action});manualCombat=j.combat;renderManual();await animateLogs(manualCombat.log||[],before);renderManual()}catch(e){alert(e.message)}finally{manualBusy=false;renderManual()}}
async function manualFlee(){if(!manualCombat||manualBusy)return;manualBusy=true;try{const j=await manualCall('flee',{sessionId:manualCombat.id});manualCombat={...manualCombat,status:j.combat?.status||'fled'};renderManual()}catch(e){alert(e.message)}finally{manualBusy=false}}

function showTravel(name){const old=$('#p1-travel-transition');old?.remove();const el=document.createElement('div');el.id='p1-travel-transition';el.className='p1-travel-transition';el.innerHTML=`<div><span>🗺️</span><b>${esc(name)}</b><small>${lang()==='es'?'Viajando...':'Traveling...'}</small></div>`;document.body.append(el);setTimeout(()=>el.remove(),900)}
async function refreshVisual(force=false){const state=await fetchState(force);if(!state?.player)return;renderWorld(state);renderCombat(state)}

document.addEventListener('click',e=>{const target=e.target?.closest?.('[data-p1-mode],[data-p1-fight],[data-p1-travel],[data-tab],[data-combat],[data-zone],[data-enemy]');if(!target)return;if(target.dataset.p1Mode){setMode(target.dataset.p1Mode);renderCombat(cachedState);return}if(target.dataset.p1Fight){const id=target.dataset.p1Fight;if(mode()==='manual')startManual(id);else startAuto(id);return}if(target.dataset.p1Travel){const id=target.dataset.p1Travel,name=zoneName((cachedState?.zones||[]).find(z=>z.id===id));showTravel(name);const legacy=$(`#panel [data-zone="${CSS.escape(id)}"]`);legacy?.click();setTimeout(()=>scheduleRefresh(0),800);return}if(target.matches('[data-tab],[data-combat]'))scheduleRefresh(80);if(target.matches('[data-zone],[data-enemy]'))scheduleRefresh(900)},true);
window.addEventListener('pageshow',()=>scheduleRefresh(250));
window.addEventListener('focus',()=>scheduleRefresh(200));
supabase.auth.onAuthStateChange((_event,session)=>{if(session)scheduleRefresh(300);else{cachedState=null;$('#p1-world')?.remove();$('#p1-combat-roster')?.remove();$('#p1-combat-overlay')?.remove()}});
setTimeout(()=>scheduleRefresh(0),650);
