import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const EDGE=`${SUPABASE_URL}/functions/v1/phase3-engine`;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>localStorage.getItem('nexus-lang')||'es';
const slotIcon=s=>({weapon:'⚔️',helmet:'⛑️',armor:'🛡️',gloves:'🧤',boots:'🥾',ring:'💍'})[s]||'◆';
const classIcon=c=>({warrior:'⚔️',mage:'🔮',archer:'🏹',assassin:'🗡️'})[c]||'⚙️';
const L={
 es:{builds:'Builds',sets:'Sets',specializations:'Especializaciones',equipment:'Equipo',build:'BUILD ACTUAL',set:'SET',pieces:'piezas',active:'ACTIVO',locked:'BLOQUEADO',inspect:'Inspeccionar',equip:'Equipar',unequip:'Desequipar',empty:'Vacío',choose:'Elegir especialización',change:'Cambiar especialización',level10:'Se desbloquea en nivel 10',freeFirst:'Primera elección gratis',respec:'Respec',respecCost:'Costo aproximado',gold:'oro',essence:'esencia',recommended:'Set recomendado',skills:'Habilidades',passives:'Bonificaciones',noSet:'Sin set',close:'Cerrar',loading:'Cargando builds...',server:'Calculado por servidor',pvp:'Arena usa límites PvP separados',noPay:'Los sets principales se obtienen jugando; no requieren compra real.',current:'Actual',confirmChange:'¿Cambiar especialización usando oro y esencia internos?',baseSkills:'Las habilidades base se mantienen.',finalStats:'Efectos finales',openBuilds:'Abrir builds'},
 en:{builds:'Builds',sets:'Sets',specializations:'Specializations',equipment:'Equipment',build:'CURRENT BUILD',set:'SET',pieces:'pieces',active:'ACTIVE',locked:'LOCKED',inspect:'Inspect',equip:'Equip',unequip:'Unequip',empty:'Empty',choose:'Choose specialization',change:'Change specialization',level10:'Unlocks at level 10',freeFirst:'First choice is free',respec:'Respec',respecCost:'Estimated cost',gold:'gold',essence:'essence',recommended:'Recommended set',skills:'Skills',passives:'Bonuses',noSet:'No set',close:'Close',loading:'Loading builds...',server:'Server calculated',pvp:'Arena uses separate PvP caps',noPay:'Core sets are earned through gameplay; no real-money purchase is required.',current:'Current',confirmChange:'Change specialization using internal gold and essence?',baseSkills:'Base skills remain available.',finalStats:'Final effects',openBuilds:'Open builds'}
};
const t=k=>L[lang()]?.[k]||L.es[k]||k;
let state=null,busy=false,view='build',lastLoad=0,loadPromise=null;

async function headers(){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;return token?{'content-type':'application/json','authorization':`Bearer ${token}`,apikey:SUPABASE_KEY}:{'content-type':'application/json',apikey:SUPABASE_KEY}}
async function call(op,payload={}){const h=await headers();if(!h.authorization)throw new Error(lang()==='es'?'Inicia sesión primero':'Sign in first');const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),14000);try{const r=await fetch(EDGE,{method:'POST',headers:h,body:JSON.stringify({op,payload}),cache:'no-store',signal:ctl.signal});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||'Phase 3 request failed');return j}finally{clearTimeout(timer)}}
async function load(force=false){if(loadPromise)return loadPromise;if(!force&&state&&Date.now()-lastLoad<7000)return state;loadPromise=(async()=>{const j=await call('state');state=j;lastLoad=Date.now();renderLauncher();augmentInventory();if($('#p3-modal'))renderModal();return state})().finally(()=>{loadPromise=null});return loadPromise}
function fmtEffect(k,v){const n=Number(v);const labels={atk_pct:'ATK',def_pct:'DEF',crit_flat:'CRIT',dodge_flat:'ESQUIVA',damage_pct:lang()==='es'?'Daño':'Damage',damage_reduction_pct:lang()==='es'?'Reducción de daño':'Damage reduction',skill_damage_pct:lang()==='es'?'Daño habilidad':'Skill damage',mana_cost_pct:lang()==='es'?'Costo maná':'Mana cost',proc_chance:lang()==='es'?'Prob. proc':'Proc chance',proc_damage_pct:lang()==='es'?'Daño proc':'Proc damage',execute_bonus_pct:lang()==='es'?'Daño ejecución':'Execute damage',incoming_damage_pct:lang()==='es'?'Daño recibido':'Incoming damage'};return `${labels[k]||k}: ${n>=0?'+':''}${Math.round(n*100)}%`}
function effectList(obj={}){const rows=Object.entries(obj).filter(([,v])=>Number(v)!==0);return rows.length?rows.map(([k,v])=>`<span>${esc(fmtEffect(k,v))}</span>`).join(''):'<span>—</span>'}
function setName(s){return lang()==='es'?(s.nameEs||s.name):s.name}
function specName(s){return lang()==='es'?(s.nameEs||s.name):s.name}
function activeSet(id){return state?.build?.sets?.find(s=>s.id===id)}
function bonusRow(label,data,on){return `<div class="p3-bonus ${on?'active':'locked'}"><strong>${label}</strong><span>${effectList(data)}</span><em>${on?'✓ '+t('active'):'○ '+t('locked')}</em></div>`}
function setCard(s,compact=false){const a=activeSet(s.id),pieces=Number(a?.pieces||0);return `<article class="p3-set-card ${a?'equipped':''}"><header><div><small>${s.classKey?classIcon(s.classKey):'🌐'} ${s.classKey||'UNIVERSAL'}</small><h3>${esc(setName(s))}</h3></div><b>${pieces}/6</b></header>${compact?'':`<div class="p3-bonuses">${bonusRow('2P',s.bonus2,pieces>=2)}${bonusRow('4P',s.bonus4,pieces>=4)}${bonusRow('6P',s.bonus6,pieces>=6)}</div>`}</article>`}
function buildHtml(){const b=state.build||{},sp=b.specialization;return `<section class="p3-build-summary"><div class="p3-hero"><div><span>${t('server')}</span><h2>${classIcon(state.character.class)} ${sp?esc(specName(sp)):t('build')}</h2><p>${sp?esc(lang()==='es'?(sp.descriptionEs||sp.description):sp.description):t('level10')}</p></div><b>Lv ${state.character.level}</b></div><div class="p3-effect-grid">${Object.entries(b.effects||{}).filter(([,v])=>Number(v)!==0).map(([k,v])=>`<span>${esc(fmtEffect(k,v))}</span>`).join('')||'<span>—</span>'}</div><div class="p3-capline"><span>CRIT cap ${Math.round(Number(b.caps?.crit||.75)*100)}%</span><span>DODGE cap ${Math.round(Number(b.caps?.dodge||.60)*100)}%</span><span>🛡️ ${t('pvp')}</span></div></section><section class="p3-current-sets">${(b.sets||[]).length?(b.sets||[]).map(x=>{const s=state.sets.find(z=>z.id===x.id)||x;return setCard(s,true)}).join(''):`<div class="p3-empty">${t('noSet')}</div>`}</section>`}
function setsHtml(){return `<div class="p3-note">🎮 ${t('noPay')}</div><div class="p3-set-grid">${(state.sets||[]).map(s=>setCard(s)).join('')}</div>`}
function specCard(s){const current=state.character.specialization===s.id,locked=state.character.level<Number(s.unlockLevel),first=!state.character.specialization,costGold=Math.min(2000,400+state.character.respecCount*200),costEss=Math.min(10,3+state.character.respecCount);return `<article class="p3-spec ${current?'current':''} ${locked?'locked':''}"><header><div><small>${classIcon(state.character.class)} ${state.character.class.toUpperCase()}</small><h3>${esc(specName(s))}</h3></div>${current?`<b>✓ ${t('current')}</b>`:''}</header><p>${esc(lang()==='es'?(s.descriptionEs||s.description):s.description)}</p><div class="p3-spec-effects">${effectList(s.statModifiers)}${effectList(s.passiveEffects)}</div><div class="p3-recommend">🧩 ${t('recommended')}: <b>${esc(setName(state.sets.find(x=>x.id===s.recommendedSetId)||{name:s.recommendedSetId,nameEs:s.recommendedSetId}))}</b></div><div class="p3-skills"><b>${t('skills')}</b>${(s.skills||[]).map(sk=>`<span>${sk.kind==='guard'?'🛡️':sk.kind==='execute'?'☠️':'⚔️'} ${esc(lang()==='es'?sk.nameEs:sk.name)} · Lv ${sk.minLevel} · ${sk.manaCost} MP</span>`).join('')}</div>${locked?`<button disabled>🔒 ${t('level10')}</button>`:current?'':`<button class="primary" data-p3-spec="${esc(s.id)}" ${busy?'disabled':''}>${first?t('choose'):t('change')}${first?` · ${t('freeFirst')}`:` · ${costGold} ${t('gold')} + ${costEss} ${t('essence')}`}</button>`}</article>`}
function specsHtml(){return `<div class="p3-note">⚙️ ${t('baseSkills')} ${state.character.specialization?`${t('respecCost')}: ${Math.min(2000,400+state.character.respecCount*200)} ${t('gold')} + ${Math.min(10,3+state.character.respecCount)} ${t('essence')}.`:t('freeFirst')}</div><div class="p3-spec-grid">${(state.specializations||[]).map(specCard).join('')}</div>`}
function equippedItem(slot){const id=state.equipment?.[slot];return state.inventory?.find(i=>i.id===id)}
function itemSetDetail(i){if(!i?.set)return'';const a=activeSet(i.setId),pieces=Number(a?.pieces||0);return `<div class="p3-item-set"><b>🧩 ${t('set')}: ${esc(lang()==='es'?i.set.nameEs:i.set.name)} · ${pieces}/6 ${t('pieces')}</b>${bonusRow('2P',i.set.bonuses.two,pieces>=2)}${bonusRow('4P',i.set.bonuses.four,pieces>=4)}${bonusRow('6P',i.set.bonuses.six,pieces>=6)}</div>`}
function equipmentHtml(){const slots=['weapon','helmet','armor','gloves','boots','ring'];const equipped=`<div class="p3-slots">${slots.map(sl=>{const i=equippedItem(sl);return `<article><span>${slotIcon(sl)}</span><div><small>${sl.toUpperCase()}</small><b>${i?esc(i.name):t('empty')}</b>${i?.set?`<em>🧩 ${esc(lang()==='es'?i.set.nameEs:i.set.name)}</em>`:''}</div>${i?`<button class="ghost" data-p3-unequip="${sl}">${t('unequip')}</button>`:''}</article>`}).join('')}</div>`;const candidates=(state.inventory||[]).filter(i=>i.slot&&i.set);return `${equipped}<h3 class="p3-section-title">${t('set')} · ${t('inspect')}</h3><div class="p3-item-grid">${candidates.map(i=>`<article class="p3-item"><header><div><small>${slotIcon(i.slot)} ${i.slot.toUpperCase()} · ${i.rarity}</small><h4>${esc(i.name)} ${i.enhancementLevel?`+${i.enhancementLevel}`:''}</h4></div><span>ATK ${i.atk} · DEF ${i.def}</span></header>${itemSetDetail(i)}<button data-p3-equip="${i.id}" ${state.equipment?.[i.slot]===i.id?'disabled':''}>${state.equipment?.[i.slot]===i.id?t('current'):t('equip')}</button></article>`).join('')||`<div class="p3-empty">${lang()==='es'?'Todavía no tienes piezas de set. Caen en combate, bosses y grietas.':'You do not have set pieces yet. They drop from combat, bosses and rifts.'}</div>`}</div>`}
function modalHtml(){const nav=[['build','⚙️ '+t('builds')],['sets','🧩 '+t('sets')],['specs','✦ '+t('specializations')],['equipment','🛡️ '+t('equipment')]];let body=view==='sets'?setsHtml():view==='specs'?specsHtml():view==='equipment'?equipmentHtml():buildHtml();return `<div class="p3-sheet"><header class="p3-modal-head"><div><span>NEXUS REALMS · PHASE 3</span><h2>${t('builds')} & ${t('specializations')}</h2></div><button data-p3-close>✕</button></header><nav class="p3-nav">${nav.map(([id,label])=>`<button data-p3-view="${id}" class="${view===id?'active':''}">${label}</button>`).join('')}</nav><main>${body}</main></div>`}
function renderModal(){const o=$('#p3-modal');if(!o)return;if(!state){o.innerHTML=`<div class="p3-sheet"><div class="p3-loading">${t('loading')}</div></div>`;return}o.innerHTML=modalHtml();bindModal()}
function bindModal(){document.querySelectorAll('[data-p3-view]').forEach(b=>b.onclick=()=>{view=b.dataset.p3View;renderModal()});$('[data-p3-close]')?.addEventListener('click',closeModal,{once:true});document.querySelectorAll('[data-p3-spec]').forEach(b=>b.onclick=async()=>{if(state.character.specialization&&!confirm(t('confirmChange')))return;await mutate('specialize',{id:b.dataset.p3Spec})});document.querySelectorAll('[data-p3-equip]').forEach(b=>b.onclick=()=>mutate('equip',{itemId:b.dataset.p3Equip}));document.querySelectorAll('[data-p3-unequip]').forEach(b=>b.onclick=()=>mutate('unequip',{slot:b.dataset.p3Unequip}))}
async function mutate(op,payload){if(busy)return;busy=true;renderModal();try{const r=await call(op,payload);state=r.state||await call('state');lastLoad=Date.now();renderModal();augmentInventory();renderLauncher();document.dispatchEvent(new CustomEvent('nexus:state',{detail:{source:'phase3'}}))}catch(e){alert(String(e.message||e))}finally{busy=false;renderModal()}}
function openModal(){let o=$('#p3-modal');if(!o){o=document.createElement('div');o.id='p3-modal';o.className='p3-overlay';document.body.append(o)}renderModal();load(true).catch(e=>{o.innerHTML=`<div class="p3-sheet"><div class="p3-error">⚠️ ${esc(e.message)}</div><button data-p3-close>${t('close')}</button></div>`;$('[data-p3-close]')?.addEventListener('click',closeModal,{once:true})})}
function closeModal(){$('#p3-modal')?.remove()}
function renderLauncher(){const h=document.querySelector('.header-actions');if(!h)return;let b=$('#p3-launcher');if(!b){b=document.createElement('button');b.id='p3-launcher';b.className='p3-launcher';b.onclick=openModal;h.prepend(b)}const sp=state?.build?.specialization,html=`⚙️ <span>${sp?esc(specName(sp)):t('openBuilds')}</span>`;if(b.innerHTML!==html)b.innerHTML=html;b.hidden=!state}
function isBag(){return /Mochila|Bag/i.test($('#panel .section-head h2')?.textContent||'')}
function augmentInventory(){if(!state||!isBag())return;const panel=$('#panel');if(!panel)return;const head=panel.querySelector('.section-head');let strip=panel.querySelector('#p3-build-strip');if(!strip){strip=document.createElement('button');strip.id='p3-build-strip';strip.className='p3-build-strip';strip.onclick=openModal;head?.insertAdjacentElement('afterend',strip)}const sp=state.build?.specialization,sets=state.build?.sets||[],stripHtml=`<span>⚙️ ${sp?esc(specName(sp)):(lang()==='es'?'Sin especialización':'No specialization')}</span><b>${sets.length?sets.map(s=>`${esc(lang()==='es'?s.nameEs:s.name)} ${s.pieces}/6`).join(' · '):t('noSet')}</b>`;if(strip.innerHTML!==stripHtml)strip.innerHTML=stripHtml;const eqList=panel.querySelector('.equipment-list');if(!eqList)return;let wrap=eqList.querySelector('.p3-extra-slots');if(!wrap){wrap=document.createElement('div');wrap.className='p3-extra-slots';eqList.append(wrap)}const extraHtml=['helmet','gloves'].map(sl=>{const i=equippedItem(sl);return `<div class="equipment-row"><div><span>${slotIcon(sl)}</span><div><small>${sl.toUpperCase()}</small><b>${i?esc(i.name):t('empty')}</b></div></div>${i?`<button data-p3-unequip="${sl}">${t('unequip')}</button>`:''}</div>`}).join('');if(wrap.innerHTML!==extraHtml){wrap.innerHTML=extraHtml;wrap.querySelectorAll('[data-p3-unequip]').forEach(b=>b.onclick=()=>mutate('unequip',{slot:b.dataset.p3Unequip}))}}

document.addEventListener('click',e=>{const b=e.target.closest?.('[data-equip]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();mutate('equip',{itemId:b.dataset.equip})},true);
document.addEventListener('nexus:panel-render',()=>{augmentInventory();renderLauncher()});
window.addEventListener('pageshow',()=>{load(true).catch(()=>{})});
supabase.auth.onAuthStateChange((_event,session)=>{if(session)load(true).catch(()=>{});else{state=null;renderLauncher();closeModal()}});
load(true).catch(()=>{});