import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(a,b)=>Math.max(0,Math.min(100,b?Number(a)/Number(b)*100:0));
let data=null,selected='hunter',busy=false,scheduled=false;
const lang=()=>localStorage.getItem('nexus-lang')||'es';
const txt={
 es:{title:'Árboles de profesiones',points:'Puntos de árbol',perLevel:'+2 por nivel de jugador',level:'Nivel',xp:'XP',hunt:'Contrato de Cacería',target:'Objetivo',zone:'Zona',progress:'Progreso',newHunt:'Nueva cacería',finishFirst:'Termina la cacería actual',rule:'Cazador de Grietas solo sube al derrotar el objetivo marcado asignado. Matar otros enemigos no da XP de esta profesión.',talent:'Talento',requires:'Requiere profesión nivel',prereq:'Requiere talento anterior',max:'MAX',spend:'Gastar 1 punto',noPoints:'Sin puntos disponibles',research:'Sistema inspirado en la idea de tareas de caza específicas: la especialización progresa por objetivos marcados, no por cualquier combate.'},
 en:{title:'Profession talent trees',points:'Tree points',perLevel:'+2 per player level',level:'Level',xp:'XP',hunt:'Hunt Contract',target:'Target',zone:'Zone',progress:'Progress',newHunt:'New hunt',finishFirst:'Finish current hunt',rule:'Rift Hunter levels only by defeating the currently assigned marked target. Other enemies grant no Hunter profession XP.',talent:'Talent',requires:'Requires profession level',prereq:'Requires previous talent',max:'MAX',spend:'Spend 1 point',noPoints:'No points available',research:'This system uses specific marked-hunt assignments: specialization progresses from assigned targets rather than generic combat.'}
};
const t=k=>txt[lang()]?.[k]??txt.es[k]??k;
const branchName=k=>({es:{prospector:'Prospección',mastery:'Maestría',harvest:'Recolección',catch:'Captura',weapons:'Armas',armor:'Armadura',tracking:'Rastreo',assault:'Combate'},en:{prospector:'Prospecting',mastery:'Mastery',harvest:'Harvest',catch:'Catch',weapons:'Weapons',armor:'Armor',tracking:'Tracking',assault:'Combat'}}[lang()]||{})[k]||k;
const pname=p=>lang()==='es'?(p.nameEs||p.name):p.name;
const tname=x=>lang()==='es'?(x.nameEs||x.name):x.name;
const tdesc=x=>lang()==='es'?(x.descriptionEs||x.description):x.description;

async function authHeaders(){const {data:s}=await supabase.auth.getSession();const token=s.session?.access_token;return token?{'content-type':'application/json','authorization':`Bearer ${token}`}:{'content-type':'application/json'};}
async function api(path,opt={}){const headers=await authHeaders();if(!headers.authorization)return null;const r=await fetch(path,{...opt,headers:{...headers,...(opt.headers||{})},cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||'Request failed');return j;}
async function refresh(){if(busy)return;try{const d=await api('/api/professions');if(d){data=d;renderIfVisible();markTarget();}}catch(e){console.warn('profession-engine',e.message)}}
async function act(action,payload={}){if(busy)return;busy=true;try{const d=await api('/api/profession-action',{method:'POST',body:JSON.stringify({action,payload})});if(d)data=d;renderIfVisible();markTarget();}catch(e){console.warn('profession-action',e.message)}finally{busy=false;}}

function ensureHunterSummary(grid){if(!data)return;let card=grid.querySelector('[data-hunter-summary]');const h=data.professions?.find(p=>p.key==='hunter');if(!h)return;if(!card){card=document.createElement('div');card.className='profession-card hunter-summary-card';card.dataset.hunterSummary='1';grid.append(card);}card.innerHTML=`<span>🎯</span><div><small>${esc(pname(h))}</small><h3>${t('level')} ${h.level}</h3></div><div class="progress"><i style="width:${pct(h.xp,h.nextXp)}%"></i></div><small>${h.xp}/${h.nextXp} XP · ${data.hunt?`${data.hunt.progress}/${data.hunt.target} ${lang()==='es'?'marcados':'marked'}`:(lang()==='es'?'sin contrato':'no contract')}</small>`;}
function ensureHost(){const grid=document.querySelector('.profession-grid');if(!grid)return null;ensureHunterSummary(grid);let host=document.querySelector('.profession-tree-v1');if(!host){host=document.createElement('section');host.className='profession-tree-v1';grid.after(host);}return host;}
function renderIfVisible(){const host=ensureHost();if(!host||!data)return;render(host);}
function render(host){const p=data.professions?.find(x=>x.key===selected)||data.professions?.[0];if(!p)return;const available=Number(data.talentPoints?.available||0);const talentById=new Map((p.talents||[]).map(x=>[x.id,x]));const branches=[...new Set((p.talents||[]).map(x=>x.branch))];const huntHtml=selected==='hunter'?renderHunt():'';
 host.innerHTML=`<div class="pt-head"><div><h3>🌿 ${t('title')}</h3><p>${t('perLevel')} · ${t('research')}</p></div><div class="pt-points"><b>${available}</b><small>${t('points')}</small></div></div><div class="pt-tabs">${data.professions.map(x=>`<button data-pt-prof="${x.key}" class="${selected===x.key?'active':''}">${x.icon} ${esc(pname(x))}</button>`).join('')}</div><div class="pt-prof-summary"><div><h4>${p.icon} ${esc(pname(p))}</h4><small>${t('level')} ${p.level}</small></div><strong>${p.xp}/${p.nextXp} XP</strong><div class="pt-xp"><div class="pt-meter"><i style="width:${pct(p.xp,p.nextXp)}%"></i></div></div></div>${huntHtml}<div class="pt-branches">${branches.map(branch=>`<div class="pt-branch"><h4>${esc(branchName(branch))}</h4>${(p.talents||[]).filter(x=>x.branch===branch).sort((a,b)=>a.tier-b.tier||a.position-b.position).map(x=>renderNode(x,p,talentById,available)).join('')}</div>`).join('')}</div><div class="pt-source-note">${selected==='hunter'?t('rule'):t('perLevel')}</div>`;
 host.querySelectorAll('[data-pt-prof]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.ptProf;render(host)}));
 host.querySelectorAll('[data-pt-talent]').forEach(b=>b.addEventListener('click',()=>act('allocateTalent',{talentId:b.dataset.ptTalent})));
 host.querySelector('[data-new-hunt]')?.addEventListener('click',()=>act('newHunt'));
}
function renderNode(x,p,talentById,available){const prereq=x.prerequisiteId?talentById.get(x.prerequisiteId):null,prereqOk=!x.prerequisiteId||Number(prereq?.rank||0)>0,levelOk=Number(p.level)>=Number(x.requiredProfessionLevel),maxed=Number(x.rank)>=Number(x.maxRank),can=available>0&&prereqOk&&levelOk&&!maxed;let lock='';if(!levelOk)lock=`${t('requires')} ${x.requiredProfessionLevel}`;else if(!prereqOk)lock=t('prereq');else if(available<=0&&!maxed)lock=t('noPoints');return `<div class="pt-node ${can?'':'locked'}"><div class="pt-node-icon">${esc(x.icon||'◆')}</div><div><b>${esc(tname(x))}</b><small>${esc(tdesc(x))}</small><div class="pt-node-rank">${t('talent')} ${x.rank}/${x.maxRank}</div>${lock?`<div class="pt-lock">${esc(lock)}</div>`:''}</div><button data-pt-talent="${x.id}" title="${t('spend')}" ${can?'':'disabled'}>${maxed?'✓':'+'}</button></div>`;}
function renderHunt(){const h=data.hunt;if(!h)return `<div class="pt-hunt"><div class="pt-hunt-title"><b>🎯 ${t('hunt')}</b><span>${t('rule')}</span></div><button data-new-hunt>${t('newHunt')}</button></div>`;return `<div class="pt-hunt"><div class="pt-hunt-title"><b>🎯 ${t('hunt')}</b><span>${h.boss?'👑 BOSS':`${t('level')} ${h.enemyLevel}`}</span></div><div class="pt-hunt-meta"><span>${t('target')}: <b>${esc(lang()==='es'?h.enemyNameEs:h.enemyName)}</b></span><span>${t('zone')}: <b>${esc(lang()==='es'?h.zoneNameEs:h.zoneName)}</b></span><span>${t('progress')}: <b>${h.progress}/${h.target}</b></span></div><div class="pt-meter"><i style="width:${pct(h.progress,h.target)}%"></i></div><p class="pt-rule">${t('rule')}</p></div>`;}
function markTarget(){document.querySelectorAll('.marked-hunt').forEach(x=>x.classList.remove('marked-hunt'));if(!data?.hunt)return;const btn=document.querySelector(`[data-enemy="${CSS.escape(data.hunt.enemyId)}"]`);btn?.closest('.enemy-row')?.classList.add('marked-hunt');}
function onDomChange(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;if(document.querySelector('.profession-grid'))renderIfVisible();markTarget();});}
const observer=new MutationObserver(onDomChange);observer.observe(document.documentElement,{subtree:true,childList:true});
document.addEventListener('click',e=>{if(e.target?.closest?.('[data-enemy]'))setTimeout(refresh,900)},true);
window.addEventListener('focus',refresh);window.addEventListener('nexus-refresh-professions',refresh);
supabase.auth.onAuthStateChange((_event,session)=>{if(session)setTimeout(refresh,150);else data=null;});
setInterval(()=>{if(document.visibilityState==='visible')refresh()},6000);
setTimeout(refresh,450);