const API='/api/v1';
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('cfs_csrf='))?.split('=')[1]||''}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};if((opt.method||'GET').toUpperCase()!=='GET')opt.headers['X-CSRF-Token']=csrf();const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail?.message||`HTTP ${r.status}`);return d}
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function loadCreatorGames(isCreator){const root=document.getElementById('myGames');if(!isCreator){root.innerHTML='<p class="muted">Tu cuenta todavía no es Creator. <a href="/creator.html">Activar Creator Free</a></p>';return}try{const d=await api('/creator/games');root.innerHTML=d.games.length?d.games.map(g=>`<div class="profile-game"><div><b>${esc(g.title)}</b><small>${esc(g.status)} · ${esc(g.visibility)}</small></div>${g.status==='PUBLISHED'?`<a class="ghost small" href="/game.html?slug=${encodeURIComponent(g.slug)}">Abrir</a>`:`<a class="ghost small" href="/creator.html#games">Gestionar</a>`}</div>`).join(''):'<p class="muted">Todavía no has creado juegos.</p>'}catch(e){root.textContent='No se pudieron cargar tus juegos.'}}
async function init(){try{const d=await api('/me');const u=d.user;accountState.innerHTML=`<div class="identity"><div class="avatar">${esc(u.display_name.slice(0,2).toUpperCase())}</div><div><span class="eyebrow">${esc(u.role.replace('_',' ').toUpperCase())}</span><h2>${esc(u.display_name)}</h2><p>${esc(u.email)}</p></div></div><div class="identity-actions">${d.creator?`<span class="status live">${esc(d.creator.plan_id.toUpperCase())}</span>`:'<a class="ghost small" href="/creator.html">Convertirme en creador</a>'}</div>`;await loadCreatorGames(Boolean(d.creator))}catch(e){accountState.innerHTML='<h2>Sesión no iniciada</h2><p>Inicia sesión desde el portal para acceder a tu cuenta.</p><a class="primary" href="/">Volver al portal</a>';myGames.textContent='—';document.getElementById('deleteAccount').disabled=true}}
logout.onclick=async()=>{try{await api('/auth/logout',{method:'POST'});location.href='/'}catch(e){toast(e.message)}};
logoutAll.onclick=async()=>{try{await api('/auth/logout-all',{method:'POST'});location.href='/'}catch(e){toast(e.message)}};
deleteAccount.onclick=async()=>{const password=deletePassword.value;if(!password){toast('Introduce tu contraseña');return}if(!confirm('Esta acción eliminará permanentemente tu cuenta, juegos y partidas. ¿Continuar?'))return;try{deleteAccount.disabled=true;await api('/account',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,confirmation:'DELETE ACCOUNT'})});location.href='/?account=deleted'}catch(e){toast(e.message);deleteAccount.disabled=false}};
init();
