import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const pct=(a,b)=>Math.max(0,Math.min(100,b?Number(a)/Number(b)*100:0));
let expanded=false,last=null,loading=false,lastRefresh=0;

function lang(){return localStorage.getItem('nexus-lang')||'es'}
const L={
 es:{title:'Progresión y combate automático',details:'Detalles',hide:'Ocultar',xp:'Experiencia',points:'Puntos libres',tactic:'Táctica',smart:'Inteligente',balanced:'Equilibrada',aggressive:'Agresiva',defensive:'Defensiva',atk:'ATQ',def:'DEF',crit:'CRÍT',dodge:'ESQ',strength:'Fuerza',vitality:'Vitalidad',agility:'Agilidad',intelligence:'Inteligencia',luck:'Suerte',skills:'Habilidades automáticas',rules:'Al subir de nivel ganas crecimiento automático según tu clase + 2 puntos para repartir. El combate usa tus atributos, equipo, maná, crítico, esquiva y habilidades automáticamente.',strHelp:'Aumenta el daño físico.',vitHelp:'Aumenta defensa; cada punto manual da +3 Vida máxima.',agiHelp:'Aumenta crítico y esquiva; clave para Arquero/Asesino.',intHelp:'Aumenta poder de habilidades; cada punto manual da +2 Maná máximo.',luckHelp:'Mejora crítico y probabilidad de mejor botín.',mana:'Maná',level:'Nivel',cooldown:'Enfriamiento',turns:'turnos',autoAI:'IA automática',damage:'Daño',guard:'Defensa',execute:'Ejecución',aiDamage:'La IA compara maná, enfriamiento, táctica, jefe y turno antes de lanzarla.',aiGuard:'La IA la prioriza cuando tu vida baja o usas una táctica defensiva.',aiExecute:'La IA la reserva para rematar enemigos cuando su vida entra en el umbral de ejecución.',aiAggressive:'Con táctica Agresiva prioriza las habilidades de mayor daño disponibles.',aiDefensive:'Con táctica Defensiva conserva maná y favorece supervivencia.',aiSmart:'Con táctica Inteligente adapta cada habilidad al estado de la pelea.',aiBalanced:'Con táctica Equilibrada alterna ataques básicos y habilidades para no vaciar el maná.'},
 en:{title:'Progression & automatic combat',details:'Details',hide:'Hide',xp:'Experience',points:'Free points',tactic:'Tactic',smart:'Smart',balanced:'Balanced',aggressive:'Aggressive',defensive:'Defensive',atk:'ATK',def:'DEF',crit:'CRIT',dodge:'DODGE',strength:'Strength',vitality:'Vitality',agility:'Agility',intelligence:'Intelligence',luck:'Luck',skills:'Automatic skills',rules:'Each level grants class-based automatic growth + 2 points to spend. Auto combat uses your attributes, gear, mana, crit, dodge and skills.',strHelp:'Raises physical damage.',vitHelp:'Raises defense; manual points also grant +3 max Health.',agiHelp:'Raises crit and dodge; especially strong for Archer/Assassin.',intHelp:'Raises skill power; manual points also grant +2 max Mana.',luckHelp:'Raises crit and better-loot chance.',mana:'Mana',level:'Level',cooldown:'Cooldown',turns:'turns',autoAI:'Auto AI',damage:'Damage',guard:'Defense',execute:'Execute',aiDamage:'AI checks mana, cooldown, tactic, boss status and turn before casting it.',aiGuard:'AI prioritizes it when your health is low or you use a defensive tactic.',aiExecute:'AI saves it to finish enemies once they enter the execution health threshold.',aiAggressive:'Aggressive tactic prioritizes the strongest available damage skills.',aiDefensive:'Defensive tactic conserves mana and favors survival.',aiSmart:'Smart tactic adapts each skill to the current fight state.',aiBalanced:'Balanced tactic alternates basic attacks and skills to avoid draining mana.'}
};
const t=k=>L[lang()]?.[k]??k;

async function sessionHeaders(){const {data}=await supabase.auth.getSession();const token=data.session?.access_token;return token?{'content-type':'application/json','authorization':`Bearer ${token}`}:{'content-type':'application/json'};}
async function getProgress(){const headers=await sessionHeaders();if(!headers.authorization)return null;const r=await fetch('/api/state',{headers,cache:'no-store'});if(!r.ok)return null;const j=await r.json();return j?.player?{player:j.player}:null;}
async function act(action,payload){const headers=await sessionHeaders();const r=await fetch('/api/action',{method:'POST',headers,body:JSON.stringify({action,payload}),cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok||j.error)throw new Error(j.error||'Request failed');return j;}
function ensureHost(){let el=document.querySelector('#progression-v2');if(el)return el;el=document.createElement('section');el.id='progression-v2';el.hidden=true;const hud=document.querySelector('#hud');if(hud)hud.after(el);else document.querySelector('main')?.before(el);return el;}
function skillLabel(s){return lang()==='es'?(s.nameEs||s.name):s.name}
function skillKind(s){return s.kind==='guard'?t('guard'):s.kind==='execute'?t('execute'):t('damage')}
function skillIcon(s){return s.kind==='guard'?'🛡️':s.kind==='execute'?'☠️':'✨'}
function skillRule(s,p){if(s.kind==='guard')return t('aiGuard');if(s.kind==='execute')return `${t('aiExecute')} ${s.executeThreshold?`(${Math.round(Number(s.executeThreshold)*100)}%)`:''}`;if(p.tactic==='aggressive')return t('aiAggressive');if(p.tactic==='defensive')return t('aiDefensive');if(p.tactic==='balanced')return t('aiBalanced');return t('aiSmart');}
function renderSkill(s,p){const mult=Number(s.multiplier||1).toFixed(2),cd=Number(s.cooldownTurns||0),mana=Number(s.manaCost||0);return `<article class="pv2-skill"><div class="pv2-skill-head"><span>${skillIcon(s)}</span><div><b>${esc(skillLabel(s))}</b><small>${skillKind(s)} · ${t('level')} ${Number(s.minLevel||1)}</small></div><em>${t('autoAI')}</em></div><div class="pv2-skill-stats"><span>${mana} ${t('mana')}</span><span>x${mult}</span><span>${t('cooldown')} ${cd} ${t('turns')}</span></div><p>${esc(skillRule(s,p))}</p></article>`;}
function render(){const host=ensureHost();if(!last?.player){host.hidden=true;return;}host.hidden=false;const p=last.player,a=p.attributes||{},s=p.combatStats||{},points=Number(p.unspentPoints||0),xpMax=Number(p.xpToNext||Math.max(100,p.level*100));const tactics=['smart','balanced','aggressive','defensive'];const attrs=[['strength','💪',t('strHelp')],['vitality','❤️',t('vitHelp')],['agility','💨',t('agiHelp')],['intelligence','🔮',t('intHelp')],['luck','🍀',t('luckHelp')]];
 host.innerHTML=`<div class="pv2-shell"><div class="pv2-head"><div><span class="pv2-kicker">AUTO RPG</span><b>⚙️ ${t('title')}</b></div><button class="pv2-toggle" data-pv2-toggle>${expanded?t('hide'):t('details')}</button></div><div class="pv2-xp"><div><span>${t('level')} ${p.level}</span><strong>${p.xp}/${xpMax} XP</strong></div><div class="pv2-meter"><i style="width:${pct(p.xp,xpMax)}%"></i></div></div><div class="pv2-summary"><span>${t('atk')} <b>${s.atk??0}</b></span><span>${t('def')} <b>${s.def??0}</b></span><span>${t('crit')} <b>${Math.round(Number(s.crit||0)*100)}%</b></span><span>${t('dodge')} <b>${Math.round(Number(s.dodge||0)*100)}%</b></span><span>${t('points')} <b>${points}</b></span></div><div class="pv2-tactics">${tactics.map(x=>`<button data-pv2-tactic="${x}" class="${p.tactic===x?'active':''}">${t(x)}</button>`).join('')}</div>${expanded?`<div class="pv2-detail"><p class="pv2-rules">${t('rules')}</p><div class="pv2-attrs">${attrs.map(([k,ic,help])=>`<div class="pv2-attr"><span>${ic}</span><div><b>${t(k)} ${a[k]??0}</b><small>${help}</small></div><button data-pv2-stat="${k}" ${points<=0?'disabled':''}>+1</button></div>`).join('')}</div><div class="pv2-skills"><div class="pv2-skills-title"><b>✨ ${t('skills')}</b><span>🤖 ${t(p.tactic||'smart')}</span></div><div class="pv2-skills-grid">${(p.skills||[]).map(sk=>renderSkill(sk,p)).join('')||'<span>—</span>'}</div></div></div>`:''}</div>`;
 bind();
}
function applyActionState(j){if(j?.player){last={player:j.player};lastRefresh=Date.now();render();}}
function bind(){document.querySelector('[data-pv2-toggle]')?.addEventListener('click',()=>{expanded=!expanded;render()});document.querySelectorAll('[data-pv2-tactic]').forEach(b=>b.addEventListener('click',async()=>{if(loading)return;loading=true;try{applyActionState(await act('setTactic',{tactic:b.dataset.pv2Tactic}));}catch(e){console.warn(e)}finally{loading=false}}));document.querySelectorAll('[data-pv2-stat]').forEach(b=>b.addEventListener('click',async()=>{if(loading)return;loading=true;try{applyActionState(await act('allocateStat',{stat:b.dataset.pv2Stat}));}catch(e){console.warn(e)}finally{loading=false}}));}
async function refresh({force=false}={}){if(!force&&Date.now()-lastRefresh<15000)return;try{const d=await getProgress();if(d){last=d;lastRefresh=Date.now();render();}}catch{}}

supabase.auth.onAuthStateChange((_event,session)=>{if(session)setTimeout(()=>refresh({force:true}),250);else{last=null;render();}});
window.addEventListener('focus',()=>refresh());
window.addEventListener('nexus-refresh-progression',()=>refresh({force:true}));
document.addEventListener('click',e=>{if(e.target?.closest?.('[data-enemy]'))setTimeout(()=>refresh({force:true}),950)},true);
setInterval(()=>{if(document.visibilityState==='visible')refresh()},45000);
setTimeout(()=>refresh({force:true}),500);