const API='/api/v1';
const state={config:null,user:null,pf:null,vault:{owned:[],purchased:[]},vaultTab:'owned',market:[],editingId:null,checkout:null,paymentMode:'MOCK',methods:[],selectedMethod:null,currentOrder:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const csrf=()=>document.cookie.split('; ').find(x=>x.startsWith('cfs_csrf='))?.split('=')[1]||'';
function toast(message,error=false){const el=$('toast');el.textContent=message;el.className='toast show'+(error?' error':'');clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',2800)}
async function api(path,opt={}){opt.credentials='same-origin';opt.headers={...(opt.headers||{})};const method=(opt.method||'GET').toUpperCase();if(method!=='GET'&&method!=='HEAD')opt.headers['X-CSRF-Token']=csrf();const r=await fetch(API+path,opt);let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail?.message||data.detail?.error_code||`HTTP ${r.status}`);return data}
function jsonBody(value){return {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}}
function putBody(value){return {method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}}
function money(v){const n=Number(v||0);return Number.isFinite(n)?`$${n.toFixed(2)}`:'$0.00'}
function feeLabel(bps){return `${(Number(bps||0)/100).toFixed(Number(bps||0)%100?2:0)}%`}
function showSection(id){if(['vault','create','earnings'].includes(id)&&!state.user){$('authPanel').classList.remove('hidden');$('authPanel').scrollIntoView({behavior:'smooth',block:'center'});return}document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})}
document.addEventListener('click',e=>{const section=e.target.closest('[data-section]')?.dataset.section;if(section)showSection(section);const close=e.target.closest('[data-close]')?.dataset.close;if(close)$(close)?.close()});

async function init(){
  try{state.config=await api('/prompt-factory/config');hydrateFilters();renderPlans()}catch(e){toast('No se pudo cargar Prompt Factory',true)}
  await loadMarketplace();
  try{const me=await api('/me');state.user=me.user;$('accountBadge').textContent=me.user.display_name;document.querySelectorAll('.auth-only').forEach(x=>x.classList.remove('hidden'));$('authPanel').classList.add('hidden');await api('/prompt-factory/reconcile',{method:'POST'}).catch(()=>{});await Promise.all([loadPfMe(),loadVault(),loadDashboard()])}catch(e){state.user=null;$('authPanel').classList.remove('hidden');document.querySelectorAll('.auth-only').forEach(x=>x.classList.add('hidden'))}
  bindForms();
  handleSearchParams();
}
function hydrateFilters(){const categories=state.config?.categories||[];$('categoryFilter').innerHTML='<option value="">Todas las categorías</option>'+categories.map(x=>`<option>${esc(x)}</option>`).join('');$('promptCategory').innerHTML=categories.map(x=>`<option ${x==='OTHER'?'selected':''}>${esc(x)}</option>`).join('')}
async function loadPfMe(){try{state.pf=await api('/prompt-factory/me');$('heroPlan').textContent=String(state.pf.plan.plan_id||'free').toUpperCase();$('heroFee').textContent=feeLabel(state.pf.plan.commission_bps);const s=state.pf.storage;$('heroStorage').textContent=s.limit===null?`${s.used} / ∞`:`${s.used} / ${s.limit}`;$('storageMeter').textContent=s.limit===null?`${s.used} guardados · ilimitado`:`${s.used} / ${s.limit} prompts · ${s.remaining} libres`;renderPlans()}catch(e){}}
async function loadMarketplace(){try{const q=encodeURIComponent($('marketSearch')?.value||'');const category=encodeURIComponent($('categoryFilter')?.value||'');const sort=encodeURIComponent($('sortFilter')?.value||'trending');const d=await api(`/prompt-factory/marketplace?q=${q}&category=${category}&sort=${sort}&limit=60`);state.market=d.listings||[];$('heroListings').textContent=state.market.length;renderMarketplace()}catch(e){$('marketGrid').innerHTML='<div class="empty-card">No se pudo cargar el marketplace.</div>'}}
function renderMarketplace(){const grid=$('marketGrid');if(!state.market.length){grid.innerHTML='<div class="empty-card">Todavía no hay prompts publicados con estos filtros.</div>';return}grid.innerHTML=state.market.map(x=>`<article class="prompt-card"><div class="card-top"><span class="category">${esc(x.category)}</span><span class="price">${Number(x.price_usd)===0?'FREE':money(x.price_usd)}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description||x.preview_text||'')}</p><div class="tags">${(x.ai_models||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}${(x.tags||[]).slice(0,3).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div><div class="card-meta"><span>${esc(x.creator_name)}</span><span class="rating">★ ${Number(x.rating_avg||0).toFixed(1)} · ${Number(x.sales_count||0)} ventas</span></div><div class="card-actions"><button class="ghost tiny" data-open-listing="${esc(x.slug)}">VER</button><button class="primary tiny" data-buy-listing="${esc(x.listing_id)}">${Number(x.price_usd)===0?'OBTENER':'COMPRAR'}</button><button class="ghost tiny auth-required" data-favorite="${esc(x.prompt_id)}">☆</button></div></article>`).join('')}

let searchTimer;
$('marketSearch')?.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(loadMarketplace,300)});$('categoryFilter')?.addEventListener('change',loadMarketplace);$('sortFilter')?.addEventListener('change',loadMarketplace);
$('marketGrid')?.addEventListener('click',async e=>{const slug=e.target.closest('[data-open-listing]')?.dataset.openListing;if(slug)return openListing(slug);const lid=e.target.closest('[data-buy-listing]')?.dataset.buyListing;if(lid)return buyListing(lid);const pid=e.target.closest('[data-favorite]')?.dataset.favorite;if(pid){if(!state.user)return showSection('vault');try{const r=await api(`/prompt-factory/prompts/${encodeURIComponent(pid)}/favorite`,{method:'POST'});toast(r.favorite?'Guardado en favoritos':'Eliminado de favoritos')}catch(err){toast(err.message,true)}}});
async function openListing(slug){try{const d=await api(`/prompt-factory/listings/${encodeURIComponent(slug)}`);const x=d.listing;$('listingContent').innerHTML=`<span class="eyebrow">${esc(x.category)} · ${esc(x.license_type)} LICENSE</span><h2 class="listing-title">${esc(x.title)}</h2><div class="card-meta"><span>por ${esc(x.creator_name)}</span><span class="rating">★ ${Number(x.rating_avg||0).toFixed(1)} · ${Number(x.sales_count||0)} ventas</span></div><p>${esc(x.description)}</p><h3>Vista previa</h3><div class="listing-preview">${esc(x.preview_text||'El autor no añadió una vista previa.')}</div>${(x.examples||[]).length?`<h3>Ejemplos</h3><div class="tags">${x.examples.map(v=>`<span class="tag">${esc(v)}</span>`).join('')}</div>`:''}<div class="hero-actions"><button class="primary" data-dialog-buy="${esc(x.listing_id)}">${Number(x.price_usd)===0?'OBTENER GRATIS':`COMPRAR · ${money(x.price_usd)}`}</button></div><h3>Reseñas verificadas</h3><div>${(d.reviews||[]).length?d.reviews.map(r=>`<div class="review-item"><b>${esc(r.display_name)} · <span class="rating">${'★'.repeat(Number(r.rating))}</span></b><p>${esc(r.comment)}</p></div>`).join(''):'<p class="muted">Aún no hay reseñas.</p>'}</div>`;$('listingDialog').showModal();$('listingContent').querySelector('[data-dialog-buy]')?.addEventListener('click',()=>buyListing(x.listing_id))}catch(e){toast(e.message,true)}}
async function buyListing(listingId){if(!state.user){$('authPanel').classList.remove('hidden');$('authPanel').scrollIntoView({behavior:'smooth'});return}try{const d=await api(`/prompt-factory/listings/${encodeURIComponent(listingId)}/prepare-checkout`,{method:'POST'});if(d.already_owned){toast('Este prompt ya está en tu Vault');await loadVault();return}if(d.free){await api(`/prompt-factory/listings/${encodeURIComponent(listingId)}/acquire-free`,{method:'POST'});toast('Prompt añadido a tu Vault');await Promise.all([loadVault(),loadMarketplace()]);$('listingDialog').close();showSection('vault');return}await openCheckout({productId:d.product_id,title:'Comprar prompt',kind:'listing'})}catch(e){toast(e.message,true)}}

async function loadVault(){try{state.vault=await api('/prompt-factory/vault');renderVault()}catch(e){$('vaultGrid').innerHTML='<div class="empty-card">No se pudo cargar tu Vault.</div>'}}
function renderVault(){const items=state.vault[state.vaultTab]||[];const grid=$('vaultGrid');if(!items.length){grid.innerHTML=`<div class="empty-card">${state.vaultTab==='owned'?'Tu Vault está vacío. Crea tu primer prompt.':'Aún no has comprado prompts.'}</div>`;return}grid.innerHTML=items.map(x=>`<article class="prompt-card"><div class="card-top"><span class="category">${esc(x.category)}</span><span class="tag">${state.vaultTab==='owned'?'OWNER':esc(x.purchased_license||'PURCHASED')}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="tags">${(x.ai_models||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="card-actions"><button class="primary tiny" data-open-prompt="${esc(x.prompt_id)}">ABRIR</button>${state.vaultTab==='owned'?`<button class="ghost tiny" data-edit-prompt="${esc(x.prompt_id)}">EDITAR</button><button class="ghost tiny" data-sell-prompt="${esc(x.prompt_id)}">VENDER</button><button class="ghost tiny" data-duplicate-prompt="${esc(x.prompt_id)}">DUPLICAR</button><button class="ghost tiny" data-archive-prompt="${esc(x.prompt_id)}">ARCHIVAR</button>`:`<button class="ghost tiny" data-review-purchase="${esc(x.purchase_id)}">RESEÑA</button>`}</div></article>`).join('')}
document.querySelectorAll('[data-vault-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-vault-tab]').forEach(x=>x.classList.toggle('active',x===b));state.vaultTab=b.dataset.vaultTab;renderVault()}));
$('vaultGrid')?.addEventListener('click',async e=>{const pid=e.target.closest('[data-open-prompt]')?.dataset.openPrompt;if(pid)return openPrompt(pid);const edit=e.target.closest('[data-edit-prompt]')?.dataset.editPrompt;if(edit)return editPrompt(edit);const sell=e.target.closest('[data-sell-prompt]')?.dataset.sellPrompt;if(sell){$('sellPromptId').value=sell;$('sellDialog').showModal();return}const duplicate=e.target.closest('[data-duplicate-prompt]')?.dataset.duplicatePrompt;if(duplicate){try{await api(`/prompt-factory/prompts/${encodeURIComponent(duplicate)}/duplicate`,{method:'POST'});toast('Prompt duplicado');await Promise.all([loadVault(),loadPfMe()])}catch(err){toast(err.message,true)}return}const archive=e.target.closest('[data-archive-prompt]')?.dataset.archivePrompt;if(archive){if(!confirm('¿Archivar este prompt y retirar su listing?'))return;try{await api(`/prompt-factory/prompts/${encodeURIComponent(archive)}`,{method:'DELETE'});toast('Prompt archivado');await Promise.all([loadVault(),loadPfMe(),loadMarketplace()])}catch(err){toast(err.message,true)}return}const review=e.target.closest('[data-review-purchase]')?.dataset.reviewPurchase;if(review){$('reviewPurchaseId').value=review;$('reviewDialog').showModal()}});

async function openPrompt(pid){try{const d=await api(`/prompt-factory/prompts/${encodeURIComponent(pid)}`);const p=d.prompt;let variableHtml='';if((p.variables||[]).length){variableHtml=`<h3>Variables</h3><div class="variable-grid">${p.variables.map(v=>{const name=String(v.name||'').trim();return `<label>${esc(v.label||name)}<input data-var-name="${esc(name)}" placeholder="${esc(name)}"></label>`}).join('')}</div><button class="ghost" id="renderPromptBtn">GENERAR CON VARIABLES</button><div id="renderedBox"></div>`}$('promptContent').innerHTML=`<span class="eyebrow">${esc(p.category)} · ${d.owned?'TU PROMPT':'COMPRADO'}</span><h2 class="listing-title">${esc(p.title)}</h2><p>${esc(p.description)}</p><h3>Prompt</h3><pre class="prompt-code" id="currentPromptCode">${esc(p.prompt_text)}</pre>${p.system_instructions?`<h3>System instructions</h3><pre class="prompt-code">${esc(p.system_instructions)}</pre>`:''}${variableHtml}<div id="versionBox"></div>`;$('promptDialog').showModal();$('renderPromptBtn')?.addEventListener('click',async()=>{const values={};$('promptContent').querySelectorAll('[data-var-name]').forEach(i=>values[i.dataset.varName]=i.value);try{const r=await api(`/prompt-factory/prompts/${encodeURIComponent(pid)}/render`,jsonBody({values}));$('renderedBox').innerHTML=`<h3>Resultado</h3><pre class="prompt-code">${esc(r.rendered_prompt)}</pre>`}catch(err){toast(err.message,true)}});if(d.owned)await loadVersions(pid)}catch(e){toast(e.message,true)}}
async function loadVersions(pid){try{const d=await api(`/prompt-factory/prompts/${encodeURIComponent(pid)}/versions`);$('versionBox').innerHTML=`<h3>Versiones</h3>${d.versions.map(v=>`<div class="version-row"><span><b>v${v.version_number}</b> · ${esc(v.changelog||'Sin nota')}</span><button class="ghost tiny" data-restore-version="${v.version_number}">RESTAURAR</button></div>`).join('')}`;$('versionBox').querySelectorAll('[data-restore-version]').forEach(b=>b.addEventListener('click',async()=>{try{await api(`/prompt-factory/prompts/${encodeURIComponent(pid)}/versions/${b.dataset.restoreVersion}/restore`,{method:'POST'});toast('Versión restaurada');await Promise.all([openPrompt(pid),loadVault()])}catch(err){toast(err.message,true)}}))}catch(e){}}
async function editPrompt(pid){const p=state.vault.owned.find(x=>x.prompt_id===pid);if(!p)return;state.editingId=pid;$('editorTitle').textContent='Editar prompt';$('cancelEdit').classList.remove('hidden');$('promptTitle').value=p.title||'';$('promptDescription').value=p.description||'';$('promptText').value=p.prompt_text||'';$('systemInstructions').value=p.system_instructions||'';$('promptCategory').value=p.category||'OTHER';$('aiModels').value=(p.ai_models||[]).join(', ');$('promptTags').value=(p.tags||[]).join(', ');$('promptLanguage').value=p.language||'es';$('promptDifficulty').value=p.difficulty||'INTERMEDIATE';$('promptVariables').value=(p.variables||[]).map(v=>v.name||'').filter(Boolean).join(', ');$('promptChangelog').value='';$('savePromptBtn').textContent='GUARDAR NUEVA VERSIÓN';showSection('create')}
function resetEditor(){state.editingId=null;$('promptForm').reset();$('promptLanguage').value='es';$('promptDifficulty').value='INTERMEDIATE';$('editorTitle').textContent='Crear un nuevo prompt';$('savePromptBtn').textContent='GUARDAR EN VAULT';$('cancelEdit').classList.add('hidden');$('editorStatus').textContent=''}
$('cancelEdit')?.addEventListener('click',resetEditor);

function bindForms(){
 $('loginForm').addEventListener('submit',async e=>{e.preventDefault();try{await api('/auth/login',jsonBody({email:$('loginEmail').value.trim(),password:$('loginPassword').value}));toast('Sesión iniciada');location.reload()}catch(err){toast(err.message,true)}});
 $('promptForm').addEventListener('submit',async e=>{e.preventDefault();const variables=$('promptVariables').value.split(',').map(x=>x.trim()).filter(Boolean).slice(0,50).map(name=>({name,label:name.replaceAll('_',' ')}));const payload={title:$('promptTitle').value.trim(),description:$('promptDescription').value.trim(),prompt_text:$('promptText').value,system_instructions:$('systemInstructions').value,category:$('promptCategory').value,ai_models:$('aiModels').value.split(',').map(x=>x.trim()).filter(Boolean),tags:$('promptTags').value.split(',').map(x=>x.trim()).filter(Boolean),language:$('promptLanguage').value.trim()||'es',difficulty:$('promptDifficulty').value,variables,changelog:$('promptChangelog').value.trim()};try{$('savePromptBtn').disabled=true;$('editorStatus').textContent='Guardando…';if(state.editingId)await api(`/prompt-factory/prompts/${encodeURIComponent(state.editingId)}`,putBody(payload));else await api('/prompt-factory/prompts',jsonBody(payload));toast(state.editingId?'Nueva versión guardada':'Prompt guardado');resetEditor();await Promise.all([loadVault(),loadPfMe()]);showSection('vault')}catch(err){$('editorStatus').textContent=err.message;toast(err.message,true)}finally{$('savePromptBtn').disabled=false}});
 $('sellForm').addEventListener('submit',async e=>{e.preventDefault();const pricing=$('sellPricing').value;const payload={price_usd:pricing==='FREE'?'0.00':String(Number($('sellPrice').value||0).toFixed(2)),pricing_model:pricing,license_type:$('sellLicense').value,preview_text:$('sellPreview').value.trim(),examples:$('sellExamples').value.split('\n').map(x=>x.trim()).filter(Boolean)};try{const r=await api(`/prompt-factory/prompts/${encodeURIComponent($('sellPromptId').value)}/sell`,jsonBody(payload));toast(r.listing.status==='PUBLISHED'?'Publicado en marketplace':'Enviado a revisión');$('sellDialog').close();await Promise.all([loadMarketplace(),loadDashboard()])}catch(err){toast(err.message,true)}});
 $('sellPricing').addEventListener('change',()=>{$('sellPrice').disabled=$('sellPricing').value==='FREE'});
 $('reviewForm').addEventListener('submit',async e=>{e.preventDefault();try{await api(`/prompt-factory/purchases/${encodeURIComponent($('reviewPurchaseId').value)}/review`,jsonBody({rating:Number($('reviewRating').value),comment:$('reviewComment').value.trim()}));toast('Reseña publicada');$('reviewDialog').close();await loadMarketplace()}catch(err){toast(err.message,true)}})
}

async function loadDashboard(){try{const d=await api('/prompt-factory/creator/dashboard');const b=d.balance,s=d.sales;$('earningStats').innerHTML=`<div class="metric"><strong>${money(b.available_usd)}</strong><span>Saldo disponible</span></div><div class="metric"><strong>${money(s.gross)}</strong><span>Ventas brutas</span></div><div class="metric"><strong>${money(s.net)}</strong><span>Ganancia neta</span></div><div class="metric"><strong>${money(s.fees)}</strong><span>Comisiones CFS</span></div>`;$('topPrompts').innerHTML=(d.top_prompts||[]).length?d.top_prompts.map(x=>`<div class="data-row"><b>${esc(x.title)}</b><span>${money(x.price_usd)}</span><span>${x.sales_count} ventas</span><span>★ ${Number(x.rating_avg||0).toFixed(1)}</span></div>`).join(''):'<p class="muted">Todavía no tienes ventas.</p>'}catch(e){}}
function renderPlans(){if(!state.config)return;const current=state.pf?.plan?.plan_id||'free';$('planGrid').innerHTML=(state.config.plans||[]).map(p=>`<article class="plan-card ${p.plan_id==='creator'?'recommended':''}"><span class="eyebrow">${p.plan_id===current?'TU PLAN':p.plan_id.toUpperCase()}</span><h3>${esc(p.label)}</h3><div class="plan-price">${Number(p.price_usd)===0?'FREE':money(p.price_usd)}${Number(p.price_usd)>0?'<small> / 30 días</small>':''}</div><div class="fee">Comisión marketplace: ${feeLabel(p.commission_bps)}</div><ul><li>${p.max_prompts===null?'Prompts ilimitados':`Hasta ${p.max_prompts} prompts`}</li>${(p.features||[]).slice(0,4).map(f=>`<li>${esc(String(f).replaceAll('_',' '))}</li>`).join('')}</ul>${p.plan_id==='free'?'<button class="ghost full" disabled>INCLUIDO</button>':`<button class="primary full" data-buy-plan="${esc(p.plan_id)}">${p.plan_id===current?'RENOVAR 30 DÍAS':'ELEGIR PLAN'}</button>`}</article>`).join('');$('addonGrid').innerHTML=(state.config.storage_addons||[]).map(a=>`<article class="addon-card"><strong>${esc(a.label)}</strong><span>${money(a.price_usd)}</span><button class="ghost full" data-buy-addon="${esc(a.addon_id)}">AÑADIR CAPACIDAD</button></article>`).join('');document.querySelectorAll('[data-buy-plan]').forEach(b=>b.addEventListener('click',()=>buyPlan(b.dataset.buyPlan)));document.querySelectorAll('[data-buy-addon]').forEach(b=>b.addEventListener('click',()=>buyAddon(b.dataset.buyAddon)))}
async function buyPlan(planId){if(!state.user)return showSection('vault');try{const d=await api(`/prompt-factory/plans/${encodeURIComponent(planId)}/prepare-checkout`,{method:'POST'});await openCheckout({productId:d.product_id,title:`Plan ${planId.toUpperCase()} · 30 días`,kind:'plan'})}catch(e){toast(e.message,true)}}
async function buyAddon(addonId){if(!state.user)return showSection('vault');try{const d=await api(`/prompt-factory/storage/${encodeURIComponent(addonId)}/prepare-checkout`,{method:'POST'});await openCheckout({productId:d.product_id,title:`${d.extra_slots} espacios adicionales`,kind:'addon'})}catch(e){toast(e.message,true)}}

async function openCheckout(ctx){state.checkout=ctx;state.currentOrder=null;$('checkoutTitle').textContent=ctx.title;$('paymentBox').classList.add('hidden');$('txInput').value='';try{const pm=await api('/payments/methods');state.paymentMode=String(pm.mode||'MOCK').toUpperCase();state.methods=pm.methods||[];state.selectedMethod=state.methods[0]?.method_id||null;$('checkoutMode').textContent=state.paymentMode==='PRODUCTION'?'PAGO REAL: verifica red, token, importe y dirección antes de enviar.':'MODO DE PRUEBA: no envíes fondos reales; usa un TXID mock_…';renderPaymentMethods();$('checkoutDialog').showModal()}catch(e){toast('No hay métodos de pago disponibles',true)}}
function renderPaymentMethods(){$('paymentMethods').innerHTML=state.methods.map((m,i)=>`<button class="payment-method ${i===0?'active':''}" data-method="${esc(m.method_id)}"><b>${esc(m.display_name||m.asset)}</b><small>${esc(m.network)} · ${esc(m.standard)}</small></button>`).join('')||'<p class="muted">Sin redes disponibles.</p>';$('paymentMethods').querySelectorAll('[data-method]').forEach(b=>b.addEventListener('click',()=>{state.selectedMethod=b.dataset.method;$('paymentMethods').querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('active',x===b));$('paymentBox').classList.add('hidden')}))}
$('createOrder')?.addEventListener('click',async()=>{if(!state.checkout||!state.selectedMethod)return;try{$('createOrder').disabled=true;const quote=await api('/payments/quotes',jsonBody({product_id:state.checkout.productId,method_id:state.selectedMethod}));const order=await api('/payments/orders',jsonBody({quote_id:quote.quote_id,idempotency_key:'pf-web-'+crypto.randomUUID()}));state.currentOrder=order;const d=await api(`/payments/orders/${encodeURIComponent(order.order_id)}/checkout`);$('payAmount').textContent=`${d.order.expected_amount} ${d.payment_method.asset}`;$('payNetwork').textContent=`${d.payment_method.network} · ${d.payment_method.standard}`;$('networkWarning').textContent=state.paymentMode==='PRODUCTION'?d.payment_method.warning:'TEST ONLY — no envíes criptomonedas reales.';$('payAddress').textContent=state.paymentMode==='PRODUCTION'?d.payment_method.address:'OCULTA EN MODO DE PRUEBA';$('paymentBox').classList.remove('hidden')}catch(e){toast(e.message,true)}finally{$('createOrder').disabled=false}});
$('verifyPayment')?.addEventListener('click',async()=>{if(!state.currentOrder)return;const tx=$('txInput').value.trim();if(!tx)return toast('Introduce el TXID',true);if(state.paymentMode!=='PRODUCTION'&&!tx.startsWith('mock_'))return toast('En pruebas el TXID debe empezar por mock_',true);try{$('verifyPayment').disabled=true;const order=await api(`/payments/orders/${encodeURIComponent(state.currentOrder.order_id)}/submit-tx`,jsonBody({transaction_hash:tx}));if(order.status!=='FULFILLED'){toast(`Estado: ${order.status}`,true);return}await api('/prompt-factory/reconcile',{method:'POST'});toast('Pago verificado y beneficio activado');$('checkoutDialog').close();await Promise.all([loadPfMe(),loadVault(),loadDashboard(),loadMarketplace()]);if(state.checkout.kind==='listing')showSection('vault');else showSection('plans')}catch(e){toast(e.message,true)}finally{$('verifyPayment').disabled=false}});

function handleSearchParams(){const q=new URLSearchParams(location.search);const slug=q.get('prompt');if(slug)openListing(slug)}
init();
