import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const EDGE=`${SUPABASE_URL}/functions/v1/referral-engine`;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let state=null,open=false,loading=false,autoApplying=false,retries=0;
const $=s=>document.querySelector(s),lang=()=>localStorage.getItem('nexus-lang')||'es',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const T={es:{title:'Referidos',sub:'Invita jugadores y gana créditos internos cuando compren el Pack Fundador.',code:'Tu código',copy:'Copiar',share:'Compartir',invited:'Invitados',qualified:'Recompensados',earned:'Créditos ganados',reward:'Tu recompensa',friendReward:'Bono del invitado',attach:'Aplicar código',yourReferrer:'Invitado por',pending:'Pendiente de compra',rewarded:'Recompensado',empty:'Todavía no tienes referidos.',terms:'Programa de un solo nivel. Los premios son Créditos Premium internos, no retirables y sin valor monetario.',window:'El código debe aplicarse durante los primeros días de la cuenta y antes de comprar el Pack Fundador.',copied:'Copiado',attached:'Código de referido aplicado.'},en:{title:'Referrals',sub:'Invite players and earn internal credits when they buy the Founder Pack.',code:'Your code',copy:'Copy',share:'Share',invited:'Invited',qualified:'Rewarded',earned:'Credits earned',reward:'Your reward',friendReward:'Invitee bonus',attach:'Apply code',yourReferrer:'Invited by',pending:'Awaiting purchase',rewarded:'Rewarded',empty:'No referrals yet.',terms:'Single-level program. Rewards are internal, non-withdrawable Premium Credits with no monetary value.',window:'The code must be applied during the account’s first days and before buying the Founder Pack.',copied:'Copied',attached:'Referral code applied.'}};const t=k=>T[lang()]?.[k]||T.es[k]||k;
function captureRef(){const u=new URL(location.href),r=(u.searchParams.get('ref')||'').trim().toUpperCase();if(/^[A-Z0-9]{6,20}$/.test(r)){localStorage.setItem('nexus-referral-code',r);u.searchParams.delete('ref');history.replaceState({},'',u.pathname+(u.search||'')+u.hash)}}
captureRef();
async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||null}
async function call(body){const tk=await token();if(!tk)throw new Error('AUTH_REQUIRED');const r=await fetch(EDGE,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${tk}`,'apikey':SUPABASE_KEY},body:JSON.stringify(body),cache:'no-store'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Referral request failed');return j}
function human(m=''){if(lang()==='en')return String(m);return String(m).replace('Invalid referral code','Código de referido inválido').replace('Referral code not found','Código de referido no encontrado').replace('Referral already attached','Ya tienes un referido asociado').replace('You cannot refer yourself','No puedes referirte a ti mismo').replace('Referral attribution window expired','El plazo para aplicar un referido terminó').replace('Referral must be applied before Founder Pack purchase','El código debe aplicarse antes de comprar el Pack Fundador').replace('Character not found','Personaje aún no disponible')}
function toast(m){let e=$('#ref-toast');if(!e){e=document.createElement('div');e.id='ref-toast';document.body.append(e)}e.textContent=human(m);e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
async function load(){if(loading)return;loading=true;try{state=await call({op:'state'});renderLauncher();if(open)renderOverlay();await autoApply()}catch(e){if(open)toast(e.message)}finally{loading=false}}
async function applyCode(code,automatic=false){if(loading||autoApplying)return;autoApplying=automatic;try{state=await call({op:'action',action:'applyCode',payload:{code:String(code||'').trim().toUpperCase()}});localStorage.removeItem('nexus-referral-code');toast(t('attached'));renderLauncher();if(open)renderOverlay()}catch(e){const m=String(e.message||'');if(!/Character not found|AUTH_REQUIRED/.test(m))localStorage.removeItem('nexus-referral-code');if(!automatic||!/Character not found|AUTH_REQUIRED/.test(m))toast(m);throw e}finally{autoApplying=false}}
async function autoApply(){const saved=localStorage.getItem('nexus-referral-code');if(!saved||state?.attribution?.invitedBy||!state?.attribution?.canAttach)return;try{await applyCode(saved,true)}catch(e){if(/Character not found|AUTH_REQUIRED/.test(String(e.message||''))&&retries<5){retries++;setTimeout(()=>load(),800*retries)}}}
function isMore(){const h=$('#panel .section-head h2');return !!h&&/Más|More/i.test(h.textContent||'')}
function renderLauncher(){if(!isMore())return;let e=$('#ref-launcher');if(!e){e=document.createElement('section');e.id='ref-launcher';e.className='ref-launcher';const after=$('#season-launcher')||$('#earn-launcher')||$('#clan-launcher')||document.querySelector('#panel .segmented');after?.insertAdjacentElement('afterend',e)}const total=state?.stats?.total??0,rewarded=state?.stats?.rewarded??0;e.innerHTML=`<button class="ref-launch" data-ref-open><span>🤝</span><div><b>${t('title')}</b><small>${state?`${total} ${t('invited').toLowerCase()} · ${rewarded} ${t('qualified').toLowerCase()}`:t('sub')}</small></div><strong>›</strong></button>`;e.querySelector('[data-ref-open]')?.addEventListener('click',()=>{open=true;document.body.classList.add('ref-open');renderOverlay();load()})}
function recent(){const rows=state?.referrals||[];return rows.length?`<div class="ref-list">${rows.map(x=>`<div><span><b>${esc(x.name)}</b><small>${new Date(x.createdAt).toLocaleDateString()}</small></span><strong class="${x.status}">${x.status==='rewarded'?`+${x.rewardCredits} 💎`:t('pending')}</strong></div>`).join('')}</div>`:`<div class="ref-empty">${t('empty')}</div>`}
function renderOverlay(){let ov=$('#ref-overlay');if(!open){ov?.remove();return}if(!ov){ov=document.createElement('div');ov.id='ref-overlay';ov.className='ref-overlay';document.body.append(ov)}const s=state;if(!s){ov.innerHTML='<div class="ref-sheet"><div class="ref-bar"><b>🤝 Referidos</b><button data-ref-close>✕</button></div><div class="ref-body">...</div></div>';bind();return}const invited=s.attribution.invitedBy;const attach=!invited&&s.attribution.canAttach?`<div class="ref-attach"><input id="ref-code-input" maxlength="20" placeholder="NX1234567890"><button data-ref-apply>${t('attach')}</button></div><small>${t('window')} ${new Date(s.attribution.deadline).toLocaleDateString()}</small>`:invited?`<div class="ref-invited">${t('yourReferrer')}: <b>${esc(invited.name)}</b> · ${esc(invited.code)} · ${invited.status==='rewarded'?t('rewarded'):t('pending')}</div>`:'';ov.innerHTML=`<div class="ref-sheet"><div class="ref-bar"><b>🤝 ${t('title')}</b><button data-ref-close>✕</button></div><div class="ref-body"><section class="ref-hero"><h2>${t('title')}</h2><p>${t('sub')}</p><div class="ref-code"><small>${t('code')}</small><strong>${esc(s.profile.code)}</strong><div><button data-ref-copy>${t('copy')}</button><button class="primary" data-ref-share>${t('share')}</button></div></div></section><section class="ref-stats"><div><small>${t('invited')}</small><strong>${s.stats.total}</strong></div><div><small>${t('qualified')}</small><strong>${s.stats.rewarded}</strong></div><div><small>${t('earned')}</small><strong>${s.stats.totalPremiumCredits} 💎</strong></div></section><section class="ref-reward"><div><small>${t('reward')}</small><strong>+${s.config.referrerPremiumCredits} 💎</strong></div><div><small>${t('friendReward')}</small><strong>+${s.config.referredPremiumCredits} 💎</strong></div></section>${attach}<section><h3>📋 ${t('invited')}</h3>${recent()}</section><p class="ref-terms">${t('terms')}</p></div></div>`;bind()}
function bind(){const ov=$('#ref-overlay');if(!ov)return;ov.querySelector('[data-ref-close]')?.addEventListener('click',()=>{open=false;document.body.classList.remove('ref-open');renderOverlay()});ov.addEventListener('click',e=>{if(e.target===ov){open=false;document.body.classList.remove('ref-open');renderOverlay()}});ov.querySelector('[data-ref-copy]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(state.profile.shareUrl);toast(t('copied'))}catch{toast(state.profile.shareUrl)}});ov.querySelector('[data-ref-share]')?.addEventListener('click',async()=>{const data={title:'Nexus Realms',text:lang()==='es'?'Únete a Nexus Realms con mi código de referido.':'Join Nexus Realms with my referral code.',url:state.profile.shareUrl};if(navigator.share)await navigator.share(data).catch(()=>{});else try{await navigator.clipboard.writeText(state.profile.shareUrl);toast(t('copied'))}catch{toast(state.profile.shareUrl)}});ov.querySelector('[data-ref-apply]')?.addEventListener('click',()=>applyCode($('#ref-code-input')?.value||''))}
function refreshSoon(){setTimeout(()=>{renderLauncher();load()},100)}
window.addEventListener('nexus:state',refreshSoon);window.addEventListener('pageshow',refreshSoon);document.addEventListener('click',e=>{const b=e.target?.closest?.('[data-tab]');if(b&&/more|más|mas/i.test(String(b.dataset.tab||'')))refreshSoon()},true);supabase.auth.onAuthStateChange((_e,s)=>{if(s)setTimeout(()=>load(),700)});setTimeout(()=>load(),1200);
