import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const EDGE=`${SUPABASE_URL}/functions/v1/referral-engine`;
const STORAGE_KEY='nexus-referral-code';
const CAPTURED_AT_KEY='nexus-referral-captured-at';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let state=null,open=false,loading=false,autoApplying=false,retries=0,retryTimer=null,lastLauncherSignature='';
const $=s=>document.querySelector(s),lang=()=>localStorage.getItem('nexus-lang')||'es',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const T={es:{title:'Referidos',sub:'Invita jugadores y gana Créditos Premium cuando compren el Pack Fundador.',link:'Mi enlace de referido',copy:'Copiar enlace',share:'Compartir',invited:'Invitados',qualified:'Recompensados',earned:'Créditos ganados',reward:'Tu recompensa',friendReward:'Bono del invitado',yourReferrer:'Invitado por',pending:'Pendiente',rewarded:'Recompensado',empty:'Todavía no tienes referidos.',terms:'Programa de un solo nivel. Las recompensas son Créditos Premium internos, no retirables y sin valor monetario.',auto:'Tu referido se aplicará automáticamente al crear tu personaje.',copied:'Enlace copiado',attached:'Referido aplicado automáticamente.'},en:{title:'Referrals',sub:'Invite players and earn Premium Credits when they buy the Founder Pack.',link:'My referral link',copy:'Copy link',share:'Share',invited:'Invited',qualified:'Rewarded',earned:'Credits earned',reward:'Your reward',friendReward:'Invitee bonus',yourReferrer:'Invited by',pending:'Pending',rewarded:'Rewarded',empty:'No referrals yet.',terms:'Single-level referral program. Rewards are internal Premium Credits, non-withdrawable and have no monetary value.',auto:'Your referral will be automatically applied after your character is created.',copied:'Link copied',attached:'Referral applied automatically.'}};const t=k=>T[lang()]?.[k]||T.es[k]||k;
function validToken(v){return /^[A-Z0-9]{6,20}$/.test(String(v||'').trim().toUpperCase())}
function captureRef(){const u=new URL(location.href),r=(u.searchParams.get('ref')||'').trim().toUpperCase();if(validToken(r)){localStorage.setItem(STORAGE_KEY,r);localStorage.setItem(CAPTURED_AT_KEY,new Date().toISOString())}if(u.searchParams.has('ref')){u.searchParams.delete('ref');history.replaceState({},'',u.pathname+(u.search||'')+u.hash)}}
function shareUrl(){if(!state?.profile?.code)return'';const u=new URL('/',window.location.origin);u.searchParams.set('ref',state.profile.code);return u.toString()}
function shortLink(url){try{const u=new URL(url);const token=u.searchParams.get('ref')||'';return `${u.origin}/?ref=${token.length>9?`${token.slice(0,6)}…${token.slice(-4)}`:token}`}catch{return url}}
captureRef();
async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||null}
async function call(body){const tk=await token();if(!tk)throw new Error('AUTH_REQUIRED');const r=await fetch(EDGE,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${tk}`,'apikey':SUPABASE_KEY},body:JSON.stringify(body),cache:'no-store'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Referral request failed');return j}
function human(m=''){if(lang()==='en')return String(m);return String(m).replace('Invalid referral code','Enlace de referido inválido').replace('Referral code not found','Enlace de referido no válido').replace('Referral already attached','Ya tienes un referido asociado').replace('You cannot refer yourself','No puedes referirte a ti mismo').replace('Referral attribution window expired','El plazo para aplicar el referido terminó').replace('Referral must be applied before Founder Pack purchase','El referido debe aplicarse antes de comprar el Pack Fundador').replace('Character not found','Personaje aún no disponible')}
function toast(m){let e=$('#ref-toast');if(!e){e=document.createElement('div');e.id='ref-toast';document.body.append(e)}e.textContent=human(m);e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function clearRetry(){if(retryTimer){clearTimeout(retryTimer);retryTimer=null}}
function retryLoad(){if(retries>=8)return;clearRetry();retries++;retryTimer=setTimeout(()=>load(),Math.min(6000,700*retries))}
async function load(){if(loading)return;loading=true;try{state=await call({op:'state'});retries=0;clearRetry();renderLauncher();if(open)renderOverlay();await autoApply()}catch(e){const m=String(e.message||'');if(localStorage.getItem(STORAGE_KEY)&&/Character not found|AUTH_REQUIRED/.test(m))retryLoad();else if(open)toast(m)}finally{loading=false}}
async function applyReferral(code,automatic=false){if(autoApplying)return;autoApplying=automatic;try{state=await call({op:'action',action:'applyReferral',payload:{code:String(code||'').trim().toUpperCase()}});localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(CAPTURED_AT_KEY);toast(t('attached'));renderLauncher();if(open)renderOverlay()}catch(e){const m=String(e.message||'');if(!/Character not found|AUTH_REQUIRED/.test(m)){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(CAPTURED_AT_KEY)}if(!automatic||!/Character not found|AUTH_REQUIRED/.test(m))toast(m);throw e}finally{autoApplying=false}}
async function autoApply(){const saved=localStorage.getItem(STORAGE_KEY);if(!saved||state?.attribution?.invitedBy||!state?.attribution?.canAttach)return;try{await applyReferral(saved,true)}catch(e){if(/Character not found|AUTH_REQUIRED/.test(String(e.message||'')))retryLoad()}}
function isMore(){const h=$('#panel .section-head h2');return !!h&&/Más|More/i.test(h.textContent||'')}
function renderLauncher(){if(!isMore())return;let e=$('#ref-launcher');if(!e){e=document.createElement('section');e.id='ref-launcher';e.className='ref-launcher';const after=$('#season-launcher')||$('#earn-launcher')||$('#clan-launcher')||document.querySelector('#panel .segmented');after?.insertAdjacentElement('afterend',e)}const total=state?.stats?.total??0,rewarded=state?.stats?.rewarded??0;const sig=`${lang()}|${total}|${rewarded}|${Boolean(state)}`;if(sig===lastLauncherSignature&&e.querySelector('[data-ref-open]'))return;lastLauncherSignature=sig;e.innerHTML=`<button class="ref-launch" data-ref-open><span>🤝</span><div><b>${t('title')}</b><small>${state?`${total} ${t('invited').toLowerCase()} · ${rewarded} ${t('qualified').toLowerCase()}`:t('sub')}</small></div><strong>›</strong></button>`;e.querySelector('[data-ref-open]')?.addEventListener('click',()=>{open=true;document.body.classList.add('ref-open');renderOverlay();load()})}
function recent(){const rows=state?.referrals||[];return rows.length?`<div class="ref-list">${rows.map(x=>`<div><span><b>${esc(x.name)}</b><small>${new Date(x.createdAt).toLocaleDateString()}</small></span><strong class="${esc(x.status)}">${x.status==='rewarded'?`+${x.rewardCredits} 💎`:t('pending')}</strong></div>`).join('')}</div>`:`<div class="ref-empty">${t('empty')}</div>`}
function renderOverlay(){let ov=$('#ref-overlay');if(!open){ov?.remove();return}if(!ov){ov=document.createElement('div');ov.id='ref-overlay';ov.className='ref-overlay';document.body.append(ov)}const s=state;if(!s){ov.innerHTML=`<div class="ref-sheet"><div class="ref-bar"><b>🤝 ${t('title')}</b><button data-ref-close>✕</button></div><div class="ref-body">...</div></div>`;bind();return}const invited=s.attribution.invitedBy;const url=shareUrl();const attribution=invited?`<div class="ref-invited">${t('yourReferrer')}: <b>${esc(invited.name)}</b> · ${invited.status==='rewarded'?t('rewarded'):t('pending')}</div>`:(localStorage.getItem(STORAGE_KEY)?`<div class="ref-auto-note">${t('auto')}</div>`:'');ov.innerHTML=`<div class="ref-sheet"><div class="ref-bar"><b>🤝 ${t('title')}</b><button data-ref-close>✕</button></div><div class="ref-body"><section class="ref-hero"><h2>${t('title')}</h2><p>${t('sub')}</p><div class="ref-link-card"><small>${t('link')}</small><div class="ref-link-display" title="${esc(url)}">${esc(shortLink(url))}</div><div class="ref-link-actions"><button data-ref-copy>${t('copy')}</button><button class="primary" data-ref-share>${t('share')}</button></div></div></section><section class="ref-stats"><div><small>${t('invited')}</small><strong>${s.stats.total}</strong></div><div><small>${t('qualified')}</small><strong>${s.stats.rewarded}</strong></div><div><small>${t('earned')}</small><strong>${s.stats.totalPremiumCredits} 💎</strong></div></section><section class="ref-reward"><div><small>${t('reward')}</small><strong>+${s.config.referrerPremiumCredits} 💎</strong></div><div><small>${t('friendReward')}</small><strong>+${s.config.referredPremiumCredits} 💎</strong></div></section>${attribution}<section><h3>📋 ${t('invited')}</h3>${recent()}</section><p class="ref-terms">${t('terms')}</p></div></div>`;bind()}
async function copyLink(){const url=shareUrl();if(!url)return;try{await navigator.clipboard.writeText(url);toast(t('copied'))}catch{const ta=document.createElement('textarea');ta.value=url;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';document.body.append(ta);ta.select();try{document.execCommand('copy');toast(t('copied'))}finally{ta.remove()}}}
function bind(){const ov=$('#ref-overlay');if(!ov)return;ov.querySelector('[data-ref-close]')?.addEventListener('click',()=>{open=false;document.body.classList.remove('ref-open');renderOverlay()});ov.addEventListener('click',e=>{if(e.target===ov){open=false;document.body.classList.remove('ref-open');renderOverlay()}});ov.querySelector('[data-ref-copy]')?.addEventListener('click',copyLink);ov.querySelector('[data-ref-share]')?.addEventListener('click',async()=>{const url=shareUrl();const data={title:'Nexus Realms',text:lang()==='es'?'Únete a Nexus Realms con mi enlace de referido.':'Join Nexus Realms with my referral link.',url};if(navigator.share){try{await navigator.share(data)}catch(e){if(e?.name!=='AbortError')await copyLink()}}else await copyLink()})}
function refreshSoon(){setTimeout(()=>{renderLauncher();load()},120)}
window.addEventListener('nexus:state',refreshSoon);window.addEventListener('pageshow',refreshSoon);document.addEventListener('click',e=>{const b=e.target?.closest?.('[data-tab]');if(b&&/more|más|mas/i.test(String(b.dataset.tab||'')))refreshSoon()},true);supabase.auth.onAuthStateChange((_e,s)=>{if(s)setTimeout(()=>load(),700)});setTimeout(()=>load(),1200);
