import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const SUPABASE_URL='https://culwlrspkwbcbtmopgcp.supabase.co';
const SUPABASE_KEY='sb_publishable_JfDoNvnecRDooAOK6dTg2A_2fRV5zRZ';
const EDGE=`${SUPABASE_URL}/functions/v1/season-engine`;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let state=null,open=false,loading=false;
const $=s=>document.querySelector(s),lang=()=>localStorage.getItem('nexus-lang')||'es',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const T={
 es:{title:'Pase de Batalla',premium:'Premium',free:'Gratis',credits:'Créditos Premium DEMO',unlock:'Desbloquear Premium',shop:'Mejoras limitadas',packs:'Paquetes de créditos',disabled:'Pago real desactivado',claim:'Reclamar',claimed:'Reclamado',locked:'Bloqueado',level:'Nivel',season:'Temporada',close:'Cerrar',demo:'DEMO · sin dinero real',limit:'límite semanal',founder:'Pack Fundador',founderSub:'Ayuda a financiar el lanzamiento y recibe contenido exclusivo.',reserve:'Reservar Pack Fundador',reserved:'Reserva creada',owned:'Pack Fundador adquirido',value:'Valor interno',treasury:'Destino del ingreso',reserveFund:'Reserva Earn',development:'Desarrollo/servidores',operations:'Operación/marketing',checkoutSoon:'El cobro real aún no está habilitado. La reserva no cobra dinero.',cancel:'Cancelar reserva'},
 en:{title:'Battle Pass',premium:'Premium',free:'Free',credits:'Premium DEMO Credits',unlock:'Unlock Premium',shop:'Limited upgrades',packs:'Credit packages',disabled:'Real payments disabled',claim:'Claim',claimed:'Claimed',locked:'Locked',level:'Level',season:'Season',close:'Close',demo:'DEMO · no real money',limit:'weekly limit',founder:'Founder Pack',founderSub:'Help fund launch and receive exclusive in-game content.',reserve:'Reserve Founder Pack',reserved:'Reservation created',owned:'Founder Pack owned',value:'Internal value',treasury:'Revenue allocation',reserveFund:'Earn reserve',development:'Development/servers',operations:'Operations/marketing',checkoutSoon:'Real checkout is not enabled yet. Reserving does not charge money.',cancel:'Cancel reservation'}
};
const t=k=>T[lang()]?.[k]||T.es[k]||k;
async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token||null}
async function call(body){const tk=await token();if(!tk)throw new Error(lang()==='es'?'Inicia sesión primero':'Sign in first');const r=await fetch(EDGE,{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${tk}`,'apikey':SUPABASE_KEY},body:JSON.stringify(body),cache:'no-store'});const j=await r.json();if(!r.ok||j.error)throw new Error(j.error||'Season request failed');return j}
async function load(){if(loading)return;loading=true;try{state=await call({op:'state'});launcher();if(open)overlay()}catch(e){toast(e.message)}finally{loading=false}}
async function act(action,payload={}){if(loading)return;loading=true;try{state=await call({op:'action',action,payload});toast(state.message||'✓');launcher();overlay()}catch(e){toast(e.message)}finally{loading=false}}
function toast(m){let e=$('#season-toast');if(!e){e=document.createElement('div');e.id='season-toast';document.body.append(e)}e.textContent=String(m).replace('Not enough Premium DEMO Credits','No tienes suficientes Créditos Premium DEMO').replace('Weekly shop limit reached','Límite semanal alcanzado').replace('Battle Pass level required','Necesitas más nivel del Pase de Batalla').replace('Premium Pass required','Necesitas el Pase Premium').replace('Founder pack not found','Pack Fundador no disponible');e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function isMore(){const h=$('#panel .section-head h2');return !!h&&/Más|More/i.test(h.textContent||'')}
function launcher(){if(!isMore())return;let e=$('#season-launcher');if(!e){e=document.createElement('section');e.id='season-launcher';e.className='season-launcher';const after=$('#earn-launcher')||$('#clan-launcher')||document.querySelector('#panel .segmented');after?.insertAdjacentElement('afterend',e)}const lvl=state?.progress?.level??0,founder=state?.founder?.owned?' · 👑 Fundador':'';e.innerHTML=`<button class="season-launch" data-season-open><span>🎟️</span><div><b>${t('title')}</b><small>${state?`${t('level')} ${lvl}/${state.season.maxLevel} · ${state.character.premiumCreditsDemo} ${t('credits')}${founder}`:t('demo')}</small></div><strong>›</strong></button>`;e.querySelector('[data-season-open]')?.addEventListener('click',()=>{open=true;document.body.classList.add('season-open');overlay();load()})}
function rewardText(r){return (r?.rewards||[]).map(x=>x.type==='gold'?`🪙 ${x.amount}`:x.type==='resource'?`${x.key==='essence'?'✨':'📦'} ${x.amount} ${x.key}`:x.type==='stat_points'?`⭐ +${x.amount} stats`:x.type==='profession_tree_points'?`🌳 +${x.amount} árbol`:x.type==='item'?`🛡️ ${x.name} · ${x.rarity}`:'🎁').join(' · ')}
function rows(){const by=new Map();for(const r of state.rewards){const x=by.get(r.level)||{};x[r.track]=r;by.set(r.level,x)}return [...by.entries()].map(([lvl,x])=>`<div class="bp-row ${lvl<=state.progress.level?'ready':''}"><div class="bp-level">${lvl}</div>${['free','premium'].map(track=>{const r=x[track];if(!r)return'<div></div>';const locked=!r.ready&&!r.claimed;return `<div class="bp-reward ${track}"><small>${track==='free'?t('free'):t('premium')}</small><span>${rewardText(r.reward)}</span><button data-claim-level="${lvl}" data-claim-track="${track}" ${locked||r.claimed||loading?'disabled':''}>${r.claimed?t('claimed'):locked?t('locked'):t('claim')}</button></div>`}).join('')}</div>`).join('')}
function shop(){return state.shop.map(x=>`<div class="season-card"><b>${esc(lang()==='es'?x.nameEs:x.name)}</b><span>${x.costCredits} 💎</span><small>${x.purchasedThisWeek}/${x.weeklyLimit} ${t('limit')}</small><button data-shop="${x.key}" ${x.purchasedThisWeek>=x.weeklyLimit||loading?'disabled':''}>${t('claim')}</button></div>`).join('')}
function packs(){return state.packages.map(x=>`<div class="season-card"><b>${x.credits} 💎</b><span>$${x.priceUsd.toFixed(2)}</span><small>${t('disabled')}</small><button disabled>${t('disabled')}</button></div>`).join('')}
function founderBenefits(f){const b=f?.benefits||{};const bits=[];if(b.battle_pass_premium)bits.push('🎟️ Pase Premium');if(b.premium_credits)bits.push(`💎 ${b.premium_credits} créditos`);if(b.stat_points)bits.push(`⭐ +${b.stat_points} stats`);if(b.profession_tree_points)bits.push(`🌳 +${b.profession_tree_points} árbol`);if(b.founder_title)bits.push('👑 título Fundador');if(b.founder_frame)bits.push('🖼️ marco Fundador');if(b.item?.name)bits.push(`💍 ${esc(b.item.name)} · ${esc(b.item.rarity||'EPIC')}`);return bits.map(x=>`<span>${x}</span>`).join('')}
function founderHtml(){const f=state?.founder;if(!f)return'';const a=f.allocation||{},status=f.order?.status;let action='';if(f.owned||status==='paid')action=`<div class="founder-owned">✓ ${t('owned')}</div>`;else if(status==='reserved'||status==='awaiting_payment')action=`<div class="founder-reserved">⏳ ${t('reserved')}</div><small>${t('checkoutSoon')}</small><button class="ghost" data-founder-cancel>${t('cancel')}</button>`;else action=`<button class="founder-cta" data-founder-reserve>${t('reserve')} · $${f.priceUsd.toFixed(2)}</button><small>${t('checkoutSoon')}</small>`;return `<section class="founder-card"><div class="founder-head"><div><span class="eyebrow">EDICIÓN DE LANZAMIENTO</span><h3>👑 ${esc(lang()==='es'?f.nameEs:f.name)}</h3><p>${t('founderSub')}</p></div><div class="founder-price"><strong>$${f.priceUsd.toFixed(2)}</strong><small>${t('value')}: $${f.internalValueUsd.toFixed(2)}+</small></div></div><div class="founder-benefits">${founderBenefits(f)}</div><div class="founder-split"><b>${t('treasury')}</b><div><span>${t('reserveFund')} <strong>${Number(a.reward_reserve_pct||0)}%</strong></span><span>${t('development')} <strong>${Number(a.development_pct||0)}%</strong></span><span>${t('operations')} <strong>${Number(a.operations_pct||0)}%</strong></span></div></div><div class="founder-actions">${action}</div></section>`}
function overlay(){let ov=$('#season-overlay');if(!open){ov?.remove();return}if(!ov){ov=document.createElement('div');ov.id='season-overlay';ov.className='season-overlay';document.body.append(ov)}ov.innerHTML=`<div class="season-sheet"><div class="season-bar"><b>🎟️ ${t('title')}</b><button data-season-close>✕</button></div><div class="season-body">${state?`<section class="season-hero"><div><span class="eyebrow">${t('demo')}</span><h2>${lang()==='es'?state.season.nameEs:state.season.name}</h2><p>${state.disclaimer[lang()]}</p></div><div class="season-wallet"><small>${t('credits')}</small><strong>${state.character.premiumCreditsDemo}</strong></div></section>${founderHtml()}<div class="bp-progress"><div><span>${t('level')} ${state.progress.level}/${state.season.maxLevel}</span><span>${state.progress.xp%100}/100 XP</span></div><i style="width:${state.progress.xp%100}%"></i></div>${!state.progress.premiumUnlocked?`<button class="season-premium" data-unlock>${t('unlock')} · ${state.season.premiumPriceCredits} 💎 / $${state.season.premiumPriceUsd.toFixed(2)} <small>${t('disabled')} para USD</small></button>`:`<div class="premium-active">✓ ${t('premium')}</div>`}<section><h3>🏆 ${t('title')}</h3><div class="bp-list">${rows()}</div></section><section><h3>✨ ${t('shop')}</h3><div class="season-grid">${shop()}</div></section><section><h3>💳 ${t('packs')}</h3><div class="season-grid">${packs()}</div></section>`:'<div class="season-loading">...</div>'}</div></div>`;ov.querySelector('[data-season-close]')?.addEventListener('click',()=>{open=false;document.body.classList.remove('season-open');overlay()});ov.addEventListener('click',e=>{if(e.target===ov){open=false;document.body.classList.remove('season-open');overlay()}});ov.querySelector('[data-unlock]')?.addEventListener('click',()=>act('unlockPremium'));ov.querySelector('[data-founder-reserve]')?.addEventListener('click',()=>act('reserveFounderPack',{packKey:state?.founder?.key}));ov.querySelector('[data-founder-cancel]')?.addEventListener('click',()=>act('cancelFounderReservation'));ov.querySelectorAll('[data-claim-level]').forEach(b=>b.addEventListener('click',()=>act('claimReward',{level:Number(b.dataset.claimLevel),track:b.dataset.claimTrack})));ov.querySelectorAll('[data-shop]').forEach(b=>b.addEventListener('click',()=>act('buyShop',{itemKey:b.dataset.shop})))}
function refreshLauncherSoon(){setTimeout(()=>{launcher();if(open)load()},80)}
window.addEventListener('nexus:state',refreshLauncherSoon);window.addEventListener('pageshow',refreshLauncherSoon);document.addEventListener('click',e=>{const b=e.target?.closest?.('[data-tab]');if(b&&/more|más|mas/i.test(String(b.dataset.tab||'')))refreshLauncherSoon()},true);setTimeout(()=>{launcher();load()},1000);
