export class LegacyRuntimeAdapter {
  constructor({ store, bus, scheduler, documentRef = document, windowRef = window }) { this.store=store;this.bus=bus;this.scheduler=scheduler;this.document=documentRef;this.window=windowRef;this.observer=null;this.lastPlayerFingerprint=''; }
  legacyGame(){try{return this.window.CryptoQuestCore?.getGame?.()??this.window.game??null;}catch{return null;}}
  normalizeEquipped(raw={}){const result={};for(const [slot,value] of Object.entries(raw||{})){if(value==null)continue;result[slot]=typeof value==='string'?value:(value.uid??value.id??null);}return result;}
  normalizePlayer(game){const p=game?.player??game?.character??null;if(!p)return null;const currentEnergy=Number(p.energy?.current??p.energy??game?.energy??0);const maxEnergy=Number(p.energy?.max??p.maxEnergy??game?.maxEnergy??currentEnergy);const rawItems=p.inventory?.items??game?.inventory??[];const items=Array.isArray(rawItems)?structuredClone(rawItems):[];const rawEquipped=p.inventory?.equipped??p.equipment??game?.equipment??{};return{id:p.id??null,name:p.name??p.username??'',classId:p.classId??p.class??null,level:Number(p.level??1),xp:Number(p.xp??p.exp??0),currencies:{gold:Number(p.gold??game?.gold??0),premium:Number(p.premium??p.gems??game?.premium??0)},energy:{current:currentEnergy,max:maxEnergy,updatedAt:Date.now()},inventory:{items,equipped:this.normalizeEquipped(rawEquipped)}};}
  playerFingerprint(player){if(!player)return'';return JSON.stringify({id:player.id,name:player.name,classId:player.classId,level:player.level,xp:player.xp,currencies:player.currencies,energy:{current:player.energy?.current,max:player.energy?.max},itemUids:(player.inventory?.items??[]).map(item=>item?.uid??item?.id??null),equipped:player.inventory?.equipped??{}});}
  currentScreen(){const shell=this.document.getElementById('game');const activeClass=shell?[...shell.classList].find(name=>name.endsWith('-active')):null;return activeClass?.replace(/-active$/,'')??null;}
  sync(){const game=this.legacyGame();const player=this.normalizePlayer(game);const fingerprint=this.playerFingerprint(player);const screen=this.currentScreen()??this.store.select(state=>state.ui?.screen??'boot');const previousScreen=this.store.select(state=>state.ui?.screen);const legacyDetected=Boolean(game);const previousLegacy=Boolean(this.store.select(state=>state.runtime?.legacyDetected));const playerChanged=fingerprint!==this.lastPlayerFingerprint;if(screen===previousScreen&&legacyDetected===previousLegacy&&!playerChanged)return;this.store.update(state=>{state.ui??={};state.runtime??={};if(screen!==state.ui.screen){state.ui.previousScreen=state.ui.screen??null;state.ui.screen=screen;}state.runtime.legacyDetected=legacyDetected;state.runtime.lastLegacySyncAt=Date.now();if(playerChanged&&player)state.player=player;},{source:'legacy-runtime-adapter'});this.lastPlayerFingerprint=fingerprint;if(screen!==previousScreen)this.bus?.emit('navigation:changed',{screen,source:'legacy-runtime-adapter'});if(playerChanged&&player)this.bus?.emit('legacy:player-synced',{playerId:player.id,level:player.level});}
  scheduleSync=()=>this.scheduler.frame('legacy-sync',()=>this.sync());
  start(){if(this.observer)return;if(this.document.readyState==='loading')this.document.addEventListener('DOMContentLoaded',this.scheduleSync,{once:true});else this.scheduleSync();this.window.addEventListener('load',this.scheduleSync,{once:true});const Observer=this.window.MutationObserver??globalThis.MutationObserver;if(Observer){this.observer=new Observer(this.scheduleSync);this.observer.observe(this.document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});}this.scheduler.debounce('legacy-initial-sync',this.scheduleSync,250);}
  dispose(){this.observer?.disconnect();this.observer=null;}
}
