import {createClient} from 'npm:@supabase/supabase-js@2';

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')??'';
const publishableKeys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')??'{}');
const secretKeys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')??'{}');
const PUBLISHABLE_KEY=publishableKeys.default??Deno.env.get('SUPABASE_ANON_KEY')??'';
const SECRET_KEY=secretKeys.default??Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'';
const admin=createClient(SUPABASE_URL,SECRET_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));

async function authUser(req:Request){const h=req.headers.get('Authorization');if(!h)throw new Error('AUTH_REQUIRED');const scoped=createClient(SUPABASE_URL,PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:h}}});const {data:{user},error}=await scoped.auth.getUser(h.replace(/^Bearer\s+/i,''));if(error||!user)throw new Error('AUTH_INVALID');return user;}
async function characterFor(userId:string){const {data,error}=await admin.from('characters').select('id,name,class,level,xp,renown,zone_id,selected_title_key').eq('user_id',userId).eq('slot',1).single();if(error)throw error;return data;}
async function rpc(name:string,args:any={}){const {data,error}=await admin.rpc(name,args);if(error)throw error;return data;}
async function guildFor(characterId:string){const {data,error}=await admin.from('guild_members').select('guild_id,role').eq('character_id',characterId).maybeSingle();if(error)throw error;return data;}

async function profileMap(ids:string[]){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return new Map<string,any>();const [chars,presence,titles,pets,guildMembers]=await Promise.all([
 admin.from('characters').select('id,name,class,level,renown,selected_title_key').in('id',unique),
 admin.from('player_presence').select('character_id,status,last_seen_at').in('character_id',unique),
 admin.from('title_definitions').select('title_key,name_es,name_en'),
 admin.from('character_pets').select('character_id,pet_key,level,evolution_stage').in('character_id',unique).eq('equipped',true),
 admin.from('guild_members').select('character_id,guild_id,role').in('character_id',unique)
]);for(const x of [chars,presence,titles,pets,guildMembers])if(x.error)throw x.error;
 const titleMap=new Map((titles.data??[]).map((x:any)=>[x.title_key,x]));const presenceMap=new Map((presence.data??[]).map((x:any)=>[x.character_id,x]));const petMap=new Map((pets.data??[]).map((x:any)=>[x.character_id,x]));const gmMap=new Map((guildMembers.data??[]).map((x:any)=>[x.character_id,x]));const guildIds=[...new Set((guildMembers.data??[]).map((x:any)=>x.guild_id).filter(Boolean))];let guilds:any[]=[];if(guildIds.length){const q=await admin.from('guilds').select('id,name,tag,level').in('id',guildIds);if(q.error)throw q.error;guilds=q.data??[];}const guildMap=new Map(guilds.map((g:any)=>[g.id,g]));
 const map=new Map<string,any>();for(const c of chars.data??[]){const p=presenceMap.get(c.id),last=p?.last_seen_at?new Date(p.last_seen_at).getTime():0,online=Date.now()-last<5*60_000;const t=titleMap.get(c.selected_title_key),gm=gmMap.get(c.id);map.set(c.id,{id:c.id,name:c.name,class:c.class,level:Number(c.level),renown:Number(c.renown),title:t??null,online,status:online?(p?.status??'online'):'offline',lastSeenAt:p?.last_seen_at??null,pet:petMap.get(c.id)??null,guild:gm?{...guildMap.get(gm.guild_id),role:gm.role}:null});}return map;
}

async function petsState(c:any){const [defs,owned]=await Promise.all([admin.from('pet_definitions').select('*').eq('enabled',true).order('created_at'),admin.from('character_pets').select('*').eq('character_id',c.id).order('equipped',{ascending:false}).order('level',{ascending:false})]);if(defs.error)throw defs.error;if(owned.error)throw owned.error;const dmap=new Map((defs.data??[]).map((d:any)=>[d.pet_key,d]));return{definitions:defs.data??[],owned:(owned.data??[]).map((p:any)=>({...p,definition:dmap.get(p.pet_key)??null,nextLevelXp:Math.pow(Math.min(Number(p.level)+1,50)-1,2)*100})),equipped:(owned.data??[]).find((p:any)=>p.equipped)?.id??null,rarities:['common','uncommon','rare','epic','legendary','mythic']};}

async function socialState(c:any){const g=await guildFor(c.id);const [incoming,outgoing,friendships,mutes]=await Promise.all([
 admin.from('friend_requests').select('*').eq('addressee_id',c.id).eq('status','pending').order('created_at',{ascending:false}),
 admin.from('friend_requests').select('*').eq('requester_id',c.id).eq('status','pending').order('created_at',{ascending:false}),
 admin.from('friendships').select('*').or(`character_a.eq.${c.id},character_b.eq.${c.id}`).order('created_at',{ascending:false}),
 admin.from('chat_mutes').select('muted_character_id,expires_at').eq('muter_character_id',c.id)
 ]);for(const x of [incoming,outgoing,friendships,mutes])if(x.error)throw x.error;const friendIds=(friendships.data??[]).map((x:any)=>x.character_a===c.id?x.character_b:x.character_a);const reqIds=[...(incoming.data??[]).map((x:any)=>x.requester_id),...(outgoing.data??[]).map((x:any)=>x.addressee_id)];const profiles=await profileMap([...friendIds,...reqIds]);return{friends:friendIds.map(id=>profiles.get(id)).filter(Boolean),incoming:(incoming.data??[]).map((x:any)=>({...x,profile:profiles.get(x.requester_id)??null})),outgoing:(outgoing.data??[]).map((x:any)=>({...x,profile:profiles.get(x.addressee_id)??null})),mutedIds:(mutes.data??[]).filter((x:any)=>!x.expires_at||new Date(x.expires_at).getTime()>Date.now()).map((x:any)=>x.muted_character_id),guild:g};}

async function chatState(c:any,social:any){const muted=new Set<string>(social.mutedIds??[]);const globalQ=admin.from('chat_messages').select('id,character_id,channel,guild_id,body,created_at').eq('channel','global').order('created_at',{ascending:false}).limit(60);const clanQ=social.guild?.guild_id?admin.from('chat_messages').select('id,character_id,channel,guild_id,body,created_at').eq('channel','clan').eq('guild_id',social.guild.guild_id).order('created_at',{ascending:false}).limit(60):Promise.resolve({data:[],error:null});const [globalRes,clanRes]=await Promise.all([globalQ,clanQ]);if(globalRes.error)throw globalRes.error;if((clanRes as any).error)throw (clanRes as any).error;const rows=[...(globalRes.data??[]),...((clanRes as any).data??[])].filter((x:any)=>!muted.has(x.character_id));const profiles=await profileMap(rows.map((x:any)=>x.character_id));const decorate=(list:any[])=>list.filter((x:any)=>!muted.has(x.character_id)).reverse().map((x:any)=>({...x,profile:profiles.get(x.character_id)??null}));return{global:decorate(globalRes.data??[]),clan:decorate((clanRes as any).data??[])};}

async function rankingsState(c:any){await rpc('phase5_refresh_rankings_if_needed');const {data,error}=await admin.from('phase5_rankings').select('*').lte('rank',20).order('ranking_key').order('rank');if(error)throw error;const rows=data??[],charIds=rows.filter((x:any)=>x.entity_type==='character').map((x:any)=>x.entity_id),guildIds=[...new Set(rows.filter((x:any)=>x.entity_type==='guild').map((x:any)=>x.entity_id))];const profiles=await profileMap(charIds);let guilds:any[]=[];if(guildIds.length){const q=await admin.from('guilds').select('id,name,tag,level,xp').in('id',guildIds);if(q.error)throw q.error;guilds=q.data??[];}const gm=new Map(guilds.map((g:any)=>[g.id,g]));const grouped:Record<string,any[]>={};for(const row of rows){(grouped[row.ranking_key]??=[]).push({...row,entity:row.entity_type==='character'?profiles.get(row.entity_id)??null:gm.get(row.entity_id)??null});}const mine:Record<string,any>={};const {data:myRows,error:myErr}=await admin.from('phase5_rankings').select('*').eq('entity_type','character').eq('entity_id',c.id);if(myErr)throw myErr;for(const r of myRows??[])mine[r.ranking_key]=r;return{groups:grouped,mine};}

async function eventsState(c:any){await rpc('phase5_refresh_events');const {data,error}=await admin.from('phase5_event_instances').select('*').gte('ends_at',new Date(Date.now()-24*3600_000).toISOString()).lte('starts_at',new Date(Date.now()+8*24*3600_000).toISOString()).order('starts_at');if(error)throw error;const defs=await admin.from('phase5_weekly_event_definitions').select('*');if(defs.error)throw defs.error;const dmap=new Map((defs.data??[]).map((d:any)=>[d.event_key,d]));const ids=(data??[]).map((x:any)=>x.id);let claims:any[]=[];if(ids.length){const q=await admin.from('phase5_event_claims').select('event_instance_id,claimed_at,reward').eq('character_id',c.id).in('event_instance_id',ids);if(q.error)throw q.error;claims=q.data??[];}const cmap=new Map(claims.map((x:any)=>[x.event_instance_id,x]));const templates=await admin.from('phase5_event_templates').select('*').eq('enabled',true).order('template_key');if(templates.error)throw templates.error;return{calendar:(data??[]).map((x:any)=>({...x,definition:dmap.get(x.event_key)??null,claim:cmap.get(x.id)??null})),templates:templates.data??[]};}

async function achievementsState(c:any){await rpc('phase5_sync_titles',{p_character:c.id});const [defs,owned,ach]=await Promise.all([admin.from('title_definitions').select('*').eq('enabled',true).order('title_key'),admin.from('character_titles').select('*').eq('character_id',c.id),admin.from('character_achievements').select('achievement_id,progress,unlocked_at').eq('character_id',c.id).like('achievement_id','phase5_%')]);for(const x of [defs,owned,ach])if(x.error)throw x.error;const have=new Set((owned.data??[]).map((x:any)=>x.title_key));return{titles:(defs.data??[]).map((d:any)=>({...d,unlocked:have.has(d.title_key),selected:c.selected_title_key===d.title_key})),achievements:ach.data??[],selectedTitle:c.selected_title_key??null};}

async function codexState(c:any){await rpc('phase5_sync_codex',{p_character:c.id});const [catalog,entries]=await Promise.all([admin.from('phase5_codex_catalog').select('*').order('category').order('entry_key'),admin.from('character_codex_entries').select('category,entry_key,unlocked_at').eq('character_id',c.id)]);if(catalog.error)throw catalog.error;if(entries.error)throw entries.error;const unlocked=new Set((entries.data??[]).map((x:any)=>`${x.category}:${x.entry_key}`));const categories=['monsters','bosses','equipment','sets','pets','resources','zones'];return{categories:categories.map(category=>{const items=(catalog.data??[]).filter((x:any)=>x.category===category);return{category,unlocked:items.filter((x:any)=>unlocked.has(`${category}:${x.entry_key}`)).length,total:items.length,items:items.map((x:any)=>({...x,unlocked:unlocked.has(`${category}:${x.entry_key}`)}))}})};}

async function notificationsState(c:any){await rpc('phase5_sync_notifications',{p_character:c.id});const {data,error}=await admin.from('player_notifications').select('*').eq('character_id',c.id).order('created_at',{ascending:false}).limit(30);if(error)throw error;return{items:data??[],unread:(data??[]).filter((x:any)=>!x.read_at).length};}

async function stateFor(user:any,message?:string){const c=await characterFor(user.id);await rpc('phase5_presence_touch',{p_character:c.id});const [pets,social,rankings,events,achievements,codex,notifications]=await Promise.all([petsState(c),socialState(c),rankingsState(c),eventsState(c),achievementsState(c),codexState(c),notificationsState(c)]);const chat=await chatState(c,social);return{ok:true,serverNow:new Date().toISOString(),...(message?{message}:{}),character:{id:c.id,name:c.name,class:c.class,level:Number(c.level),xp:Number(c.xp),renown:Number(c.renown),zoneId:c.zone_id,selectedTitle:c.selected_title_key},pets,social,chat,rankings,events,achievements,codex,notifications};}

async function safeSearch(c:any,query:string){const q=query.trim().replace(/[<>%_]/g,'').slice(0,24);if(q.length<2)return[];const {data,error}=await admin.from('characters').select('id,name,class,level,renown').ilike('name',`%${q}%`).neq('id',c.id).limit(12);if(error)throw error;const profiles=await profileMap((data??[]).map((x:any)=>x.id));return (data??[]).map((x:any)=>profiles.get(x.id)).filter(Boolean);}
async function safeInspect(c:any,target:string){if(!target)throw new Error('PLAYER_REQUIRED');const profiles=await profileMap([target]);const p=profiles.get(target);if(!p)throw new Error('PLAYER_NOT_FOUND');const [arena,stats,pets,codex]=await Promise.all([admin.from('phase2_arena_profiles').select('highest_rating,wins,losses').eq('character_id',target).order('highest_rating',{ascending:false}).limit(1).maybeSingle(),admin.from('character_stats').select('atk,def,strength,vitality,agility,intelligence,luck').eq('character_id',target).maybeSingle(),admin.from('character_pets').select('pet_key,level,evolution_stage').eq('character_id',target).eq('equipped',true).maybeSingle(),admin.from('character_codex_entries').select('entry_key',{count:'exact',head:true}).eq('character_id',target)]);for(const x of [arena,stats,pets,codex])if((x as any).error)throw (x as any).error;return{...p,arena:arena.data??null,stats:stats.data??null,equippedPet:pets.data??null,collectionCount:codex.count??0};}

async function action(user:any,name:string,payload:any){const c=await characterFor(user.id);let message='OK';const requestId=String(payload?.requestId||crypto.randomUUID());
 if(name==='petEquip'){await rpc('phase5_pet_equip',{p_character:c.id,p_pet:String(payload?.petId||'')});message='Mascota equipada';}
 else if(name==='petEvolve'){await rpc('phase5_pet_evolve',{p_character:c.id,p_pet:String(payload?.petId||''),p_receipt:requestId});message='Mascota evolucionada';}
 else if(name==='friendRequest'){await rpc('phase5_friend_request',{p_character:c.id,p_target:String(payload?.characterId||'')});message='Solicitud enviada';}
 else if(name==='friendRespond'){await rpc('phase5_friend_respond',{p_character:c.id,p_request:String(payload?.requestId||''),p_accept:Boolean(payload?.accept)});message=payload?.accept?'Amigo agregado':'Solicitud rechazada';}
 else if(name==='friendRemove'){await rpc('phase5_friend_remove',{p_character:c.id,p_target:String(payload?.characterId||'')});message='Amigo eliminado';}
 else if(name==='chatSend'){await rpc('phase5_chat_send',{p_character:c.id,p_channel:String(payload?.channel||'global'),p_body:String(payload?.body||'')});message='Mensaje enviado';}
 else if(name==='chatMute'){await rpc('phase5_chat_mute',{p_character:c.id,p_target:String(payload?.characterId||''),p_minutes:clamp(Number(payload?.minutes||1440),1,43200)});message='Jugador silenciado';}
 else if(name==='chatReport'){await rpc('phase5_chat_report',{p_character:c.id,p_message:String(payload?.messageId||''),p_reason:String(payload?.reason||'spam')});message='Reporte enviado';}
 else if(name==='eventClaim'){await rpc('phase5_claim_event',{p_character:c.id,p_event:String(payload?.eventId||''),p_receipt:requestId});message='Recompensa de evento reclamada';}
 else if(name==='titleSet'){await rpc('phase5_set_title',{p_character:c.id,p_title:payload?.titleKey?String(payload.titleKey):null});message='Título actualizado';}
 else if(name==='notificationRead'){const id=String(payload?.notificationId||'');const {error}=await admin.from('player_notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('character_id',c.id);if(error)throw error;message='Notificación leída';}
 else throw new Error('Unknown Phase 5 action');
 return stateFor(user,message);
}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);try{const user=await authUser(req),body=await req.json().catch(()=>({})),op=String(body?.op??'state');if(op==='state')return json(await stateFor(user));const c=await characterFor(user.id);if(op==='search')return json({ok:true,results:await safeSearch(c,String(body?.query||''))});if(op==='inspect')return json({ok:true,profile:await safeInspect(c,String(body?.characterId||''))});if(op==='action')return json(await action(user,String(body?.action||''),body?.payload??{}));return json({error:'unknown_operation'},400)}catch(e){const m=e instanceof Error?e.message:'request_failed';const status=m==='AUTH_REQUIRED'||m==='AUTH_INVALID'?401:/rate limit/i.test(m)?429:/permission|not unlocked/i.test(m)?403:400;return json({error:m},status)}});
