-- Crypto Factory Studios V0.2 payment foundation.
-- Applied automatically by backend/app/db.py for SQLite dev; keep this file for managed DB migration parity.
CREATE TABLE IF NOT EXISTS products(product_id TEXT PRIMARY KEY,label TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',price_usd TEXT NOT NULL,entitlement_key TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS payment_methods(method_id TEXT PRIMARY KEY,asset TEXT NOT NULL,network TEXT NOT NULL,standard TEXT NOT NULL,address TEXT NOT NULL,token_contract TEXT,enabled INTEGER NOT NULL DEFAULT 1,production_allowed INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS payment_quotes(quote_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,product_id TEXT NOT NULL,method_id TEXT NOT NULL,fiat_price_usd TEXT NOT NULL,crypto_amount TEXT NOT NULL,exchange_rate TEXT NOT NULL,rate_source TEXT NOT NULL,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS orders(order_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,product_id TEXT NOT NULL,quote_id TEXT NOT NULL,method_id TEXT NOT NULL,expected_amount TEXT NOT NULL,received_amount TEXT NOT NULL DEFAULT '0',asset TEXT NOT NULL,network TEXT NOT NULL,receiving_address TEXT NOT NULL,status TEXT NOT NULL,transaction_hash TEXT,created_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,confirmed_at INTEGER NOT NULL DEFAULT 0,fulfilled_at INTEGER NOT NULL DEFAULT 0,idempotency_key TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS blockchain_transactions(fingerprint TEXT PRIMARY KEY,network TEXT NOT NULL,transaction_hash TEXT NOT NULL,order_id TEXT NOT NULL,verification_json TEXT NOT NULL,consumed_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS payment_events(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL,event_type TEXT NOT NULL,details_json TEXT NOT NULL DEFAULT '{}',created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS purchase_history(purchase_id TEXT PRIMARY KEY,user_id TEXT NOT NULL,order_id TEXT NOT NULL UNIQUE,product_id TEXT NOT NULL,amount TEXT NOT NULL,asset TEXT NOT NULL,network TEXT NOT NULL,transaction_hash TEXT,created_at INTEGER NOT NULL);
