begin;

-- Global audit: cover every currently unindexed foreign-key lookup reported by the production schema.
create index if not exists ix_fk_bastion_buildings_building_key on public.bastion_buildings(building_key);
create index if not exists ix_fk_battle_pass_claims_season_level_track on public.battle_pass_claims(season_id,level,track);
create index if not exists ix_fk_battle_pass_progress_season on public.battle_pass_progress(season_id);
create index if not exists ix_fk_character_achievements_achievement on public.character_achievements(achievement_id);
create index if not exists ix_fk_character_skills_skill on public.character_skills(skill_id);
create index if not exists ix_fk_characters_zone on public.characters(zone_id);
create index if not exists ix_fk_combat_history_enemy on public.combat_history(enemy_id);
create index if not exists ix_fk_crafting_log_character on public.crafting_log(character_id);
create index if not exists ix_fk_crafting_log_recipe on public.crafting_log(recipe_id);
create index if not exists ix_fk_earn_task_claims_task on public.earn_task_claims(task_key);
create index if not exists ix_fk_equipment_armor_item on public.equipment(armor_item_id);
create index if not exists ix_fk_equipment_boots_item on public.equipment(boots_item_id);
create index if not exists ix_fk_equipment_ring_item on public.equipment(ring_item_id);
create index if not exists ix_fk_equipment_weapon_item on public.equipment(weapon_item_id);
create index if not exists ix_fk_expedition_runs_character on public.expedition_runs(character_id);
create index if not exists ix_fk_expedition_runs_expedition on public.expedition_runs(expedition_id);
create index if not exists ix_fk_founder_pack_orders_pack on public.founder_pack_orders(pack_key);
create index if not exists ix_fk_game_logs_character on public.game_logs(character_id);
create index if not exists ix_fk_game_sessions_user on public.game_sessions(user_id);
create index if not exists ix_fk_guild_activity_character on public.guild_activity(character_id);
create index if not exists ix_fk_guild_activity_guild on public.guild_activity(guild_id);
create index if not exists ix_fk_guild_audit_actor on public.guild_audit_log(actor_character_id);
create index if not exists ix_fk_guild_audit_target on public.guild_audit_log(target_character_id);
create index if not exists ix_fk_guild_buffs_activated_by on public.guild_buffs(activated_by);
create index if not exists ix_fk_guild_mission_claims_character on public.guild_mission_claims(character_id);
create index if not exists ix_fk_guild_raid_contributions_character on public.guild_raid_contributions(character_id);
create index if not exists ix_fk_guild_research_key on public.guild_research(research_key);
create index if not exists ix_fk_guild_shop_purchases_character on public.guild_shop_purchases(character_id);
create index if not exists ix_fk_guild_shop_purchases_item on public.guild_shop_purchases(item_key);
create index if not exists ix_fk_guild_wars_a on public.guild_wars(guild_a);
create index if not exists ix_fk_guild_wars_b on public.guild_wars(guild_b);
create index if not exists ix_fk_guild_weekly_claims_character on public.guild_weekly_claims(character_id);
create index if not exists ix_fk_guilds_owner on public.guilds(owner_character_id);
create index if not exists ix_fk_hunt_assignments_enemy on public.hunt_assignments(enemy_id);
create index if not exists ix_fk_item_instances_definition on public.item_instances(definition_id);
create index if not exists ix_fk_manual_combat_sessions_enemy on public.manual_combat_sessions(enemy_id);
create index if not exists ix_fk_marketplace_listing_item on public.marketplace_listings_demo(item_instance_id);
create index if not exists ix_fk_marketplace_listing_seller on public.marketplace_listings_demo(seller_character_id);
create index if not exists ix_fk_monster_codex_enemy on public.monster_codex(enemy_id);
create index if not exists ix_fk_phase3_specializations_recommended_set on public.phase3_specializations(recommended_set_id);
create index if not exists ix_fk_premium_shop_purchases_item on public.premium_shop_purchases(item_key);
create index if not exists ix_fk_profession_talent_progress_talent on public.profession_talent_progress(talent_id);
create index if not exists ix_fk_quest_progress_quest on public.quest_progress(quest_id);
create index if not exists ix_fk_quests_zone on public.quests(zone_id);
create index if not exists ix_fk_wallet_links_user on public.wallet_links(user_id);
create index if not exists ix_fk_world_event_contributions_character on public.world_event_contributions(character_id);

commit;
